/**
 * GROUP I - Asset Safety & Integrity (ISO 55001:2014)
 */
import { m, f, req, sel, num, dt, txt, WF, CHECK_RESULT, riskFields } from './defs.js';

export const group = { code: 'I', key: 'assetsafety', name: 'Asset Safety', icon: '🛠' };

export default [
  m({
    key: 'equipment_inspection',
    name: 'Equipment Inspection',
    nameId: 'Inspeksi Peralatan',
    icon: '🔩',
    codePrefix: 'EQI',
    scope: 'any',
    workflow: WF.INSPECTION,
    capa: true,
    standards: ['ISO 55001:2014 §8.1', 'ISO 45001:2018 §8.1'],
    regulations: [
      'Permenaker No. 08 Tahun 2020 (Pesawat Angkat dan Angkut)',
      'Permenaker No. 38 Tahun 2016 (Pesawat Tenaga dan Produksi)',
      'Permenaker No. 12 Tahun 2015 (Keselamatan Listrik)',
      'Permenaker No. 37 Tahun 2016 (Bejana Tekanan dan Tangki Timbun)',
    ],
    fields: [
      req('title', 'Judul Inspeksi'),
      req('asset_ref', 'Aset', 'asset'),
      sel('inspection_type', 'Jenis Inspeksi', ['Harian', 'Mingguan', 'Bulanan', 'Triwulanan', 'Tahunan', 'Riksa Uji Disnaker', 'Pra-Operasi', 'Setelah Perbaikan'], { required: true }),
      dt('inspection_date', 'Tanggal Inspeksi', { required: true }),
      f('inspector', 'Inspektor', 'user'),
      f('inspector_certified', 'Inspektor Bersertifikat / Ahli K3 Bidang', 'bool'),
      sel('visual_condition', 'Kondisi Visual', CHECK_RESULT, { required: true }),
      sel('function_test', 'Uji Fungsi', CHECK_RESULT),
      sel('safety_device', 'Alat Pengaman (Limit Switch/Emergency Stop)', CHECK_RESULT),
      sel('structural', 'Kondisi Struktur / Rangka', CHECK_RESULT),
      sel('lubrication', 'Pelumasan', CHECK_RESULT),
      sel('electrical', 'Sistem Kelistrikan', CHECK_RESULT),
      sel('hydraulic', 'Sistem Hidrolik/Pneumatik', CHECK_RESULT),
      num('operating_hours', 'Jam Operasi Kumulatif'),
      txt('findings', 'Temuan'),
      sel('result', 'Kesimpulan', ['Laik Operasi', 'Laik dengan Catatan', 'Tidak Laik Operasi'], { required: true }),
      f('tagged_out', 'Diberi Tanda Larangan Operasi (Tag Out)', 'bool'),
      txt('recommendation', 'Rekomendasi'),
      dt('next_inspection', 'Inspeksi Berikutnya', { alert: 'expiry' }),
    ],
  }),

  m({
    key: 'calibration',
    name: 'Calibration',
    nameId: 'Kalibrasi Alat Ukur',
    icon: '📏',
    codePrefix: 'CAL',
    scope: 'any',
    workflow: WF.MONITORING,
    capa: true,
    standards: ['ISO 9001:2015 §7.1.5', 'ISO 17025'],
    fields: [
      req('title', 'Nama Alat Ukur'),
      f('asset_ref', 'Aset', 'asset'),
      sel('instrument_type', 'Jenis Alat', ['Gas Detector', 'Sound Level Meter', 'Lux Meter', 'Timbangan / Jembatan Timbang', 'Manometer / Pressure Gauge', 'Termometer', 'Multimeter', 'Anemometer', 'Draft Gauge', 'Flow Meter', 'Alat Ukur Navigasi', 'Lainnya'], { required: true }),
      f('serial_number', 'Nomor Seri'),
      dt('calibration_date', 'Tanggal Kalibrasi', { required: true }),
      f('calibration_body', 'Lembaga Kalibrasi'),
      f('accreditation_no', 'Nomor Akreditasi (KAN)'),
      f('certificate_no', 'Nomor Sertifikat Kalibrasi'),
      num('deviation', 'Penyimpangan Terukur', { step: 0.0001 }),
      f('deviation_unit', 'Satuan Penyimpangan'),
      num('tolerance', 'Toleransi yang Diizinkan', { step: 0.0001 }),
      sel('result', 'Hasil', ['Sesuai (In Tolerance)', 'Perlu Penyetelan', 'Tidak Sesuai (Out of Tolerance)'], { required: true }),
      f('adjustment_done', 'Dilakukan Penyetelan', 'bool'),
      dt('valid_until', 'Berlaku Sampai', { required: true, alert: 'expiry' }),
      txt('impact_assessment', 'Evaluasi Dampak Bila Out of Tolerance'),
    ],
  }),

  m({
    key: 'maintenance',
    name: 'Maintenance',
    nameId: 'Pemeliharaan Aset',
    icon: '🔧',
    codePrefix: 'MNT',
    scope: 'any',
    workflow: WF.INSPECTION,
    capa: true,
    standards: ['ISO 55001:2014 §8.1'],
    regulations: ['ISM Code Element 10 - Maintenance of the Ship and Equipment'],
    fields: [
      req('title', 'Judul Pekerjaan Pemeliharaan'),
      req('asset_ref', 'Aset', 'asset'),
      sel('maintenance_type', 'Jenis Pemeliharaan', ['Preventif Terjadwal', 'Prediktif (Condition Based)', 'Korektif / Perbaikan', 'Darurat / Breakdown', 'Overhaul', 'Docking Kapal'], { required: true }),
      dt('plan_date', 'Tanggal Rencana'),
      dt('actual_date', 'Tanggal Pelaksanaan'),
      dt('completion_date', 'Tanggal Selesai'),
      txt('work_description', 'Uraian Pekerjaan', { required: true }),
      sel('executor_type', 'Pelaksana', ['Internal', 'Kontraktor', 'Galangan']),
      f('contractor_ref', 'Kontraktor', 'contractor'),
      f('spare_parts', 'Suku Cadang Digunakan', 'textarea'),
      num('downtime_hours', 'Downtime (jam)', { step: 0.1 }),
      num('cost', 'Biaya (IDR)', { type: 'currency' }),
      f('permit_required', 'Memerlukan Izin Kerja', 'bool'),
      f('permit_ref', 'Nomor Izin Kerja'),
      f('loto_applied', 'Isolasi Energi (LOTO) Diterapkan', 'bool'),
      sel('result', 'Hasil', ['Selesai - Normal', 'Selesai - dengan Catatan', 'Tertunda', 'Perlu Pekerjaan Lanjutan']),
      txt('post_maintenance_test', 'Hasil Uji Setelah Pemeliharaan'),
      dt('next_maintenance', 'Pemeliharaan Berikutnya', { alert: 'expiry' }),
    ],
  }),

  m({
    key: 'certification',
    name: 'Certification & Statutory Document',
    nameId: 'Sertifikat & Dokumen Statutori',
    icon: '📑',
    codePrefix: 'CRT',
    scope: 'any',
    workflow: WF.RECORD,
    capa: true,
    standards: ['ISO 55001:2014', 'ISO 45001:2018 §6.1.3'],
    regulations: [
      'UU No. 17 Tahun 2008 tentang Pelayaran',
      'Peraturan BKI tentang Klasifikasi Kapal',
      'Permenaker No. 08 Tahun 2020 (Suket Layak Pesawat Angkat)',
    ],
    fields: [
      req('title', 'Nama Sertifikat / Dokumen'),
      sel('holder_type', 'Objek Sertifikat', ['Kapal', 'Pelabuhan', 'Peralatan', 'Personil', 'Perusahaan'], { required: true }),
      f('asset_ref', 'Aset Terkait', 'asset'),
      sel('cert_category', 'Kategori', [
        'Sertifikat Keselamatan Kapal', 'Sertifikat Garis Muat', 'Sertifikat Klasifikasi BKI',
        'Safety Management Certificate (SMC)', 'Document of Compliance (DOC)',
        'International Ship Security Certificate (ISSC)', 'Sertifikat Pencegahan Pencemaran (IOPP)',
        'Surat Ukur', 'Surat Laut / Grosse Akta', 'Sertifikat Radio', 'Suket Layak Pesawat Angkat',
        'Sertifikat Instalasi Listrik', 'Sertifikat Bejana Tekan', 'Sertifikat Proteksi Kebakaran',
        'Izin Lingkungan', 'Izin TPS Limbah B3', 'Sertifikat Kompetensi Personil', 'Sertifikat ISO',
      ], { required: true }),
      f('certificate_no', 'Nomor Sertifikat', 'text', { required: true }),
      f('issuer', 'Penerbit'),
      dt('issue_date', 'Tanggal Terbit'),
      dt('valid_until', 'Berlaku Sampai', { required: true, alert: 'expiry' }),
      dt('endorsement_due', 'Jatuh Tempo Endorsement/Annual Survey', { alert: 'expiry' }),
      sel('cert_status', 'Status', ['Berlaku', 'Akan Kedaluwarsa', 'Kedaluwarsa', 'Dalam Proses Perpanjangan', 'Ditangguhkan'], { computed: 'certStatus' }),
      f('renewal_pic', 'PIC Perpanjangan', 'user'),
      num('renewal_lead_days', 'Lead Time Perpanjangan (hari)', { default: 60 }),
      txt('notes', 'Catatan'),
    ],
  }),

  m({
    key: 'asset_criticality',
    name: 'Asset Criticality',
    nameId: 'Kekritisan Aset',
    icon: '🎚',
    codePrefix: 'ACR',
    scope: 'any',
    workflow: WF.RISK,
    standards: ['ISO 55001:2014 §6.2.2', 'ISO 31000:2018'],
    fields: [
      req('title', 'Judul Penilaian'),
      req('asset_ref', 'Aset', 'asset'),
      dt('assessment_date', 'Tanggal Penilaian', { required: true }),
      sel('safety_impact', 'Dampak Keselamatan Bila Gagal', ['1 - Tidak Ada', '2 - Ringan', '3 - Sedang', '4 - Berat', '5 - Fatal'], { required: true }),
      sel('operational_impact', 'Dampak Operasional', ['1 - Tidak Ada', '2 - Ringan', '3 - Gangguan Sebagian', '4 - Gangguan Besar', '5 - Operasi Berhenti'], { required: true }),
      sel('environmental_impact', 'Dampak Lingkungan', ['1 - Tidak Ada', '2 - Ringan', '3 - Sedang', '4 - Berat', '5 - Sangat Berat']),
      sel('financial_impact', 'Dampak Finansial', ['1 - <10 Juta', '2 - 10-100 Juta', '3 - 100 Juta-1 M', '4 - 1-10 M', '5 - >10 M']),
      ...riskFields(),
      sel('criticality_class', 'Kelas Kekritisan', ['Kritis Tinggi', 'Kritis Sedang', 'Non-Kritis'], { computed: 'criticalityClass' }),
      sel('maintenance_strategy', 'Strategi Pemeliharaan', ['Preventive Maintenance Ketat', 'Condition Based Monitoring', 'Run to Failure', 'Redundansi / Standby Unit']),
      num('spare_stock_level', 'Level Stok Suku Cadang Kritis'),
      f('redundancy_available', 'Tersedia Redundansi', 'bool'),
      num('mtbf_hours', 'MTBF (jam)', { step: 0.1 }),
      num('mttr_hours', 'MTTR (jam)', { step: 0.1 }),
      txt('justification', 'Justifikasi Penilaian'),
    ],
  }),
];
