/**
 * GROUP G - Audit, Inspection & Management Review
 */
import { m, f, req, sel, num, dt, txt, WF } from './defs.js';

export const group = { code: 'G', key: 'audit', name: 'Audit & Compliance', nameId: 'Audit & Kepatuhan', icon: '🔎' };

const SYSTEMS = ['ISO 9001:2015', 'ISO 14001:2015', 'ISO 45001:2018', 'ISO 27001:2022', 'ISO 50001:2018', 'ISO 55001:2014', 'ISO 22301:2019', 'ISO 31000:2018', 'SMK3 PP 50/2012', 'ISM Code', 'ISPS Code', 'Terintegrasi'];

export default [
  m({
    key: 'internal_audit',
    name: 'Internal Audit',
    nameId: 'Audit Internal',
    icon: '🧾',
    codePrefix: 'IA',
    scope: 'any',
    workflow: WF.INSPECTION,
    capa: true,
    standards: ['ISO 9001:2015 §9.2', 'ISO 45001:2018 §9.2', 'ISO 14001:2015 §9.2', 'ISO 19011:2018'],
    regulations: ['PP No. 50 Tahun 2012 (SMK3) Elemen 11'],
    fields: [
      req('title', 'Judul Audit'),
      sel('system_ref', 'Sistem Manajemen yang Diaudit', SYSTEMS, { type: 'multiselect', required: true }),
      f('audit_program_year', 'Tahun Program Audit'),
      dt('plan_date', 'Tanggal Rencana', { required: true }),
      dt('actual_date', 'Tanggal Pelaksanaan'),
      f('auditee_unit', 'Unit yang Diaudit', 'text', { required: true }),
      f('lead_auditor', 'Ketua Tim Auditor', 'user', { required: true }),
      f('auditors', 'Anggota Tim Auditor'),
      txt('audit_scope', 'Ruang Lingkup Audit'),
      txt('audit_criteria', 'Kriteria Audit'),
      num('major_nc', 'Jumlah Ketidaksesuaian Mayor'),
      num('minor_nc', 'Jumlah Ketidaksesuaian Minor'),
      num('observations', 'Jumlah Observasi'),
      num('ofi', 'Peluang Perbaikan (OFI)'),
      num('conformity_rate', 'Tingkat Kesesuaian (%)', { step: 0.1, min: 0, max: 100 }),
      txt('positive_findings', 'Hal Positif'),
      txt('summary', 'Ringkasan Temuan'),
      txt('conclusion', 'Kesimpulan Auditor'),
      dt('report_date', 'Tanggal Laporan'),
      dt('follow_up_due', 'Batas Tindak Lanjut', { alert: 'due' }),
      sel('follow_up_status', 'Status Tindak Lanjut', ['Belum Dimulai', 'Sebagian Selesai', 'Selesai Seluruhnya']),
    ],
  }),

  m({
    key: 'external_audit',
    name: 'External Audit',
    nameId: 'Audit Eksternal & Sertifikasi',
    icon: '🏅',
    codePrefix: 'EA',
    scope: 'any',
    workflow: WF.INSPECTION,
    capa: true,
    standards: ['ISO 17021', 'ISO 19011:2018'],
    regulations: ['PP No. 50 Tahun 2012 - Audit SMK3 oleh Lembaga Audit Independen'],
    fields: [
      req('title', 'Judul Audit'),
      sel('audit_type', 'Jenis Audit', ['Sertifikasi Awal', 'Surveillance', 'Re-sertifikasi', 'Audit SMK3 Kemnaker', 'Audit ISM Code', 'Audit ISPS Code', 'Port State Control', 'Flag State Inspection', 'Audit Pelanggan', 'Audit Regulator', 'Audit BPK/SPI'], { required: true }),
      sel('system_ref', 'Sistem / Standar', SYSTEMS, { type: 'multiselect' }),
      f('auditor_body', 'Badan Auditor / Instansi', 'text', { required: true }),
      f('lead_auditor_ext', 'Lead Auditor'),
      dt('start_date', 'Tanggal Mulai', { required: true }),
      dt('end_date', 'Tanggal Selesai'),
      txt('audit_scope', 'Ruang Lingkup'),
      num('major_nc', 'Ketidaksesuaian Mayor'),
      num('minor_nc', 'Ketidaksesuaian Minor'),
      num('observations', 'Observasi'),
      sel('result', 'Hasil Audit', ['Direkomendasikan Sertifikasi', 'Sertifikasi Dilanjutkan', 'Perlu Tindak Lanjut', 'Ditangguhkan', 'Dicabut', 'Lulus', 'Tidak Lulus']),
      f('certificate_no', 'Nomor Sertifikat'),
      dt('certificate_valid_from', 'Sertifikat Berlaku Dari'),
      dt('certificate_expiry', 'Sertifikat Berlaku Sampai', { alert: 'expiry' }),
      num('smk3_score', 'Skor Penilaian SMK3 (%)', { min: 0, max: 100, help: 'Tingkat pencapaian penerapan SMK3 (PP 50/2012).' }),
      sel('smk3_level', 'Tingkat Pencapaian SMK3', ['Tingkat Awal (64 kriteria)', 'Tingkat Transisi (122 kriteria)', 'Tingkat Lanjutan (166 kriteria)']),
      txt('findings_summary', 'Ringkasan Temuan'),
      dt('follow_up_due', 'Batas Tindak Lanjut', { alert: 'due' }),
    ],
  }),

  m({
    key: 'inspection',
    name: 'General Inspection',
    nameId: 'Inspeksi Umum K3L',
    icon: '📋',
    codePrefix: 'INS',
    scope: 'any',
    workflow: WF.INSPECTION,
    capa: true,
    standards: ['ISO 45001:2018 §9.1', 'ISO 14001:2015 §9.1'],
    regulations: ['PP No. 50 Tahun 2012 (SMK3) Elemen 7'],
    fields: [
      req('title', 'Judul Inspeksi'),
      sel('inspection_type', 'Jenis Inspeksi', [
        'Inspeksi K3 Rutin', 'Inspeksi Housekeeping (5R)', 'Inspeksi APAR & Hydrant',
        'Inspeksi P3K', 'Inspeksi APD', 'Inspeksi Listrik', 'Inspeksi Alat Angkat',
        'Inspeksi Lingkungan', 'Inspeksi TPS Limbah B3', 'Safety Patrol Manajemen',
        'Inspeksi Kesiapan Darurat', 'Inspeksi Keamanan (ISPS)',
      ], { required: true }),
      dt('inspection_date', 'Tanggal Inspeksi', { required: true }),
      f('area', 'Area / Objek Inspeksi', 'text', { required: true }),
      f('inspector', 'Inspektor', 'user', { required: true }),
      f('accompanied_by', 'Didampingi Oleh'),
      num('items_checked', 'Jumlah Item Diperiksa'),
      num('items_conform', 'Item Sesuai'),
      num('findings_count', 'Jumlah Temuan'),
      num('conformity_rate', 'Tingkat Kesesuaian (%)', { computed: 'conformityRate', readonly: true }),
      num('critical_findings', 'Temuan Kritis'),
      txt('findings', 'Uraian Temuan'),
      txt('recommendation', 'Rekomendasi'),
      f('pic', 'Penanggung Jawab Tindak Lanjut', 'user'),
      dt('due_date', 'Target Penyelesaian', { alert: 'due' }),
      sel('follow_up_status', 'Status Tindak Lanjut', ['Belum Ditindaklanjuti', 'Dalam Proses', 'Selesai']),
    ],
  }),

  m({
    key: 'compliance_audit',
    name: 'Compliance Audit',
    nameId: 'Audit Kepatuhan Regulasi',
    icon: '⚖',
    codePrefix: 'CA',
    scope: 'any',
    workflow: WF.INSPECTION,
    capa: true,
    standards: ['ISO 14001:2015 §9.1.2', 'ISO 45001:2018 §9.1.2', 'ISO 37301'],
    fields: [
      req('title', 'Judul Audit Kepatuhan'),
      sel('regulator', 'Regulator / Domain', [
        'Kementerian Perhubungan', 'Kementerian Ketenagakerjaan (Disnaker)', 'KLHK / DLH',
        'Syahbandar / KSOP', 'BKI', 'OJK', 'Kementerian BUMN', 'Pemda', 'Internal',
      ], { required: true }),
      dt('audit_date', 'Tanggal Audit', { required: true }),
      f('auditor', 'Auditor / Pemeriksa'),
      txt('regulations_checked', 'Peraturan yang Dievaluasi'),
      num('obligations_total', 'Jumlah Kewajiban'),
      num('obligations_compliant', 'Kewajiban Dipenuhi'),
      num('compliance_rate', 'Tingkat Kepatuhan (%)', { computed: 'complianceRate', readonly: true }),
      num('non_compliance_count', 'Jumlah Ketidakpatuhan'),
      sel('risk_exposure', 'Eksposur Risiko Hukum', ['Rendah', 'Sedang', 'Tinggi', 'Kritis']),
      txt('findings', 'Temuan Ketidakpatuhan'),
      txt('sanction_risk', 'Potensi Sanksi'),
      txt('action_plan', 'Rencana Pemenuhan'),
      dt('due_date', 'Target Pemenuhan', { alert: 'due' }),
    ],
  }),

  m({
    key: 'management_review',
    name: 'Management Review',
    nameId: 'Tinjauan Manajemen',
    icon: '🏛',
    codePrefix: 'MR',
    scope: 'any',
    workflow: WF.SIMPLE,
    capa: true,
    standards: ['ISO 9001:2015 §9.3', 'ISO 45001:2018 §9.3', 'ISO 14001:2015 §9.3', 'ISO 27001:2022 §9.3'],
    regulations: ['PP No. 50 Tahun 2012 (SMK3) Elemen 12'],
    fields: [
      req('title', 'Judul Rapat Tinjauan Manajemen'),
      dt('meeting_date', 'Tanggal Rapat', { required: true }),
      f('location', 'Tempat'),
      f('chairperson', 'Pimpinan Rapat', 'user', { required: true }),
      f('attendees', 'Peserta', 'textarea'),
      sel('system_ref', 'Sistem yang Ditinjau', SYSTEMS, { type: 'multiselect' }),
      req('period_reviewed', 'Periode yang Ditinjau', 'text', { placeholder: 'Semester I 2026' }),
      txt('input_previous_actions', 'Status Tindakan Tinjauan Sebelumnya'),
      txt('input_context_changes', 'Perubahan Isu Internal & Eksternal'),
      txt('input_kpi', 'Kinerja Sasaran & KPI'),
      txt('input_audit', 'Hasil Audit'),
      txt('input_nc_capa', 'Ketidaksesuaian & Tindakan Korektif'),
      txt('input_incident', 'Kinerja Keselamatan & Insiden'),
      txt('input_environment', 'Kinerja Lingkungan & Kepatuhan'),
      txt('input_customer', 'Umpan Balik Pelanggan'),
      txt('input_risk', 'Efektivitas Pengelolaan Risiko & Peluang'),
      txt('input_resources', 'Kecukupan Sumber Daya'),
      txt('output_decisions', 'Keputusan & Tindakan', { required: true }),
      txt('output_improvement', 'Peluang Perbaikan'),
      txt('output_resource_needs', 'Kebutuhan Sumber Daya'),
      sel('system_effectiveness', 'Kesimpulan Efektivitas Sistem', ['Sangat Efektif', 'Efektif', 'Cukup Efektif', 'Perlu Perbaikan Signifikan']),
      dt('next_review', 'Rencana Tinjauan Berikutnya', { alert: 'expiry' }),
    ],
  }),
];
