/**
 * GROUP J - Contractor Safety Management (CSMS)
 */
import { m, f, req, sel, num, dt, txt, WF } from './defs.js';

export const group = { code: 'J', key: 'contractorsafety', name: 'Contractor Safety', icon: '🤝' };

export default [
  m({
    key: 'contractor_prequalification',
    name: 'Contractor Prequalification',
    nameId: 'Prakualifikasi Kontraktor (CSMS)',
    icon: '✅',
    codePrefix: 'CPQ',
    scope: 'any',
    workflow: WF.SIMPLE,
    capa: true,
    contractorAccess: true,
    standards: ['ISO 45001:2018 §8.1.4.2'],
    regulations: ['PP No. 50 Tahun 2012 (SMK3)', 'UU No. 1 Tahun 1970'],
    fields: [
      req('contractor_ref', 'Kontraktor', 'contractor'),
      dt('assessment_date', 'Tanggal Penilaian', { required: true }),
      f('scope_of_work', 'Lingkup Pekerjaan yang Dinilai'),
      sel('risk_level_work', 'Tingkat Risiko Pekerjaan', ['Rendah', 'Sedang', 'Tinggi'], { required: true }),
      num('score_commitment', 'Komitmen & Kepemimpinan K3 (0-100)', { min: 0, max: 100 }),
      num('score_procedure', 'Prosedur & Dokumentasi K3 (0-100)', { min: 0, max: 100 }),
      num('score_competency', 'Kompetensi & Pelatihan Pekerja (0-100)', { min: 0, max: 100 }),
      num('score_equipment', 'Peralatan & APD (0-100)', { min: 0, max: 100 }),
      num('score_performance', 'Kinerja K3 Historis (0-100)', { min: 0, max: 100 }),
      num('score_compliance', 'Kepatuhan Legal & BPJS (0-100)', { min: 0, max: 100 }),
      num('total_score', 'Skor Total (0-100)', { computed: 'csmsScore', readonly: true }),
      sel('grade', 'Grade', ['A - Sangat Baik', 'B - Baik', 'C - Cukup', 'D - Kurang', 'E - Tidak Layak'], { computed: 'csmsGrade' }),
      sel('result', 'Keputusan', ['Lulus Prakualifikasi', 'Lulus Bersyarat', 'Tidak Lulus'], { required: true }),
      txt('conditions', 'Persyaratan yang Harus Dipenuhi'),
      dt('valid_until', 'Berlaku Sampai', { alert: 'expiry' }),
      f('assessor', 'Penilai', 'user'),
    ],
  }),

  m({
    key: 'contractor_evaluation',
    name: 'Contractor Evaluation',
    nameId: 'Evaluasi Kinerja Kontraktor',
    icon: '📊',
    codePrefix: 'CEV',
    scope: 'any',
    workflow: WF.SIMPLE,
    capa: true,
    standards: ['ISO 9001:2015 §8.4.3', 'ISO 45001:2018 §8.1.4'],
    fields: [
      req('contractor_ref', 'Kontraktor', 'contractor'),
      req('period', 'Periode Evaluasi', 'text', { placeholder: '2026-Q1' }),
      dt('evaluation_date', 'Tanggal Evaluasi', { required: true }),
      f('project_name', 'Nama Pekerjaan / Proyek'),
      num('score_quality', 'Mutu Hasil Pekerjaan (0-100)', { min: 0, max: 100 }),
      num('score_hse', 'Kinerja K3L (0-100)', { min: 0, max: 100 }),
      num('score_timeliness', 'Ketepatan Waktu (0-100)', { min: 0, max: 100 }),
      num('score_cooperation', 'Kerja Sama & Komunikasi (0-100)', { min: 0, max: 100 }),
      num('score_documentation', 'Kelengkapan Dokumen (0-100)', { min: 0, max: 100 }),
      num('total_score', 'Skor Total', { computed: 'evalScore', readonly: true }),
      num('incident_count', 'Jumlah Insiden Selama Periode'),
      num('violation_count', 'Jumlah Pelanggaran K3'),
      num('stop_work_count', 'Jumlah Penghentian Pekerjaan'),
      sel('recommendation', 'Rekomendasi', ['Dapat Digunakan Kembali', 'Dapat Digunakan dengan Pembinaan', 'Peringatan Tertulis', 'Tidak Direkomendasikan', 'Usulan Blacklist'], { required: true }),
      txt('strengths', 'Kekuatan'),
      txt('improvement_areas', 'Area Perbaikan'),
      f('evaluator', 'Evaluator', 'user'),
    ],
  }),

  m({
    key: 'contractor_permit',
    name: 'Contractor Work Permit & Induction',
    nameId: 'Izin Masuk & Induksi Kontraktor',
    icon: '🪪',
    codePrefix: 'CIP',
    scope: 'any',
    workflow: WF.PERMIT,
    contractorAccess: true,
    standards: ['ISO 45001:2018 §7.2', 'ISO 45001:2018 §8.1.4'],
    regulations: ['ISPS Code - Kontrol Akses Fasilitas Pelabuhan'],
    fields: [
      req('contractor_ref', 'Kontraktor', 'contractor'),
      req('title', 'Pekerjaan / Keperluan'),
      dt('valid_from', 'Berlaku Mulai', { required: true }),
      dt('valid_to', 'Berlaku Sampai', { required: true, alert: 'expiry' }),
      num('worker_count', 'Jumlah Pekerja', { required: true }),
      f('worker_list', 'Daftar Pekerja', 'textarea'),
      f('area_access', 'Area yang Diakses', 'multiselect', {
        options: ['Dermaga', 'Terminal Penumpang', 'Kapal', 'Ruang Mesin Kapal', 'Bengkel', 'Gudang', 'Area Terbatas ISPS', 'Kantor', 'TPS Limbah B3'],
      }),
      f('induction_done', 'Induksi K3 Telah Dilaksanakan', 'bool', { required: true }),
      dt('induction_date', 'Tanggal Induksi'),
      num('induction_participants', 'Jumlah Peserta Induksi'),
      f('id_card_issued', 'Kartu Identitas Diterbitkan', 'bool'),
      f('vehicle_access', 'Akses Kendaraan'),
      f('equipment_brought', 'Peralatan yang Dibawa', 'textarea'),
      f('documents_verified', 'Dokumen Terverifikasi', 'multiselect', {
        options: ['Kontrak', 'BPJS Ketenagakerjaan', 'Sertifikat Kompetensi', 'JSA/HIRA', 'MSDS Bahan Kimia', 'Sertifikat Alat', 'Asuransi', 'Hasil MCU Pekerja'],
      }),
      f('supervisor_internal', 'Pengawas Internal', 'user'),
      txt('special_conditions', 'Ketentuan Khusus'),
    ],
  }),

  m({
    key: 'contractor_safety_performance',
    name: 'Contractor Safety Performance',
    nameId: 'Kinerja Keselamatan Kontraktor',
    icon: '📉',
    codePrefix: 'CSP',
    scope: 'any',
    workflow: WF.MONITORING,
    capa: true,
    standards: ['ISO 45001:2018 §9.1'],
    fields: [
      req('contractor_ref', 'Kontraktor', 'contractor'),
      req('period', 'Periode (YYYY-MM)', 'text', { placeholder: '2026-01', pattern: '^\\d{4}-\\d{2}$' }),
      num('manhours', 'Jam Kerja Kontraktor', { required: true }),
      num('worker_count', 'Jumlah Pekerja'),
      num('fatality', 'Fatality'),
      num('lti', 'Lost Time Injury (LTI)'),
      num('mtc', 'Medical Treatment Case'),
      num('fac', 'First Aid Case'),
      num('near_miss', 'Near Miss Dilaporkan'),
      num('unsafe_findings', 'Temuan Tindakan/Kondisi Tidak Aman'),
      num('lost_days', 'Hari Kerja Hilang'),
      num('ltifr', 'LTIFR (per 1 juta jam kerja)', { computed: 'ltifr', readonly: true }),
      num('trir', 'TRIR (per 1 juta jam kerja)', { computed: 'trir', readonly: true }),
      num('severity_rate', 'Severity Rate', { computed: 'severityRate', readonly: true }),
      num('toolbox_count', 'Jumlah Toolbox Meeting'),
      num('training_hours', 'Jam Pelatihan K3'),
      sel('performance_rating', 'Peringkat Kinerja', ['Sangat Baik', 'Baik', 'Cukup', 'Buruk'], { computed: 'safetyRating' }),
      txt('notes', 'Catatan'),
    ],
  }),
];
