/**
 * GROUP N - Business Continuity (ISO 22301), Energy (ISO 50001),
 * Information Security (ISO 27001) and Competency (ISO 45001 §7.2).
 */
import { m, f, req, sel, num, dt, txt, WF, riskFields, PRIORITY } from './defs.js';

export const group = { code: 'N', key: 'continuity', name: 'Continuity, Energy & Security', icon: '🔐' };

export default [
  m({
    key: 'business_impact_analysis',
    name: 'Business Impact Analysis',
    nameId: 'Analisis Dampak Bisnis (BIA)',
    icon: '📉',
    codePrefix: 'BIA',
    scope: 'any',
    workflow: WF.RISK,
    capa: true,
    standards: ['ISO 22301:2019 §8.2.2'],
    fields: [
      req('title', 'Nama Proses / Layanan Kritis'),
      sel('process_category', 'Kategori Proses', ['Operasi Kapal', 'Operasi Pelabuhan', 'Ticketing & Reservasi', 'Bongkar Muat', 'Keuangan', 'Teknologi Informasi', 'SDM', 'Pengadaan', 'Komunikasi Publik'], { required: true }),
      txt('process_description', 'Uraian Proses'),
      sel('criticality', 'Tingkat Kekritisan', PRIORITY, { required: true }),
      num('mtpd_hours', 'MTPD - Maximum Tolerable Period of Disruption (jam)', { required: true }),
      num('rto_hours', 'RTO - Recovery Time Objective (jam)', { required: true }),
      num('rpo_hours', 'RPO - Recovery Point Objective (jam)'),
      num('mbco', 'MBCO - Minimum Business Continuity Objective (%)', { min: 0, max: 100 }),
      num('financial_impact_daily', 'Dampak Finansial per Hari (IDR)', { type: 'currency' }),
      txt('impact_operational', 'Dampak Operasional'),
      txt('impact_reputation', 'Dampak Reputasi'),
      txt('impact_legal', 'Dampak Hukum & Regulasi'),
      f('dependencies', 'Ketergantungan Kritis', 'multiselect', {
        options: ['Listrik PLN', 'Sistem TI / Aplikasi', 'Jaringan Komunikasi', 'Pasokan BBM', 'Kapal Operasional', 'Movable Bridge', 'Pihak Ketiga / Vendor', 'Personil Kunci', 'Air Bersih'],
      }),
      f('resource_required', 'Sumber Daya Pemulihan Minimum', 'textarea'),
      f('bcp_ref', 'Rencana Kelangsungan Terkait'),
      dt('review_date', 'Tanggal Tinjauan', { alert: 'expiry' }),
    ],
  }),

  m({
    key: 'business_continuity_plan',
    name: 'Business Continuity Plan',
    nameId: 'Rencana Kelangsungan Usaha',
    icon: '🧯',
    codePrefix: 'BCP',
    scope: 'any',
    workflow: WF.DOC,
    capa: true,
    standards: ['ISO 22301:2019 §8.4'],
    regulations: ['Perka BNPB tentang Rencana Kontinjensi'],
    fields: [
      req('title', 'Judul Rencana'),
      sel('disruption_scenario', 'Skenario Gangguan', [
        'Gempa Bumi', 'Tsunami', 'Banjir', 'Angin Kencang / Badai', 'Erupsi Gunung Api',
        'Kebakaran Fasilitas', 'Kegagalan Listrik Total', 'Serangan Siber', 'Kegagalan Sistem TI',
        'Pandemi / Wabah', 'Kerusuhan Sosial', 'Ancaman Terorisme', 'Kelangkaan BBM',
        'Kecelakaan Kapal Besar', 'Penutupan Pelabuhan', 'Kehilangan Personil Kunci',
      ], { required: true }),
      f('scope_covered', 'Cakupan'),
      txt('activation_criteria', 'Kriteria Aktivasi', { required: true }),
      f('crisis_team_leader', 'Ketua Tim Krisis', 'user'),
      f('crisis_team', 'Anggota Tim Krisis', 'textarea'),
      txt('response_strategy', 'Strategi Respons'),
      txt('recovery_procedure', 'Prosedur Pemulihan', { required: true }),
      txt('communication_plan', 'Rencana Komunikasi Krisis'),
      f('alternate_site', 'Lokasi Alternatif'),
      f('backup_resources', 'Sumber Daya Cadangan', 'textarea'),
      num('target_rto_hours', 'Target RTO (jam)'),
      dt('last_tested', 'Terakhir Diuji'),
      sel('test_result', 'Hasil Pengujian Terakhir', ['Berhasil', 'Berhasil dengan Catatan', 'Gagal', 'Belum Diuji']),
      dt('next_test', 'Rencana Pengujian Berikutnya', { alert: 'expiry' }),
      dt('review_date', 'Tanggal Tinjauan', { alert: 'expiry' }),
    ],
  }),

  m({
    key: 'energy_review',
    name: 'Energy Review & Program',
    nameId: 'Tinjauan & Program Efisiensi Energi',
    icon: '🔋',
    codePrefix: 'ENR',
    scope: 'any',
    workflow: WF.CAPA,
    capa: true,
    standards: ['ISO 50001:2018 §6.3, §6.5'],
    regulations: ['PP No. 33 Tahun 2023 tentang Konservasi Energi', 'Permen ESDM No. 14 Tahun 2012'],
    fields: [
      req('title', 'Nama Program / Tinjauan Energi'),
      req('period', 'Periode', 'text', { placeholder: '2026' }),
      sel('seu_category', 'Significant Energy Use (SEU)', ['BBM Kapal', 'Genset Pelabuhan', 'Listrik Terminal', 'Pendingin Udara', 'Penerangan', 'Kendaraan Operasional', 'Pompa & Motor', 'Movable Bridge'], { required: true }),
      num('baseline_consumption', 'Konsumsi Baseline', { step: 0.01 }),
      f('baseline_unit', 'Satuan'),
      num('actual_consumption', 'Konsumsi Aktual', { step: 0.01 }),
      num('enpi_value', 'Nilai EnPI (Indikator Kinerja Energi)', { step: 0.0001 }),
      f('enpi_definition', 'Definisi EnPI'),
      num('target_reduction', 'Target Penurunan (%)', { step: 0.1 }),
      num('actual_reduction', 'Penurunan Aktual (%)', { computed: 'energyReduction', readonly: true }),
      num('energy_saving_value', 'Nilai Penghematan (IDR)', { type: 'currency' }),
      num('co2_avoided_ton', 'Emisi CO2 Dihindari (ton)', { step: 0.001 }),
      txt('improvement_action', 'Tindakan Efisiensi'),
      f('pic', 'Penanggung Jawab', 'user'),
      dt('due_date', 'Target Selesai', { alert: 'due' }),
      num('progress', 'Progres (%)', { min: 0, max: 100 }),
      num('investment', 'Investasi (IDR)', { type: 'currency' }),
      num('payback_months', 'Payback Period (bulan)', { step: 0.1 }),
    ],
  }),

  m({
    key: 'information_security',
    name: 'Information Security Event',
    nameId: 'Kejadian Keamanan Informasi',
    icon: '🔒',
    codePrefix: 'ISE',
    scope: 'any',
    workflow: WF.REPORT,
    capa: true,
    standards: ['ISO 27001:2022 §A.5.24 - A.5.28'],
    regulations: [
      'UU No. 27 Tahun 2022 tentang Pelindungan Data Pribadi',
      'PP No. 71 Tahun 2019 tentang Penyelenggaraan Sistem dan Transaksi Elektronik',
    ],
    fields: [
      req('title', 'Judul Kejadian'),
      dt('event_date', 'Tanggal Kejadian', { required: true }),
      dt('detected_date', 'Tanggal Terdeteksi'),
      sel('event_type', 'Jenis Kejadian', [
        'Akses Tidak Sah', 'Malware / Ransomware', 'Phishing', 'Kebocoran Data',
        'Kehilangan Perangkat', 'Gangguan Layanan (DoS)', 'Kesalahan Konfigurasi',
        'Pelanggaran Kebijakan', 'Kegagalan Backup', 'Kerentanan Ditemukan', 'Social Engineering',
      ], { required: true }),
      sel('cia_impact', 'Aspek Terdampak', ['Kerahasiaan (Confidentiality)', 'Integritas (Integrity)', 'Ketersediaan (Availability)'], { type: 'multiselect' }),
      sel('severity', 'Tingkat Keparahan', PRIORITY, { required: true }),
      f('affected_system', 'Sistem / Aset Informasi Terdampak'),
      f('personal_data_involved', 'Melibatkan Data Pribadi', 'bool'),
      num('records_affected', 'Jumlah Data Terdampak'),
      num('downtime_hours', 'Downtime (jam)', { step: 0.1 }),
      txt('description', 'Uraian Kejadian', { required: true }),
      txt('containment_action', 'Tindakan Penanggulangan'),
      txt('root_cause', 'Akar Masalah'),
      f('reported_authority', 'Dilaporkan ke Otoritas (Kominfo/BSSN)', 'bool'),
      dt('resolved_date', 'Tanggal Pemulihan'),
      txt('lesson_learned', 'Pembelajaran'),
      ...riskFields('potential_'),
    ],
  }),

  m({
    key: 'training_competency',
    name: 'Training & Competency',
    nameId: 'Pelatihan & Kompetensi',
    icon: '🎓',
    codePrefix: 'TRN',
    scope: 'any',
    workflow: WF.SIMPLE,
    capa: true,
    standards: ['ISO 45001:2018 §7.2', 'ISO 9001:2015 §7.2', 'STCW'],
    regulations: [
      'PP No. 50 Tahun 2012 (SMK3) Elemen 4 & 12',
      'Permenaker No. 02/MEN/1992 (Ahli K3)',
      'STCW - Sertifikasi Pelaut',
    ],
    fields: [
      req('title', 'Judul Pelatihan'),
      sel('training_category', 'Kategori', [
        'Induksi K3', 'Pelatihan Wajib Regulasi', 'Sertifikasi Kompetensi', 'Refreshment',
        'Pelatihan Darurat', 'Pelatihan Sistem Manajemen', 'Pelatihan Teknis', 'Pelatihan Pelayanan',
      ], { required: true }),
      sel('topic', 'Topik', [
        'Ahli K3 Umum', 'P3K di Tempat Kerja', 'Pemadam Kebakaran', 'Bekerja di Ketinggian',
        'Ruang Terbatas', 'LOTO', 'Operator Forklift', 'Operator Crane', 'Basic Safety Training (BST)',
        'Survival Craft (SCRB)', 'Advanced Fire Fighting (AFF)', 'Medical First Aid (MFA)',
        'Penanganan B3 & IMDG', 'Auditor Internal ISO', 'HIRADC', 'Investigasi Insiden',
        'Penanggulangan Tumpahan Minyak', 'Keamanan Informasi', 'Pelayanan Prima', 'ISPS Code',
      ]),
      dt('start_date', 'Tanggal Mulai', { required: true }),
      dt('end_date', 'Tanggal Selesai'),
      num('duration_hours', 'Durasi (jam)'),
      f('provider', 'Penyelenggara'),
      f('trainer', 'Instruktur'),
      sel('mandatory', 'Sifat', ['Wajib Regulasi', 'Wajib Internal', 'Pengembangan']),
      num('planned_participants', 'Target Peserta'),
      num('actual_participants', 'Realisasi Peserta'),
      f('participants', 'Daftar Peserta', 'textarea'),
      num('pretest_avg', 'Rata-rata Pre-Test', { step: 0.1 }),
      num('posttest_avg', 'Rata-rata Post-Test', { step: 0.1 }),
      num('pass_count', 'Jumlah Lulus'),
      f('certificate_issued', 'Sertifikat Diterbitkan', 'bool'),
      dt('certificate_valid_until', 'Sertifikat Berlaku Sampai', { alert: 'expiry' }),
      num('cost', 'Biaya (IDR)', { type: 'currency' }),
      sel('effectiveness', 'Evaluasi Efektivitas', ['Sangat Efektif', 'Efektif', 'Cukup', 'Kurang Efektif', 'Belum Dievaluasi']),
      txt('evaluation_note', 'Catatan Evaluasi'),
    ],
  }),
];
