/**
 * GROUP B - Document Management (ISO 9001:2015 §7.5 Documented Information)
 */
import { m, f, req, sel, num, dt, txt, WF } from './defs.js';

export const group = { code: 'B', key: 'document', name: 'Document Management', nameId: 'Manajemen Dokumen', icon: '📄' };

const DOC_LEVELS = ['Level 1 - Manual', 'Level 2 - Prosedur', 'Level 3 - Instruksi Kerja', 'Level 4 - Formulir & Rekaman'];
const SYSTEMS = ['ISO 9001', 'ISO 14001', 'ISO 45001', 'ISO 27001', 'ISO 50001', 'ISO 55001', 'ISO 22301', 'SMK3', 'ISM Code', 'ISPS Code', 'Terintegrasi'];

export default [
  m({
    key: 'document_control',
    name: 'Document Control',
    nameId: 'Pengendalian Dokumen',
    icon: '📁',
    codePrefix: 'DOC',
    scope: 'any',
    workflow: WF.DOC,
    standards: ['ISO 9001:2015 §7.5', 'ISO 14001:2015 §7.5', 'ISO 45001:2018 §7.5'],
    fields: [
      req('title', 'Judul Dokumen'),
      req('doc_number', 'Nomor Dokumen'),
      sel('doc_level', 'Level Dokumen', DOC_LEVELS, { required: true }),
      sel('management_system', 'Sistem Manajemen', SYSTEMS, { multi: true, type: 'multiselect' }),
      f('revision', 'Revisi', 'text', { placeholder: '00' }),
      dt('effective_date', 'Tanggal Berlaku', { required: true }),
      dt('review_due', 'Jadwal Tinjauan Berikutnya', { alert: 'expiry' }),
      f('owner_unit', 'Unit Pemilik'),
      f('prepared_by', 'Disusun Oleh', 'user'),
      f('reviewed_by', 'Diperiksa Oleh', 'user'),
      f('approved_by', 'Disetujui Oleh', 'user'),
      sel('confidentiality', 'Klasifikasi Informasi', ['Publik', 'Internal', 'Rahasia', 'Sangat Rahasia'], { help: 'ISO 27001 A.5.12 - klasifikasi informasi' }),
      txt('summary', 'Ringkasan Isi'),
      f('retention_period', 'Masa Retensi'),
    ],
  }),

  m({
    key: 'sop',
    name: 'Standard Operating Procedure',
    nameId: 'Prosedur Operasi Standar (SOP)',
    icon: '📘',
    codePrefix: 'SOP',
    scope: 'any',
    workflow: WF.DOC,
    standards: ['ISO 9001:2015 §8.1'],
    regulations: ['SOP Syahbandar', 'SOP Pelabuhan Penyeberangan'],
    fields: [
      req('title', 'Judul SOP'),
      req('doc_number', 'Nomor SOP'),
      sel('process_area', 'Area Proses', [
        'Operasi Pelabuhan', 'Operasi Kapal', 'Bongkar Muat', 'Ticketing & Pelayanan Penumpang',
        'Pemeliharaan', 'K3', 'Lingkungan', 'Mutu', 'Keamanan', 'Pengadaan', 'SDM', 'Keuangan', 'TI',
      ], { required: true }),
      sel('management_system', 'Sistem Manajemen', SYSTEMS, { type: 'multiselect' }),
      f('revision', 'Revisi'),
      dt('effective_date', 'Tanggal Berlaku'),
      dt('review_due', 'Tinjauan Berikutnya', { alert: 'expiry' }),
      txt('purpose', 'Tujuan'),
      txt('scope_text', 'Ruang Lingkup'),
      txt('procedure_steps', 'Langkah Prosedur'),
      txt('references', 'Referensi & Regulasi Terkait'),
      f('related_forms', 'Formulir Terkait'),
      f('owner_unit', 'Unit Pemilik'),
    ],
  }),

  m({
    key: 'work_instruction',
    name: 'Work Instruction',
    nameId: 'Instruksi Kerja',
    icon: '📗',
    codePrefix: 'IK',
    scope: 'any',
    workflow: WF.DOC,
    standards: ['ISO 9001:2015 §8.5.1'],
    fields: [
      req('title', 'Judul Instruksi Kerja'),
      req('doc_number', 'Nomor IK'),
      f('parent_sop', 'SOP Induk'),
      f('revision', 'Revisi'),
      dt('effective_date', 'Tanggal Berlaku'),
      txt('steps', 'Langkah Kerja'),
      f('required_ppe', 'APD Wajib', 'multiselect', {
        options: ['Helm', 'Sepatu Safety', 'Rompi Reflektif', 'Sarung Tangan', 'Kacamata Safety', 'Pelindung Telinga', 'Masker/Respirator', 'Life Jacket', 'Full Body Harness', 'Wearpack'],
        help: 'Permenakertrans No. 08 Tahun 2010 tentang APD',
      }),
      txt('hazards', 'Bahaya Terkait'),
      f('competency_required', 'Kompetensi yang Dipersyaratkan'),
    ],
  }),

  m({
    key: 'form_management',
    name: 'Form Management',
    nameId: 'Pengendalian Formulir',
    icon: '🧾',
    codePrefix: 'FRM',
    scope: 'any',
    workflow: WF.DOC,
    standards: ['ISO 9001:2015 §7.5.3'],
    fields: [
      req('title', 'Nama Formulir'),
      req('doc_number', 'Nomor Formulir'),
      f('parent_document', 'Dokumen Induk'),
      f('revision', 'Revisi'),
      dt('effective_date', 'Tanggal Berlaku'),
      sel('media', 'Media', ['Digital (Aplikasi)', 'Cetak', 'Digital & Cetak']),
      f('retention_period', 'Masa Retensi Rekaman'),
      f('storage_location', 'Lokasi Penyimpanan'),
    ],
  }),

  m({
    key: 'external_regulation',
    name: 'External Regulation',
    nameId: 'Dokumen Eksternal / Regulasi',
    icon: '📜',
    codePrefix: 'REG',
    scope: 'corporate',
    workflow: WF.RECORD,
    standards: ['ISO 9001:2015 §7.5.3.2'],
    fields: [
      req('title', 'Judul Peraturan'),
      req('reg_number', 'Nomor Peraturan'),
      sel('issuer', 'Instansi Penerbit', [
        'Kementerian Perhubungan', 'Kementerian Ketenagakerjaan', 'Kementerian LHK',
        'Kementerian BUMN', 'OJK', 'Pemerintah Daerah', 'BKI', 'IMO', 'ISO', 'GRI', 'Lainnya',
      ], { required: true }),
      sel('domain', 'Bidang', ['Pelayaran', 'Kepelabuhanan', 'K3', 'Lingkungan', 'Mutu', 'Keamanan Informasi', 'ESG', 'Energi', 'Aset']),
      dt('issued_date', 'Tanggal Terbit'),
      dt('effective_date', 'Tanggal Berlaku'),
      sel('status_regulation', 'Status', ['Berlaku', 'Dicabut', 'Diubah', 'Draft']),
      txt('summary', 'Ringkasan / Pasal Relevan'),
      f('source_url', 'Tautan Sumber'),
    ],
  }),

  m({
    key: 'legal_register',
    name: 'Legal Register & Compliance Obligation',
    nameId: 'Daftar Peraturan & Evaluasi Kepatuhan',
    icon: '⚖',
    codePrefix: 'LGL',
    scope: 'any',
    workflow: WF.MONITORING,
    capa: true,
    standards: ['ISO 14001:2015 §9.1.2', 'ISO 45001:2018 §9.1.2'],
    regulations: ['PP No. 50 Tahun 2012 (SMK3) Elemen 1.1'],
    fields: [
      req('title', 'Kewajiban / Persyaratan'),
      f('regulation_ref', 'Acuan Peraturan', { required: true }),
      sel('domain', 'Bidang', ['Pelayaran', 'Kepelabuhanan', 'K3', 'Lingkungan', 'Mutu', 'Ketenagakerjaan', 'Keamanan Informasi', 'Perizinan']),
      f('applicable_to', 'Berlaku Untuk'),
      f('responsible_unit', 'Unit Penanggung Jawab'),
      sel('compliance_status', 'Status Kepatuhan', ['Patuh', 'Patuh Sebagian', 'Tidak Patuh', 'Belum Dievaluasi'], { required: true }),
      dt('last_evaluation', 'Tanggal Evaluasi Terakhir'),
      dt('next_evaluation', 'Evaluasi Berikutnya', { alert: 'expiry' }),
      txt('evidence', 'Bukti Kepatuhan'),
      txt('gap', 'Kesenjangan / Temuan'),
      txt('action_plan', 'Rencana Tindak Lanjut'),
      f('permit_number', 'Nomor Izin Terkait'),
      dt('permit_expiry', 'Masa Berlaku Izin', { alert: 'expiry' }),
    ],
  }),

  m({
    key: 'document_revision',
    name: 'Document Revision',
    nameId: 'Riwayat Revisi Dokumen',
    icon: '🕓',
    codePrefix: 'REV',
    scope: 'any',
    workflow: WF.SIMPLE,
    standards: ['ISO 9001:2015 §7.5.2'],
    fields: [
      req('document_ref', 'Dokumen'),
      req('revision_from', 'Revisi Dari'),
      req('revision_to', 'Revisi Menjadi'),
      dt('revision_date', 'Tanggal Revisi', { required: true }),
      sel('revision_type', 'Jenis Perubahan', ['Perubahan Minor', 'Perubahan Mayor', 'Penerbitan Baru', 'Penarikan Dokumen']),
      txt('change_description', 'Uraian Perubahan', { required: true }),
      txt('reason', 'Alasan Perubahan'),
      f('requested_by', 'Diusulkan Oleh', 'user'),
      f('approved_by', 'Disetujui Oleh', 'user'),
      f('obsolete_copy_withdrawn', 'Salinan Kedaluwarsa Ditarik', 'bool'),
    ],
  }),

  m({
    key: 'distribution_matrix',
    name: 'Distribution Matrix',
    nameId: 'Matriks Distribusi Dokumen',
    icon: '🔀',
    codePrefix: 'DIS',
    scope: 'any',
    workflow: WF.SIMPLE,
    standards: ['ISO 9001:2015 §7.5.3'],
    fields: [
      req('document_ref', 'Dokumen'),
      req('recipient_unit', 'Unit Penerima'),
      f('recipient', 'Penerima', 'user'),
      sel('copy_type', 'Jenis Salinan', ['Terkendali', 'Tidak Terkendali', 'Salinan Elektronik']),
      f('copy_number', 'Nomor Salinan'),
      dt('distributed_date', 'Tanggal Distribusi'),
      f('acknowledged', 'Diterima & Dipahami', 'bool'),
      dt('acknowledged_date', 'Tanggal Konfirmasi'),
    ],
  }),
];
