/**
 * GROUP F - Environmental Management (ISO 14001:2015, ISO 50001:2018) + ESG
 */
import { m, f, req, sel, num, dt, txt, WF, riskFields } from './defs.js';

export const group = { code: 'F', key: 'environment', name: 'Environment & Energy', icon: '🌿' };

export default [
  m({
    key: 'waste_management',
    name: 'Waste Management (Non B3)',
    nameId: 'Pengelolaan Limbah Non-B3',
    icon: '🗑',
    codePrefix: 'WST',
    scope: 'any',
    workflow: WF.MONITORING,
    standards: ['ISO 14001:2015 §8.1'],
    regulations: [
      'UU No. 18 Tahun 2008 tentang Pengelolaan Sampah',
      'PP No. 22 Tahun 2021 tentang Penyelenggaraan Perlindungan dan Pengelolaan Lingkungan Hidup',
      'MARPOL Annex V - Garbage',
    ],
    fields: [
      req('period', 'Periode (YYYY-MM)', 'text', { placeholder: '2026-01', pattern: '^\\d{4}-\\d{2}$' }),
      sel('waste_type', 'Jenis Limbah', ['Sampah Domestik', 'Sampah Organik', 'Plastik', 'Kertas & Karton', 'Logam', 'Kaca', 'Kayu', 'Limbah Kapal (Garbage MARPOL V)', 'Puing Konstruksi'], { required: true }),
      sel('source', 'Sumber', ['Terminal Penumpang', 'Kapal', 'Perkantoran', 'Dermaga', 'Kantin', 'Bengkel', 'Area Parkir']),
      num('quantity', 'Jumlah', { required: true, step: 0.01 }),
      sel('unit', 'Satuan', ['kg', 'ton', 'm3'], { required: true }),
      sel('treatment', 'Penanganan', ['Diangkut ke TPA', 'Daur Ulang', 'Bank Sampah', 'Komposting', 'Diserahkan ke Pihak Ketiga', 'Reception Facility Pelabuhan'], { required: true }),
      num('recycled_qty', 'Jumlah Didaur Ulang', { step: 0.01 }),
      num('recycle_rate', 'Tingkat Daur Ulang (%)', { computed: 'recycleRate', readonly: true }),
      f('vendor', 'Pihak Pengangkut / Pengolah'),
      f('manifest_no', 'Nomor Bukti Serah Terima'),
      txt('notes', 'Catatan'),
    ],
  }),

  m({
    key: 'hazardous_waste',
    name: 'Hazardous Waste (B3)',
    nameId: 'Pengelolaan Limbah B3',
    icon: '☣',
    codePrefix: 'B3',
    scope: 'any',
    workflow: WF.MONITORING,
    capa: true,
    standards: ['ISO 14001:2015 §8.1'],
    regulations: [
      'PP No. 22 Tahun 2021 Lampiran IX (Daftar Limbah B3)',
      'PermenLHK No. 6 Tahun 2021 tentang Tata Cara dan Persyaratan Pengelolaan Limbah B3',
      'MARPOL Annex I - Oil',
    ],
    fields: [
      req('period', 'Periode (YYYY-MM)', 'text', { placeholder: '2026-01', pattern: '^\\d{4}-\\d{2}$' }),
      sel('waste_code', 'Kode Limbah B3', [
        'A102d - Aki/Baterai Bekas', 'A106d - Limbah Terkontaminasi B3', 'B105d - Minyak Pelumas Bekas',
        'B104d - Kemasan Bekas B3', 'B107d - Limbah Elektronik', 'B110d - Kain Majun Terkontaminasi',
        'A337-1 - Sludge Oil / Oily Water', 'B353-1 - Filter Bekas', 'A337-2 - Limbah Cat & Thinner',
        'B109d - Lampu TL Bekas', 'A339-1 - Limbah Medis', 'Lainnya',
      ], { required: true }),
      f('waste_name', 'Nama Limbah', 'text', { required: true }),
      sel('source', 'Sumber Limbah', ['Kapal - Ruang Mesin', 'Kapal - Akomodasi', 'Bengkel Pelabuhan', 'Genset', 'Klinik', 'Perkantoran', 'Kegiatan Docking', 'Movable Bridge / Alat Berat']),
      sel('characteristic', 'Karakteristik', ['Mudah Meledak', 'Mudah Menyala', 'Reaktif', 'Beracun', 'Infeksius', 'Korosif', 'Berbahaya Bagi Lingkungan'], { type: 'multiselect' }),
      num('quantity', 'Jumlah Dihasilkan', { required: true, step: 0.001 }),
      sel('unit', 'Satuan', ['kg', 'ton', 'liter', 'drum', 'unit'], { required: true }),
      num('stored_qty', 'Jumlah Tersimpan di TPS', { step: 0.001 }),
      dt('storage_start', 'Tanggal Mulai Disimpan'),
      num('storage_days', 'Lama Penyimpanan (hari)', { computed: 'storageDays', readonly: true, help: 'Maksimal 90 hari untuk limbah >50 kg/hari (PermenLHK 6/2021).' }),
      f('storage_compliant', 'Penyimpanan Sesuai Ketentuan', 'bool', { computed: 'b3StorageCompliant' }),
      f('tps_permit_no', 'Nomor Izin TPS Limbah B3'),
      sel('disposal_method', 'Metode Pengelolaan', ['Diserahkan ke Pengumpul Berizin', 'Diserahkan ke Pemanfaat', 'Dimusnahkan Pihak Ketiga', 'Diolah Sendiri', 'Masih Disimpan'], { required: true }),
      f('transporter', 'Pengangkut Berizin'),
      f('transporter_permit', 'Nomor Izin Pengangkut'),
      f('processor', 'Pengolah / Pemanfaat Berizin'),
      f('manifest_no', 'Nomor Manifes (Festronik)'),
      dt('manifest_date', 'Tanggal Manifes'),
      f('reported_siraja', 'Dilaporkan via SIRAJA Limbah', 'bool'),
      txt('notes', 'Catatan'),
    ],
  }),

  m({
    key: 'air_emission',
    name: 'Air Emission',
    nameId: 'Pemantauan Emisi Udara',
    icon: '💨',
    codePrefix: 'EMS',
    scope: 'any',
    workflow: WF.MONITORING,
    capa: true,
    standards: ['ISO 14001:2015 §9.1'],
    regulations: [
      'PP No. 22 Tahun 2021 Lampiran VII (Baku Mutu Emisi)',
      'PermenLHK No. 11 Tahun 2021 (Baku Mutu Emisi Mesin dengan Pembakaran Dalam)',
      'MARPOL Annex VI - Air Pollution',
    ],
    fields: [
      dt('sampling_date', 'Tanggal Pengukuran', { required: true }),
      sel('source_type', 'Sumber Emisi', ['Genset Pelabuhan', 'Mesin Induk Kapal', 'Mesin Bantu Kapal', 'Boiler', 'Insinerator', 'Kendaraan Operasional', 'Ambien Pelabuhan'], { required: true }),
      f('source_name', 'Nama / Kode Sumber'),
      f('asset_ref', 'Aset', 'asset'),
      f('lab_name', 'Laboratorium Penguji'),
      f('lab_accreditation', 'Nomor Akreditasi Lab (KAN)'),
      num('so2', 'SO2 (mg/Nm3)', { step: 0.01 }),
      num('no2', 'NO2 (mg/Nm3)', { step: 0.01 }),
      num('co', 'CO (mg/Nm3)', { step: 0.01 }),
      num('particulate', 'Partikulat (mg/Nm3)', { step: 0.01 }),
      num('opacity', 'Opasitas (%)', { step: 0.1 }),
      num('o2_reference', 'O2 Referensi (%)', { step: 0.1 }),
      sel('compliance', 'Status Baku Mutu', ['Memenuhi', 'Melebihi Baku Mutu', 'Sebagian Melebihi'], { required: true }),
      txt('exceedance_note', 'Parameter yang Melebihi'),
      txt('corrective_action', 'Tindakan Perbaikan'),
      dt('next_sampling', 'Pengukuran Berikutnya', { alert: 'expiry' }),
      f('reported_slhi', 'Dilaporkan dalam SIMPEL/SLHI', 'bool'),
    ],
  }),

  m({
    key: 'water_quality',
    name: 'Water Quality & Waste Water',
    nameId: 'Kualitas Air & Air Limbah',
    icon: '💧',
    codePrefix: 'AIR',
    scope: 'any',
    workflow: WF.MONITORING,
    capa: true,
    standards: ['ISO 14001:2015 §9.1'],
    regulations: [
      'PP No. 22 Tahun 2021 Lampiran VI (Baku Mutu Air Limbah)',
      'PermenLHK No. 5 Tahun 2014 tentang Baku Mutu Air Limbah',
      'Kepmen LH No. 51 Tahun 2004 tentang Baku Mutu Air Laut',
      'MARPOL Annex IV - Sewage',
    ],
    fields: [
      dt('sampling_date', 'Tanggal Pengambilan Sampel', { required: true }),
      sel('sample_type', 'Jenis Sampel', ['Air Laut (Kolam Pelabuhan)', 'Air Limbah Domestik (IPAL)', 'Air Limbah Kapal (Sewage)', 'Air Bilga', 'Air Bersih', 'Air Tanah / Sumur Pantau'], { required: true }),
      f('sampling_point', 'Titik Sampling', 'text', { required: true }),
      f('lab_name', 'Laboratorium Penguji'),
      num('ph', 'pH', { step: 0.01 }),
      num('bod', 'BOD (mg/L)', { step: 0.01 }),
      num('cod', 'COD (mg/L)', { step: 0.01 }),
      num('tss', 'TSS (mg/L)', { step: 0.01 }),
      num('oil_grease', 'Minyak & Lemak (mg/L)', { step: 0.01 }),
      num('ammonia', 'Amonia NH3-N (mg/L)', { step: 0.001 }),
      num('total_coliform', 'Total Coliform (MPN/100mL)', { step: 1 }),
      num('do_value', 'DO (mg/L)', { step: 0.01 }),
      num('salinity', 'Salinitas (‰)', { step: 0.01 }),
      num('debit', 'Debit Air Limbah (m3/bulan)', { step: 0.01 }),
      sel('compliance', 'Status Baku Mutu', ['Memenuhi', 'Melebihi Baku Mutu', 'Sebagian Melebihi'], { required: true }),
      txt('exceedance_note', 'Parameter yang Melebihi'),
      txt('corrective_action', 'Tindakan Perbaikan'),
      f('sppl_permit', 'Nomor Izin Pembuangan Air Limbah'),
      dt('next_sampling', 'Pengambilan Sampel Berikutnya', { alert: 'expiry' }),
    ],
  }),

  m({
    key: 'fuel_consumption',
    name: 'Fuel & Energy Consumption',
    nameId: 'Konsumsi Energi & BBM',
    icon: '⛽',
    codePrefix: 'ENG',
    scope: 'any',
    workflow: WF.MONITORING,
    standards: ['ISO 50001:2018 §6.3', 'ISO 14001:2015'],
    regulations: ['PP No. 33 Tahun 2023 tentang Konservasi Energi', 'Permen ESDM tentang Manajemen Energi'],
    fields: [
      req('period', 'Periode (YYYY-MM)', 'text', { placeholder: '2026-01', pattern: '^\\d{4}-\\d{2}$' }),
      sel('energy_type', 'Jenis Energi', ['Solar / HSD (Kapal)', 'Solar / HSD (Genset)', 'MFO', 'Bensin (Kendaraan Operasional)', 'Listrik PLN', 'Pelumas', 'Air Bersih (PDAM)', 'LPG'], { required: true }),
      sel('consumer_type', 'Pengguna', ['Kapal', 'Pelabuhan', 'Kantor', 'Kendaraan Operasional', 'Alat Berat'], { required: true }),
      f('asset_ref', 'Aset / Unit', 'asset'),
      num('quantity', 'Konsumsi', { required: true, step: 0.01 }),
      sel('unit', 'Satuan', ['liter', 'kg', 'ton', 'kWh', 'm3'], { required: true }),
      num('cost', 'Biaya (IDR)', { type: 'currency' }),
      num('operating_hours', 'Jam Operasi', { step: 0.1 }),
      num('distance_nm', 'Jarak Tempuh (mil laut)', { step: 0.1 }),
      num('trips', 'Jumlah Trip'),
      num('cargo_tonnage', 'Muatan Diangkut (ton)', { step: 0.01 }),
      num('specific_consumption', 'Konsumsi Spesifik', { computed: 'specificConsumption', readonly: true, help: 'Konsumsi per jam operasi / per trip.' }),
      num('co2e_kg', 'Emisi CO2e (kg)', { computed: 'co2e', readonly: true, help: 'Dihitung otomatis dari faktor emisi.' }),
      txt('efficiency_note', 'Catatan Efisiensi'),
    ],
  }),

  m({
    key: 'carbon_footprint',
    name: 'Carbon Footprint',
    nameId: 'Jejak Karbon (GRK)',
    icon: '🌍',
    codePrefix: 'GRK',
    scope: 'any',
    workflow: WF.MONITORING,
    standards: ['ISO 14064-1', 'GHG Protocol', 'IMO DCS / CII'],
    regulations: ['Perpres No. 98 Tahun 2021 tentang Nilai Ekonomi Karbon', 'PermenLHK No. 21 Tahun 2022'],
    fields: [
      req('period', 'Periode (YYYY-MM atau YYYY)', 'text', { placeholder: '2026-01' }),
      sel('scope_ghg', 'Cakupan Emisi', ['Scope 1 - Emisi Langsung', 'Scope 2 - Energi Tidak Langsung', 'Scope 3 - Lainnya'], { required: true }),
      sel('emission_source', 'Sumber Emisi', ['Pembakaran BBM Kapal', 'Genset Pelabuhan', 'Kendaraan Operasional', 'Konsumsi Listrik PLN', 'Refrigeran', 'Perjalanan Dinas', 'Limbah', 'Rantai Pasok'], { required: true }),
      num('activity_data', 'Data Aktivitas', { required: true, step: 0.01 }),
      f('activity_unit', 'Satuan Data Aktivitas'),
      num('emission_factor', 'Faktor Emisi (kg CO2e/satuan)', { step: 0.00001 }),
      f('factor_source', 'Sumber Faktor Emisi', 'text', { placeholder: 'IPCC 2006 / KLHK / DEFRA' }),
      num('co2e_ton', 'Emisi (ton CO2e)', { computed: 'co2eTon', readonly: true }),
      num('baseline_ton', 'Baseline (ton CO2e)', { step: 0.001 }),
      num('reduction_percent', 'Penurunan vs Baseline (%)', { computed: 'reductionPercent', readonly: true }),
      txt('reduction_initiative', 'Inisiatif Dekarbonisasi'),
      f('verified_external', 'Diverifikasi Pihak Ketiga', 'bool'),
      f('verifier', 'Lembaga Verifikasi'),
    ],
  }),

  m({
    key: 'esg',
    name: 'ESG Disclosure',
    nameId: 'Kinerja & Pengungkapan ESG',
    icon: '🌱',
    codePrefix: 'ESG',
    scope: 'any',
    workflow: WF.MONITORING,
    standards: ['GRI Standards', 'SASB', 'TCFD'],
    regulations: [
      'POJK No. 51/POJK.03/2017 tentang Keuangan Berkelanjutan',
      'SEOJK No. 16/SEOJK.04/2021 tentang Laporan Keberlanjutan',
    ],
    fields: [
      req('title', 'Nama Indikator ESG'),
      sel('pillar', 'Pilar', ['Environmental', 'Social', 'Governance'], { required: true }),
      f('gri_code', 'Kode GRI', 'text', { placeholder: 'GRI 305-1' }),
      f('sdg_ref', 'Kontribusi SDGs', 'multiselect', {
        options: ['SDG 3 - Kesehatan', 'SDG 5 - Kesetaraan Gender', 'SDG 6 - Air Bersih', 'SDG 7 - Energi Bersih', 'SDG 8 - Pekerjaan Layak', 'SDG 9 - Infrastruktur', 'SDG 11 - Kota Berkelanjutan', 'SDG 12 - Konsumsi Bertanggung Jawab', 'SDG 13 - Aksi Iklim', 'SDG 14 - Ekosistem Laut', 'SDG 16 - Kelembagaan'],
      }),
      req('period', 'Periode', 'text', { placeholder: '2026' }),
      f('unit', 'Satuan'),
      num('target', 'Target', { step: 0.01 }),
      num('actual', 'Realisasi', { step: 0.01 }),
      num('previous_year', 'Realisasi Tahun Sebelumnya', { step: 0.01 }),
      sel('polarity', 'Arah Pencapaian', ['Semakin Tinggi Semakin Baik', 'Semakin Rendah Semakin Baik']),
      num('achievement', 'Pencapaian (%)', { computed: 'kpiAchievement', readonly: true }),
      sel('assurance', 'Tingkat Asurans', ['Belum Diasuransi', 'Limited Assurance', 'Reasonable Assurance']),
      txt('narrative', 'Narasi Pengungkapan'),
      f('disclosed_in_report', 'Diungkapkan dalam Laporan Keberlanjutan', 'bool'),
    ],
  }),

  m({
    key: 'environmental_monitoring',
    name: 'Environmental Monitoring',
    nameId: 'Pemantauan Lingkungan (RKL-RPL)',
    icon: '🔬',
    codePrefix: 'ENV',
    scope: 'any',
    workflow: WF.MONITORING,
    capa: true,
    standards: ['ISO 14001:2015 §9.1.1'],
    regulations: ['PP No. 22 Tahun 2021 - Dokumen AMDAL / UKL-UPL', 'Pelaporan RKL-RPL Semesteran'],
    fields: [
      req('title', 'Judul Pemantauan'),
      dt('monitoring_date', 'Tanggal Pemantauan', { required: true }),
      sel('parameter_group', 'Kelompok Parameter', ['Kualitas Air Laut', 'Kualitas Udara Ambien', 'Kebisingan', 'Getaran', 'Biota Perairan', 'Sedimen', 'Abrasi & Sedimentasi Pantai', 'Sosial Ekonomi Masyarakat', 'Kesehatan Masyarakat'], { required: true }),
      f('location_point', 'Titik Pemantauan', 'text', { required: true }),
      num('latitude', 'Lintang', { step: 0.000001 }),
      num('longitude', 'Bujur', { step: 0.000001 }),
      f('parameter_name', 'Parameter'),
      num('result_value', 'Hasil Pengukuran', { step: 0.0001 }),
      f('result_unit', 'Satuan'),
      num('threshold_value', 'Baku Mutu', { step: 0.0001 }),
      sel('compliance', 'Status', ['Memenuhi', 'Melebihi Baku Mutu'], { required: true }),
      f('noise_day', 'Kebisingan Siang (dBA)', 'number', { step: 0.1 }),
      f('noise_night', 'Kebisingan Malam (dBA)', 'number', { step: 0.1 }),
      f('lab_name', 'Laboratorium'),
      sel('document_ref', 'Dokumen Lingkungan Acuan', ['AMDAL', 'UKL-UPL', 'SPPL', 'DELH/DPLH']),
      sel('reporting_period', 'Periode Pelaporan RKL-RPL', ['Semester I', 'Semester II']),
      f('reported_to_dlh', 'Dilaporkan ke DLH/KLHK', 'bool'),
      txt('analysis', 'Analisis & Evaluasi'),
      txt('corrective_action', 'Tindakan Pengelolaan'),
    ],
  }),

  m({
    key: 'spill_management',
    name: 'Spill Management',
    nameId: 'Penanggulangan Tumpahan',
    icon: '🛢',
    codePrefix: 'SPL',
    scope: 'any',
    workflow: WF.REPORT,
    capa: true,
    standards: ['ISO 14001:2015 §8.2'],
    regulations: [
      'Perpres No. 109 Tahun 2006 tentang Penanggulangan Keadaan Darurat Tumpahan Minyak di Laut',
      'MARPOL Annex I',
      'PP No. 22 Tahun 2021',
    ],
    fields: [
      req('title', 'Judul Kejadian'),
      dt('spill_date', 'Tanggal Kejadian', { required: true }),
      f('spill_time', 'Waktu', 'time'),
      sel('material', 'Jenis Bahan Tumpah', ['Minyak Pelumas', 'Solar / HSD', 'MFO', 'Sludge Oil', 'Bahan Kimia', 'Air Ballast Terkontaminasi', 'Sewage', 'Lainnya'], { required: true }),
      num('volume_liter', 'Perkiraan Volume (liter)', { required: true, step: 0.1 }),
      sel('medium', 'Media Terdampak', ['Perairan / Laut', 'Daratan / Dermaga', 'Dek Kapal', 'Saluran Drainase', 'Tanah'], { required: true }),
      sel('cause', 'Penyebab', ['Kebocoran Peralatan', 'Kesalahan Operasi Bunkering', 'Kegagalan Selang/Sambungan', 'Overflow Tangki', 'Kecelakaan Kapal', 'Vandalisme', 'Cuaca Ekstrem']),
      f('location', 'Lokasi Tumpahan'),
      txt('description', 'Kronologi', { required: true }),
      num('response_time_minutes', 'Waktu Respons (menit)'),
      f('containment_used', 'Peralatan Penanggulangan', 'multiselect', {
        options: ['Oil Boom', 'Oil Absorbent Pad', 'Sorbent Boom', 'Dispersant', 'Skimmer', 'Vacuum Truck', 'Pasir/Serbuk Gergaji', 'Drum Penampung'],
      }),
      num('recovered_liter', 'Volume Terkumpul (liter)', { step: 0.1 }),
      num('recovery_rate', 'Tingkat Pemulihan (%)', { computed: 'recoveryRate', readonly: true }),
      f('reported_ksop', 'Dilaporkan ke KSOP/Syahbandar', 'bool'),
      f('reported_klhk', 'Dilaporkan ke KLHK/DLH', 'bool'),
      txt('environmental_impact', 'Dampak Lingkungan'),
      txt('remediation', 'Pemulihan Lingkungan'),
      num('cost', 'Biaya Penanggulangan (IDR)', { type: 'currency' }),
      ...riskFields('potential_'),
    ],
  }),
];
