/**
 * GROUP A - Governance & Master Data
 *
 * These modules are flagged `master: true`. Master records are the reference
 * data every other module points at (ports, vessels, employees, assets ...)
 * and they are what row-level security is computed from.
 */
import { m, f, req, sel, num, dt, txt, WF, PRIORITY } from './defs.js';

export const group = { code: 'A', key: 'governance', name: 'Governance & Master Data', nameId: 'Tata Kelola & Data Induk', icon: '⚙' };

export default [
  m({
    key: 'company_profile',
    name: 'Company Profile',
    nameId: 'Profil Perusahaan',
    master: true,
    singleton: true,
    scope: 'corporate',
    codePrefix: 'CP',
    icon: '🏢',
    standards: ['ISO 9001:2015 §4.1'],
    workflow: WF.RECORD,
    labelField: 'name',
    fields: [
      req('name', 'Nama Perusahaan'),
      f('legal_name', 'Nama Badan Hukum'),
      f('npwp', 'NPWP'),
      f('address', 'Alamat', 'textarea'),
      f('phone', 'Telepon'),
      f('email', 'Email'),
      f('website', 'Website'),
      txt('vision', 'Visi'),
      txt('mission', 'Misi'),
      txt('qhse_policy', 'Kebijakan QHSE', { help: 'Kebijakan mutu, K3, lingkungan dan keselamatan pelayaran terintegrasi.' }),
      dt('policy_date', 'Tanggal Kebijakan'),
      f('policy_signed_by', 'Ditandatangani Oleh'),
      f('iso_certificates', 'Sertifikasi ISO Aktif', 'multiselect', {
        options: ['ISO 9001:2015', 'ISO 14001:2015', 'ISO 45001:2018', 'ISO 27001:2022', 'ISO 50001:2018', 'ISO 55001:2014', 'ISO 22301:2019', 'SMK3 PP 50/2012', 'ISM Code', 'ISPS Code'],
      }),
    ],
  }),

  m({
    key: 'region',
    name: 'Regional',
    nameId: 'Wilayah / Regional',
    master: true,
    scope: 'corporate',
    orgFields: [],
    codePrefix: 'REG',
    icon: '🗺',
    workflow: WF.RECORD,
    fields: [
      req('name', 'Nama Regional'),
      f('head_office', 'Kantor Regional'),
      f('manager', 'General Manager', 'user'),
      f('area_description', 'Cakupan Wilayah', 'textarea'),
    ],
  }),

  m({
    key: 'branch',
    name: 'Branch',
    nameId: 'Cabang',
    master: true,
    scope: 'corporate',
    orgFields: ['region'],
    orgRequired: ['region'],
    codePrefix: 'BR',
    icon: '🏛',
    workflow: WF.RECORD,
    fields: [
      req('name', 'Nama Cabang'),
      f('address', 'Alamat', 'textarea'),
      f('manager', 'Kepala Cabang', 'user'),
      num('employee_count', 'Jumlah Karyawan'),
      f('phone', 'Telepon'),
    ],
  }),

  m({
    key: 'port',
    name: 'Port',
    nameId: 'Pelabuhan Penyeberangan',
    master: true,
    scope: 'corporate',
    orgFields: ['region', 'branch'],
    orgRequired: ['region', 'branch'],
    codePrefix: 'PLB',
    icon: '⚓',
    standards: ['ISO 55001:2014'],
    regulations: ['PP No. 61 Tahun 2009 tentang Kepelabuhanan', 'UU No. 17 Tahun 2008 tentang Pelayaran'],
    workflow: WF.RECORD,
    fields: [
      req('name', 'Nama Pelabuhan'),
      sel('port_class', 'Kelas Pelabuhan', ['Kelas I', 'Kelas II', 'Kelas III', 'Pelabuhan Perintis']),
      f('province', 'Provinsi'),
      f('city', 'Kabupaten/Kota'),
      num('latitude', 'Lintang', { step: 0.000001 }),
      num('longitude', 'Bujur', { step: 0.000001 }),
      num('berth_count', 'Jumlah Dermaga'),
      num('mb_count', 'Jumlah Movable Bridge'),
      num('max_draft', 'Kedalaman Kolam (m)', { step: 0.1 }),
      f('syahbandar_office', 'Kantor Syahbandar'),
      f('harbourmaster', 'Nama Syahbandar'),
      f('operating_hours', 'Jam Operasi'),
      num('annual_passengers', 'Estimasi Penumpang/Tahun'),
      num('annual_vehicles', 'Estimasi Kendaraan/Tahun'),
      f('env_permit_no', 'No. Izin Lingkungan (AMDAL/UKL-UPL)'),
      dt('env_permit_expiry', 'Masa Berlaku Izin Lingkungan', { alert: 'expiry' }),
      f('tps_b3_permit_no', 'No. Izin TPS Limbah B3'),
      dt('tps_b3_permit_expiry', 'Masa Berlaku Izin TPS B3', { alert: 'expiry' }),
    ],
  }),

  m({
    key: 'vessel',
    name: 'Vessel Management',
    nameId: 'Manajemen Kapal',
    master: true,
    scope: 'corporate',
    orgFields: ['region', 'branch'],
    codePrefix: 'KPL',
    icon: '🚢',
    standards: ['ISO 55001:2014', 'ISO 45001:2018'],
    regulations: [
      'UU No. 17 Tahun 2008 tentang Pelayaran',
      'PP No. 20 Tahun 2010 tentang Angkutan di Perairan',
      'ISM Code / SOLAS',
      'Klasifikasi Biro Klasifikasi Indonesia (BKI)',
    ],
    workflow: WF.RECORD,
    fields: [
      req('name', 'Nama Kapal'),
      f('call_sign', 'Call Sign'),
      f('imo_number', 'Nomor IMO'),
      f('mmsi', 'MMSI'),
      sel('vessel_type', 'Tipe Kapal', ['KMP Ro-Ro', 'KMP Ro-Pax', 'Kapal Cepat', 'Landing Craft Tank', 'Tug Boat', 'Kapal Kerja']),
      num('gt', 'Gross Tonnage (GT)'),
      num('dwt', 'Deadweight (DWT)'),
      num('loa', 'LOA (m)', { step: 0.01 }),
      num('breadth', 'Lebar (m)', { step: 0.01 }),
      num('draft', 'Sarat Maksimum (m)', { step: 0.01 }),
      num('year_built', 'Tahun Pembuatan'),
      f('shipyard', 'Galangan Pembuat'),
      num('pax_capacity', 'Kapasitas Penumpang'),
      num('vehicle_capacity', 'Kapasitas Kendaraan (SUP)'),
      num('crew_capacity', 'Jumlah ABK'),
      num('deck_count', 'Jumlah Dek Kendaraan'),
      f('master_name', 'Nakhoda', 'user'),
      f('route', 'Lintasan Operasi'),
      f('class_society', 'Badan Klasifikasi', 'select', { options: ['BKI', 'BKI + IACS', 'Lloyd’s Register', 'Nippon Kaiji Kyokai', 'Lainnya'] }),
      f('class_notation', 'Notasi Klas BKI'),
      dt('class_survey_due', 'Jatuh Tempo Survey Klas', { alert: 'expiry' }),
      dt('docking_last', 'Docking Terakhir'),
      dt('docking_next', 'Rencana Docking Berikutnya', { alert: 'expiry' }),
      f('smc_no', 'No. Safety Management Certificate (SMC)'),
      dt('smc_expiry', 'Masa Berlaku SMC', { alert: 'expiry' }),
      f('issc_no', 'No. ISSC (ISPS)'),
      dt('issc_expiry', 'Masa Berlaku ISSC', { alert: 'expiry' }),
      f('sertifikat_keselamatan_no', 'No. Sertifikat Keselamatan Kapal'),
      dt('sertifikat_keselamatan_expiry', 'Masa Berlaku Sertifikat Keselamatan', { alert: 'expiry' }),
      sel('operational_status', 'Status Operasional', ['Beroperasi', 'Docking', 'Perbaikan', 'Idle', 'Tidak Laik Laut']),
    ],
  }),

  m({
    key: 'org_unit',
    name: 'Organization Structure',
    nameId: 'Struktur Organisasi',
    master: true,
    scope: 'any',
    codePrefix: 'ORG',
    icon: '🧩',
    standards: ['ISO 9001:2015 §5.3'],
    regulations: ['PP No. 50 Tahun 2012 (SMK3) - Struktur P2K3'],
    workflow: WF.RECORD,
    fields: [
      req('name', 'Nama Unit Kerja'),
      sel('level', 'Tingkat', ['Direktorat', 'Divisi', 'Departemen', 'Cabang', 'Pelabuhan', 'Kapal', 'Seksi']),
      f('parent_unit', 'Unit Induk'),
      f('head', 'Kepala Unit', 'user'),
      num('headcount', 'Jumlah Personil'),
      txt('responsibility', 'Tanggung Jawab QHSE'),
      f('is_p2k3', 'Merupakan Unit P2K3', 'bool', { help: 'Panitia Pembina K3 sesuai Permenaker No. 04/MEN/1987' }),
    ],
  }),

  m({
    key: 'employee',
    name: 'Employee',
    nameId: 'Data Pegawai',
    master: true,
    scope: 'any',
    codePrefix: 'PEG',
    icon: '👤',
    workflow: WF.RECORD,
    fields: [
      req('name', 'Nama Lengkap'),
      f('nip', 'NIP / NIK Pegawai'),
      sel('employment_type', 'Status Kepegawaian', ['Organik', 'PKWT', 'Outsourcing', 'ABK', 'Magang']),
      f('position', 'Jabatan'),
      f('department', 'Departemen'),
      dt('join_date', 'Tanggal Bergabung'),
      dt('birth_date', 'Tanggal Lahir'),
      sel('gender', 'Jenis Kelamin', ['Laki-laki', 'Perempuan']),
      sel('work_location_type', 'Lokasi Kerja', ['Kantor Pusat', 'Regional', 'Cabang', 'Pelabuhan', 'Kapal']),
      f('certifications', 'Sertifikat Kompetensi', 'multiselect', {
        options: ['Ahli K3 Umum', 'Ahli K3 Migas', 'Petugas P3K', 'Operator Forklift', 'Operator Crane', 'ANT-I', 'ANT-II', 'ANT-III', 'ANT-IV', 'ANT-V', 'ATT-I', 'ATT-II', 'ATT-III', 'ATT-IV', 'ATT-V', 'BST', 'SCRB', 'AFF', 'MFA', 'Auditor Internal ISO'],
      }),
      dt('cert_expiry', 'Masa Berlaku Sertifikat Terdekat', { alert: 'expiry' }),
      dt('last_mcu', 'MCU Terakhir'),
      sel('fit_to_work', 'Status Kelaikan Kerja', ['Fit', 'Fit with Note', 'Temporary Unfit', 'Unfit']),
      f('emergency_contact', 'Kontak Darurat'),
    ],
  }),

  m({
    key: 'asset',
    name: 'Asset Register',
    nameId: 'Daftar Aset',
    master: true,
    scope: 'any',
    codePrefix: 'AST',
    icon: '🛠',
    standards: ['ISO 55001:2014'],
    regulations: [
      'Permenaker No. 08 Tahun 2020 (Pesawat Angkat dan Angkut)',
      'Permenaker No. 12 Tahun 2015 (Listrik)',
      'Permenaker No. 37 Tahun 2016 (Bejana Tekan)',
    ],
    workflow: WF.RECORD,
    fields: [
      req('name', 'Nama Aset'),
      sel('category', 'Kategori Aset', [
        'Dermaga', 'Movable Bridge', 'Gangway', 'Ramp Door', 'Bow Door', 'Stern Door',
        'Genset / Generator', 'Crane', 'Forklift', 'Kendaraan Operasional', 'Fender',
        'Bollard', 'Pompa Kebakaran', 'APAR', 'Hydrant', 'LSA (Life Saving Appliance)',
        'Bejana Tekan', 'Instalasi Listrik', 'Mesin Induk Kapal', 'Mesin Bantu Kapal',
        'Peralatan Navigasi', 'IPAL', 'TPS Limbah B3', 'Lainnya',
      ], { required: true }),
      sel('asset_class', 'Klasifikasi', ['Kritis Keselamatan', 'Kritis Operasi', 'Pendukung']),
      f('manufacturer', 'Pabrikan'),
      f('model', 'Tipe / Model'),
      f('serial_number', 'Nomor Seri'),
      dt('commission_date', 'Tanggal Operasi'),
      num('capacity', 'Kapasitas', { step: 0.01 }),
      f('capacity_unit', 'Satuan Kapasitas'),
      sel('condition', 'Kondisi', ['Baik', 'Perlu Perbaikan', 'Rusak', 'Tidak Beroperasi']),
      dt('last_inspection', 'Inspeksi Terakhir'),
      dt('next_inspection', 'Inspeksi Berikutnya', { alert: 'expiry' }),
      f('permit_required', 'Wajib Riksa-Uji Disnaker', 'bool'),
      f('permit_number', 'No. Surat Keterangan Layak (Suket)'),
      dt('permit_expiry', 'Masa Berlaku Suket', { alert: 'expiry' }),
      num('replacement_value', 'Nilai Aset (IDR)', { type: 'currency' }),
    ],
  }),

  m({
    key: 'manhours',
    name: 'Man Hours Record',
    nameId: 'Rekaman Jam Kerja',
    master: true,
    scope: 'any',
    codePrefix: 'MH',
    icon: '⏱',
    standards: ['ISO 45001:2018 §9.1'],
    workflow: WF.RECORD,
    labelField: 'period',
    fields: [
      req('period', 'Periode (YYYY-MM)', 'text', { placeholder: '2026-01', pattern: '^\\d{4}-\\d{2}$' }),
      num('employee_hours', 'Jam Kerja Pegawai', { required: true }),
      num('contractor_hours', 'Jam Kerja Kontraktor'),
      num('crew_hours', 'Jam Kerja ABK'),
      num('total_hours', 'Total Jam Kerja', { computed: 'sumHours', readonly: true }),
      num('headcount', 'Jumlah Pekerja'),
    ],
  }),

  m({
    key: 'contractor',
    name: 'Contractor Management',
    nameId: 'Manajemen Kontraktor',
    master: true,
    scope: 'any',
    codePrefix: 'KTR',
    icon: '🤝',
    standards: ['ISO 45001:2018 §8.1.4'],
    regulations: ['UU No. 1 Tahun 1970', 'PP No. 50 Tahun 2012 (SMK3)'],
    workflow: WF.RECORD,
    contractorAccess: true,
    fields: [
      req('name', 'Nama Perusahaan Kontraktor'),
      f('npwp', 'NPWP'),
      f('address', 'Alamat', 'textarea'),
      f('pic_name', 'Nama PIC'),
      f('pic_phone', 'Telepon PIC'),
      f('pic_email', 'Email PIC'),
      sel('work_type', 'Jenis Pekerjaan', ['Konstruksi', 'Pemeliharaan', 'Docking & Reparasi Kapal', 'Kebersihan', 'Keamanan', 'Bongkar Muat', 'Katering', 'Pengelolaan Limbah', 'Konsultan', 'Lainnya']),
      sel('risk_category', 'Kategori Risiko Pekerjaan', PRIORITY),
      f('contract_no', 'Nomor Kontrak'),
      dt('contract_start', 'Mulai Kontrak'),
      dt('contract_end', 'Akhir Kontrak', { alert: 'expiry' }),
      f('smk3_certified', 'Bersertifikat SMK3', 'bool'),
      f('iso45001_certified', 'Bersertifikat ISO 45001', 'bool'),
      f('bpjs_compliance', 'Kepesertaan BPJS Ketenagakerjaan Lengkap', 'bool'),
      num('worker_count', 'Jumlah Pekerja'),
      num('csms_score', 'Skor CSMS Terakhir', { min: 0, max: 100 }),
      sel('csms_grade', 'Grade CSMS', ['A - Sangat Baik', 'B - Baik', 'C - Cukup', 'D - Kurang', 'E - Tidak Layak']),
      sel('blacklist_status', 'Status', ['Aktif', 'Peringatan', 'Suspensi', 'Blacklist']),
    ],
  }),
];
