/**
 * GROUP D - Health Management (ISO 45001:2018 - occupational health)
 */
import { m, f, req, sel, num, dt, txt, WF } from './defs.js';

export const group = { code: 'D', key: 'health', name: 'Health Management', nameId: 'Manajemen Kesehatan Kerja', icon: '🩺' };

export default [
  m({
    key: 'mcu',
    name: 'Medical Check Up',
    nameId: 'Pemeriksaan Kesehatan (MCU)',
    icon: '🧪',
    codePrefix: 'MCU',
    scope: 'any',
    workflow: WF.MONITORING,
    capa: true,
    standards: ['ISO 45001:2018 §7.2'],
    regulations: [
      'Permenakertrans No. 02/MEN/1980 tentang Pemeriksaan Kesehatan Tenaga Kerja',
      'PM Perhubungan tentang Kesehatan Awak Kapal (Medical Fitness Certificate)',
    ],
    fields: [
      req('employee', 'Pegawai', 'employee'),
      sel('mcu_type', 'Jenis MCU', ['Awal (Pra-Kerja)', 'Berkala', 'Khusus', 'Purna Kerja', 'Medical Fitness Awak Kapal'], { required: true }),
      dt('exam_date', 'Tanggal Pemeriksaan', { required: true }),
      f('provider', 'Penyelenggara / Klinik'),
      f('doctor', 'Dokter Pemeriksa'),
      sel('result', 'Hasil', ['Fit', 'Fit with Note', 'Fit with Restriction', 'Temporary Unfit', 'Unfit'], { required: true }),
      f('findings', 'Temuan Medis', 'multiselect', {
        options: ['Hipertensi', 'Diabetes Melitus', 'Dislipidemia', 'Obesitas', 'Gangguan Penglihatan', 'Gangguan Pendengaran', 'Gangguan Paru', 'Gangguan Jantung', 'Gangguan Muskuloskeletal', 'Buta Warna', 'Tidak Ada Temuan'],
      }),
      num('systolic', 'Tekanan Darah Sistolik'),
      num('diastolic', 'Tekanan Darah Diastolik'),
      num('bmi', 'IMT (BMI)', { step: 0.1 }),
      sel('audiometry', 'Audiometri', ['Normal', 'Gangguan Ringan', 'Gangguan Sedang', 'Gangguan Berat', 'Tidak Diperiksa'], { help: 'Wajib untuk pekerja area bising >85 dBA' }),
      sel('spirometry', 'Spirometri', ['Normal', 'Restriktif', 'Obstruktif', 'Campuran', 'Tidak Diperiksa']),
      txt('recommendation', 'Rekomendasi Dokter'),
      f('work_restriction', 'Pembatasan Kerja'),
      dt('next_mcu', 'MCU Berikutnya', { alert: 'expiry' }),
      f('follow_up_required', 'Perlu Tindak Lanjut', 'bool'),
    ],
  }),

  m({
    key: 'fatigue_management',
    name: 'Fatigue Management',
    nameId: 'Manajemen Kelelahan',
    icon: '😴',
    codePrefix: 'FTG',
    scope: 'any',
    workflow: WF.MONITORING,
    capa: true,
    standards: ['ISO 45001:2018 §8.1'],
    regulations: [
      'STCW Manila Amendments - Hours of Rest',
      'UU No. 13 Tahun 2003 tentang Ketenagakerjaan (Waktu Kerja & Istirahat)',
    ],
    fields: [
      req('employee', 'Pegawai / ABK', 'employee'),
      dt('assessment_date', 'Tanggal Penilaian', { required: true }),
      sel('role_type', 'Jenis Tugas', ['Nakhoda', 'Perwira Dek', 'Perwira Mesin', 'ABK', 'Operator MB/Gangway', 'Petugas Loket', 'Pengemudi', 'Petugas Keamanan', 'Petugas Bongkar Muat']),
      num('hours_worked_24h', 'Jam Kerja dalam 24 Jam', { required: true, step: 0.5 }),
      num('hours_rest_24h', 'Jam Istirahat dalam 24 Jam', { step: 0.5, help: 'Minimal 10 jam per STCW' }),
      num('hours_worked_7d', 'Jam Kerja dalam 7 Hari', { step: 0.5 }),
      num('hours_rest_7d', 'Jam Istirahat dalam 7 Hari', { step: 0.5, help: 'Minimal 77 jam per STCW' }),
      num('consecutive_days', 'Hari Kerja Berturut-turut'),
      sel('fatigue_score', 'Skor Kelelahan (Self-Assessment)', ['1 - Sangat Segar', '2 - Segar', '3 - Normal', '4 - Lelah', '5 - Sangat Lelah'], { required: true }),
      f('rest_compliance', 'Memenuhi Ketentuan Jam Istirahat', 'bool', { computed: 'restCompliance' }),
      sel('risk_flag', 'Status Risiko Kelelahan', ['Aman', 'Perlu Perhatian', 'Berisiko Tinggi'], { computed: 'fatigueRisk', readonly: true }),
      txt('mitigation', 'Tindakan Mitigasi'),
      f('fit_to_duty', 'Layak Bertugas', 'bool'),
    ],
  }),

  m({
    key: 'occupational_disease',
    name: 'Occupational Disease',
    nameId: 'Penyakit Akibat Kerja',
    icon: '🫁',
    codePrefix: 'PAK',
    scope: 'any',
    workflow: WF.REPORT,
    capa: true,
    standards: ['ISO 45001:2018 §10.2'],
    regulations: [
      'Perpres No. 7 Tahun 2019 tentang Penyakit Akibat Kerja',
      'PP No. 44 Tahun 2015 - Jaminan Kecelakaan Kerja BPJS',
    ],
    fields: [
      req('employee', 'Pegawai', 'employee'),
      dt('diagnosis_date', 'Tanggal Diagnosis', { required: true }),
      sel('disease_category', 'Kategori Penyakit', [
        'Gangguan Pendengaran Akibat Bising (NIHL)', 'Penyakit Saluran Pernapasan',
        'Penyakit Kulit Akibat Kerja', 'Gangguan Muskuloskeletal (MSD)', 'Keracunan Bahan Kimia',
        'Penyakit Akibat Getaran', 'Heat Stress', 'Gangguan Psikologis Akibat Kerja', 'Lainnya',
      ], { required: true }),
      f('diagnosis', 'Diagnosis Medis'),
      f('icd_code', 'Kode ICD-10'),
      f('doctor', 'Dokter / Fasilitas Kesehatan'),
      txt('exposure_history', 'Riwayat Pajanan'),
      f('causal_agent', 'Agen Penyebab'),
      num('exposure_years', 'Lama Pajanan (tahun)', { step: 0.1 }),
      num('lost_days', 'Hari Kerja Hilang'),
      f('reported_bpjs', 'Dilaporkan ke BPJS Ketenagakerjaan', 'bool'),
      f('reported_disnaker', 'Dilaporkan ke Disnaker', 'bool'),
      txt('control_measures', 'Pengendalian yang Diterapkan'),
      sel('outcome', 'Hasil Akhir', ['Sembuh', 'Sembuh dengan Gejala Sisa', 'Cacat Sebagian', 'Cacat Total', 'Dalam Perawatan', 'Meninggal']),
    ],
  }),

  m({
    key: 'clinic',
    name: 'Clinic Service',
    nameId: 'Layanan Klinik & P3K',
    icon: '🏥',
    codePrefix: 'CLN',
    scope: 'any',
    workflow: WF.MONITORING,
    standards: ['ISO 45001:2018 §8.2'],
    regulations: ['Permenakertrans No. 15 Tahun 2008 tentang P3K di Tempat Kerja'],
    fields: [
      dt('visit_date', 'Tanggal Kunjungan', { required: true }),
      req('patient_name', 'Nama Pasien'),
      sel('patient_type', 'Kategori Pasien', ['Pegawai', 'ABK', 'Kontraktor', 'Penumpang', 'Pengunjung'], { required: true }),
      sel('service_type', 'Jenis Layanan', ['Pemeriksaan Umum', 'P3K / Gawat Darurat', 'Pengobatan', 'Rujukan', 'Konsultasi', 'Vaksinasi', 'Pemeriksaan Tekanan Darah']),
      f('complaint', 'Keluhan'),
      f('diagnosis', 'Diagnosis'),
      txt('treatment', 'Tindakan / Pengobatan'),
      f('work_related', 'Terkait Pekerjaan', 'bool'),
      f('referred', 'Dirujuk', 'bool'),
      f('referral_facility', 'Fasilitas Rujukan'),
      f('officer', 'Petugas Kesehatan'),
      num('rest_days', 'Hari Istirahat Diberikan'),
    ],
  }),

  m({
    key: 'vaccination',
    name: 'Vaccination',
    nameId: 'Vaksinasi',
    icon: '💉',
    codePrefix: 'VAC',
    scope: 'any',
    workflow: WF.MONITORING,
    standards: ['ISO 45001:2018 §8.1'],
    regulations: ['International Health Regulations (IHR) - Sertifikat Vaksinasi Pelaut'],
    fields: [
      req('employee', 'Pegawai / ABK', 'employee'),
      sel('vaccine_type', 'Jenis Vaksin', ['COVID-19', 'Influenza', 'Hepatitis A', 'Hepatitis B', 'Tetanus (TT)', 'Tifoid', 'Yellow Fever', 'Meningitis', 'Rabies'], { required: true }),
      num('dose_number', 'Dosis Ke-'),
      dt('vaccination_date', 'Tanggal Vaksinasi', { required: true }),
      f('batch_number', 'Nomor Batch'),
      f('provider', 'Penyelenggara'),
      dt('next_dose', 'Jadwal Dosis Berikutnya', { alert: 'expiry' }),
      dt('valid_until', 'Berlaku Sampai', { alert: 'expiry' }),
      f('certificate_no', 'Nomor Sertifikat'),
      f('adverse_reaction', 'Terdapat Kejadian Ikutan (KIPI)', 'bool'),
      f('reaction_detail', 'Uraian KIPI'),
    ],
  }),

  m({
    key: 'health_campaign',
    name: 'Health Campaign',
    nameId: 'Program Promosi Kesehatan',
    icon: '📣',
    codePrefix: 'HPR',
    scope: 'any',
    workflow: WF.SIMPLE,
    standards: ['ISO 45001:2018 §7.4'],
    regulations: ['Permenkes No. 48 Tahun 2016 - K3 Perkantoran'],
    fields: [
      req('title', 'Judul Program'),
      sel('theme', 'Tema', ['Pola Hidup Sehat', 'Bahaya Merokok', 'Pencegahan HIV/AIDS', 'Kesehatan Mental', 'Ergonomi', 'Gizi Kerja', 'Pencegahan Penyakit Menular', 'Bulan K3 Nasional', 'Anti Narkoba (P4GN)']),
      dt('start_date', 'Tanggal Mulai', { required: true }),
      dt('end_date', 'Tanggal Selesai'),
      sel('format', 'Bentuk Kegiatan', ['Sosialisasi', 'Pemeriksaan Gratis', 'Senam Bersama', 'Poster & Banner', 'Webinar', 'Lomba', 'Konseling']),
      num('target_participants', 'Target Peserta'),
      num('actual_participants', 'Realisasi Peserta'),
      f('organizer', 'Penyelenggara'),
      num('budget', 'Anggaran (IDR)', { type: 'currency' }),
      txt('outcome', 'Hasil & Evaluasi'),
    ],
  }),
];
