/**
 * GROUP K - Maritime Safety
 *
 * The ferry/port specific core that separates an ASDP QHSE system from a
 * generic industrial one. Anchored on UU 17/2008, PP 20/2010, SOLAS, ISM Code
 * and BKI class requirements.
 */
import { m, f, req, sel, num, dt, txt, WF, CHECK_RESULT, riskFields } from './defs.js';

export const group = { code: 'K', key: 'maritime', name: 'Maritime Safety', icon: '⚓' };

const CHK = (name, label, help) => sel(name, label, CHECK_RESULT, { group: 'Checklist', ...(help ? { help } : {}) });

export default [
  m({
    key: 'vessel_safety_inspection',
    name: 'Vessel Safety Inspection',
    nameId: 'Inspeksi Keselamatan Kapal',
    icon: '🔍',
    codePrefix: 'VSI',
    scope: 'vessel',
    workflow: WF.INSPECTION,
    capa: true,
    standards: ['ISO 45001:2018', 'ISM Code §10'],
    regulations: ['UU No. 17 Tahun 2008 Pasal 117 (Kelaiklautan Kapal)', 'SOLAS', 'Peraturan BKI'],
    fields: [
      req('title', 'Judul Inspeksi'),
      dt('inspection_date', 'Tanggal Inspeksi', { required: true }),
      sel('inspection_type', 'Jenis Inspeksi', ['Inspeksi Internal Perusahaan', 'Inspeksi Nakhoda', 'Verifikasi ISM Internal', 'Persiapan Port State Control', 'Pasca Docking', 'Inspeksi Insidental'], { required: true }),
      f('inspector', 'Inspektor', 'user'),
      CHK('hull_condition', 'Kondisi Lambung & Struktur'),
      CHK('watertight_doors', 'Pintu Kedap Air'),
      CHK('navigation_equipment', 'Peralatan Navigasi (Radar, GPS, AIS, Kompas)'),
      CHK('communication_equipment', 'Peralatan Komunikasi (GMDSS/VHF)'),
      CHK('main_engine', 'Mesin Induk'),
      CHK('auxiliary_engine', 'Mesin Bantu / Genset'),
      CHK('steering_gear', 'Sistem Kemudi'),
      CHK('emergency_steering', 'Kemudi Darurat'),
      CHK('bilge_system', 'Sistem Bilga'),
      CHK('ballast_system', 'Sistem Ballast'),
      CHK('fire_detection', 'Sistem Deteksi Kebakaran'),
      CHK('fire_main', 'Fire Main & Pompa Kebakaran'),
      CHK('lsa_general', 'Alat Keselamatan Jiwa (LSA)'),
      CHK('emergency_lighting', 'Penerangan Darurat'),
      CHK('escape_routes', 'Jalur Evakuasi & Tanda'),
      CHK('accommodation', 'Akomodasi & Sanitasi ABK'),
      CHK('pollution_prevention', 'Peralatan Pencegahan Pencemaran (OWS, Sewage)'),
      CHK('mooring_equipment', 'Peralatan Tambat'),
      CHK('ramp_doors', 'Ramp Door / Bow Door / Stern Door'),
      CHK('vehicle_deck', 'Dek Kendaraan & Lashing'),
      CHK('documentation', 'Kelengkapan Sertifikat & Dokumen'),
      num('items_checked', 'Total Item Diperiksa'),
      num('deficiencies', 'Jumlah Ketidaksesuaian'),
      num('critical_deficiencies', 'Ketidaksesuaian Kritis'),
      txt('findings', 'Uraian Temuan'),
      sel('seaworthy', 'Kesimpulan Kelaiklautan', ['Laik Laut', 'Laik dengan Catatan', 'Tidak Laik Laut'], { required: true }),
      txt('recommendation', 'Rekomendasi'),
      dt('next_inspection', 'Inspeksi Berikutnya', { alert: 'expiry' }),
    ],
  }),

  m({
    key: 'ferry_safety_checklist',
    name: 'Ferry Pre-Departure Checklist',
    nameId: 'Checklist Keselamatan Sebelum Berlayar',
    icon: '☑',
    codePrefix: 'FSC',
    scope: 'vessel',
    workflow: WF.INSPECTION,
    capa: true,
    standards: ['ISM Code §7'],
    regulations: ['UU No. 17 Tahun 2008 - Kelaiklautan Kapal', 'SOP Syahbandar - Persetujuan Berlayar'],
    fields: [
      dt('voyage_date', 'Tanggal Pelayaran', { required: true }),
      f('departure_time', 'Jam Keberangkatan', 'time'),
      f('route', 'Lintasan', 'text', { required: true }),
      f('trip_number', 'Nomor Trip'),
      f('master_on_duty', 'Nakhoda Bertugas', 'user', { required: true }),
      CHK('ramp_door', 'Ramp Door - Tertutup & Terkunci Sempurna'),
      CHK('bow_door', 'Bow Door - Tertutup & Terkunci Sempurna'),
      CHK('stern_door', 'Stern Door - Tertutup & Terkunci Sempurna'),
      CHK('door_indicator', 'Indikator Pintu di Anjungan Berfungsi'),
      CHK('ballast', 'Kondisi Ballast & Trim'),
      CHK('stability', 'Perhitungan Stabilitas Terpenuhi'),
      CHK('navigation_light', 'Lampu Navigasi'),
      CHK('sound_signal', 'Isyarat Bunyi / Suling Kapal'),
      CHK('radar', 'Radar & ARPA'),
      CHK('gps_ais', 'GPS & AIS'),
      CHK('vhf_radio', 'Radio VHF / GMDSS'),
      CHK('echo_sounder', 'Echo Sounder'),
      CHK('main_engine_test', 'Uji Mesin Induk'),
      CHK('steering_test', 'Uji Kemudi'),
      CHK('generator', 'Generator / Genset'),
      CHK('emergency_generator', 'Generator Darurat'),
      CHK('bilge_pump', 'Pompa Bilga'),
      CHK('fire_pump', 'Pompa Kebakaran'),
      CHK('engine_room', 'Kondisi Ruang Mesin (Bebas Kebocoran & Ceceran)'),
      CHK('bridge_equipment', 'Peralatan Anjungan'),
      CHK('lifejacket', 'Life Jacket Sesuai Jumlah Penumpang'),
      CHK('liferaft', 'Life Raft / Sekoci'),
      CHK('fire_extinguisher', 'APAR Kapal'),
      CHK('vehicle_lashing', 'Pengikatan Kendaraan (Lashing)'),
      CHK('passenger_manifest', 'Manifest Penumpang Lengkap'),
      CHK('crew_complete', 'Kelengkapan & Kelaikan ABK'),
      CHK('weather_check', 'Pengecekan Cuaca & Gelombang'),
      CHK('sailing_clearance', 'Surat Persetujuan Berlayar (SPB)'),
      num('items_checked', 'Total Item'),
      num('items_not_ok', 'Item Tidak Sesuai'),
      txt('deficiency_notes', 'Catatan Ketidaksesuaian'),
      sel('departure_decision', 'Keputusan Keberangkatan', ['Layak Berangkat', 'Berangkat dengan Catatan', 'Ditunda', 'Dibatalkan'], { required: true }),
      txt('decision_reason', 'Alasan Keputusan'),
    ],
  }),

  m({
    key: 'sailing_clearance',
    name: 'Sailing Clearance (SPB)',
    nameId: 'Surat Persetujuan Berlayar',
    icon: '🛂',
    codePrefix: 'SPB',
    scope: 'vessel',
    workflow: WF.PERMIT,
    capa: true,
    regulations: [
      'UU No. 17 Tahun 2008 Pasal 219 (Surat Persetujuan Berlayar)',
      'PM Perhubungan No. 82 Tahun 2014 tentang Tata Cara Penerbitan SPB',
      'SOP Syahbandar',
    ],
    fields: [
      dt('clearance_date', 'Tanggal SPB', { required: true }),
      f('spb_number', 'Nomor SPB'),
      f('issuing_office', 'Kantor Penerbit (KSOP/Syahbandar)', 'text', { required: true }),
      f('departure_port', 'Pelabuhan Asal'),
      f('destination_port', 'Pelabuhan Tujuan'),
      f('departure_time', 'Jam Keberangkatan', 'time'),
      f('master_on_duty', 'Nakhoda', 'user'),
      num('crew_count', 'Jumlah ABK'),
      num('passenger_count', 'Jumlah Penumpang'),
      num('vehicle_count', 'Jumlah Kendaraan'),
      num('cargo_tonnage', 'Berat Muatan (ton)', { step: 0.01 }),
      f('checklist_ref', 'Nomor Checklist Pra-Berlayar'),
      f('documents_complete', 'Kelengkapan Dokumen Kapal Terverifikasi', 'bool'),
      f('crew_certificates_valid', 'Sertifikat ABK Berlaku', 'bool'),
      f('weather_approved', 'Kondisi Cuaca Memenuhi Syarat', 'bool'),
      sel('clearance_status', 'Status', ['Diterbitkan', 'Ditahan (Detained)', 'Ditunda', 'Dibatalkan'], { required: true }),
      txt('hold_reason', 'Alasan Penahanan / Penundaan'),
      dt('actual_departure', 'Realisasi Keberangkatan'),
      num('delay_minutes', 'Keterlambatan (menit)'),
    ],
  }),

  m({
    key: 'mooring_safety',
    name: 'Mooring Safety',
    nameId: 'Keselamatan Sandar & Tambat',
    icon: '🪢',
    codePrefix: 'MOR',
    scope: 'any',
    workflow: WF.INSPECTION,
    capa: true,
    standards: ['ISO 45001:2018', 'OCIMF Mooring Equipment Guidelines'],
    fields: [
      req('title', 'Judul Kegiatan / Inspeksi'),
      dt('activity_date', 'Tanggal', { required: true }),
      sel('activity_type', 'Jenis', ['Sandar (Berthing)', 'Lepas Sandar (Unberthing)', 'Inspeksi Peralatan Tambat', 'Latihan Tambat'], { required: true }),
      f('berth_number', 'Nomor Dermaga'),
      CHK('mooring_lines', 'Kondisi Tali Tambat'),
      CHK('winch', 'Winch / Mesin Tambat'),
      CHK('bollard', 'Bollard'),
      CHK('fender', 'Fender Dermaga'),
      CHK('rope_guard', 'Pelindung Tali & Rat Guard'),
      CHK('snap_back_zone', 'Penandaan Snap Back Zone'),
      CHK('crew_ppe', 'APD Petugas Tambat'),
      CHK('communication', 'Komunikasi Anjungan - Petugas Dermaga'),
      num('lines_used', 'Jumlah Tali Digunakan'),
      sel('wind_condition', 'Kondisi Angin', ['Tenang', 'Sedang', 'Kencang', 'Sangat Kencang']),
      sel('current_condition', 'Kondisi Arus', ['Tenang', 'Sedang', 'Kuat']),
      f('tug_assistance', 'Bantuan Kapal Tunda', 'bool'),
      num('mooring_duration', 'Durasi Kegiatan (menit)'),
      txt('findings', 'Temuan / Catatan'),
      sel('result', 'Hasil', ['Aman', 'Aman dengan Catatan', 'Terdapat Insiden'], { required: true }),
    ],
  }),

  m({
    key: 'ramp_door_inspection',
    name: 'Ramp Door Inspection',
    nameId: 'Inspeksi Ramp Door & Pintu Rampa',
    icon: '🚪',
    codePrefix: 'RDI',
    scope: 'vessel',
    workflow: WF.INSPECTION,
    capa: true,
    standards: ['ISO 55001:2014', 'SOLAS Ch. II-1 Reg. 17'],
    regulations: ['Peraturan BKI - Bagian Konstruksi Pintu Rampa'],
    fields: [
      req('title', 'Judul Inspeksi'),
      dt('inspection_date', 'Tanggal Inspeksi', { required: true }),
      sel('door_type', 'Jenis Pintu', ['Ramp Door Haluan', 'Ramp Door Buritan', 'Bow Door', 'Stern Door', 'Side Ramp', 'Movable Bridge Pelabuhan'], { required: true }),
      f('asset_ref', 'Aset', 'asset'),
      CHK('hydraulic_system', 'Sistem Hidrolik (Tekanan & Kebocoran)'),
      CHK('hydraulic_hoses', 'Selang & Sambungan Hidrolik'),
      CHK('wire_rope_chain', 'Wire Rope / Rantai Pengangkat'),
      CHK('hinge_bearing', 'Engsel & Bearing'),
      CHK('locking_device', 'Perangkat Pengunci (Cleat/Dog)'),
      CHK('securing_indicator', 'Indikator Pengunci di Anjungan'),
      CHK('rubber_seal', 'Karet Perapat (Weathertight Seal)'),
      CHK('structure_deformation', 'Deformasi / Retak Struktur'),
      CHK('corrosion', 'Korosi'),
      CHK('emergency_operation', 'Operasi Manual Darurat'),
      CHK('limit_switch', 'Limit Switch'),
      CHK('warning_alarm', 'Alarm Peringatan'),
      CHK('deck_surface', 'Permukaan & Anti-Slip Ramp'),
      num('cycle_count', 'Jumlah Siklus Operasi'),
      num('hydraulic_pressure', 'Tekanan Hidrolik (bar)', { step: 0.1 }),
      num('operation_time_sec', 'Waktu Operasi Buka/Tutup (detik)'),
      txt('findings', 'Temuan'),
      sel('result', 'Kesimpulan', ['Laik Operasi', 'Laik dengan Pembatasan', 'Tidak Laik Operasi'], { required: true }),
      f('load_test_done', 'Uji Beban Dilakukan', 'bool'),
      dt('next_inspection', 'Inspeksi Berikutnya', { alert: 'expiry' }),
    ],
  }),

  m({
    key: 'vehicle_loading_safety',
    name: 'Vehicle Loading Safety',
    nameId: 'Keselamatan Muat Kendaraan',
    icon: '🚛',
    codePrefix: 'VLS',
    scope: 'vessel',
    workflow: WF.INSPECTION,
    capa: true,
    standards: ['IMO Code of Safe Practice for Cargo Stowage and Securing (CSS Code)'],
    regulations: ['PM Perhubungan tentang Pengangkutan Kendaraan di Kapal Penyeberangan'],
    fields: [
      dt('loading_date', 'Tanggal Muat', { required: true }),
      f('trip_number', 'Nomor Trip'),
      f('route', 'Lintasan'),
      f('loading_officer', 'Petugas Pengatur Muatan', 'user'),
      num('deck_capacity_sup', 'Kapasitas Dek (SUP)'),
      num('total_vehicles', 'Total Kendaraan Dimuat', { required: true }),
      num('golongan_i_ii', 'Golongan I-II (Sepeda/Motor)'),
      num('golongan_iii_iv', 'Golongan III-IV (Mobil Penumpang)'),
      num('golongan_v_vi', 'Golongan V-VI (Bus/Truk Sedang)'),
      num('golongan_vii_ix', 'Golongan VII-IX (Truk Besar/Trailer)'),
      num('total_weight_ton', 'Total Berat Muatan (ton)', { step: 0.01 }),
      num('capacity_utilization', 'Utilisasi Kapasitas (%)', { computed: 'capacityUtilization', readonly: true }),
      f('overdimension_present', 'Terdapat Kendaraan Over Dimension', 'bool'),
      num('overdimension_count', 'Jumlah Kendaraan Over Dimension/Over Load'),
      f('dg_vehicle_present', 'Terdapat Kendaraan Pengangkut B3', 'bool'),
      num('dg_vehicle_count', 'Jumlah Kendaraan B3'),
      f('dg_manifest_verified', 'Manifest B3 Terverifikasi', 'bool'),
      CHK('weight_distribution', 'Distribusi Beban Merata'),
      CHK('vehicle_lashing', 'Pengikatan Kendaraan (Lashing/Chocking)'),
      CHK('handbrake_gear', 'Rem Tangan Aktif & Masuk Gigi'),
      CHK('engine_off', 'Mesin Kendaraan Dimatikan'),
      CHK('fuel_leak_check', 'Pemeriksaan Kebocoran BBM'),
      CHK('spacing', 'Jarak Antar Kendaraan'),
      CHK('access_route', 'Jalur Akses & Evakuasi Bebas'),
      CHK('dg_segregation', 'Segregasi Kendaraan B3'),
      CHK('passenger_evacuated_deck', 'Penumpang Tidak Berada di Dek Kendaraan'),
      CHK('deck_ventilation', 'Ventilasi Dek Kendaraan Aktif'),
      CHK('fire_detection_deck', 'Deteksi & Pemadam Kebakaran Dek Aktif'),
      txt('findings', 'Temuan'),
      sel('result', 'Kesimpulan', ['Aman untuk Berlayar', 'Perlu Perbaikan Sebelum Berlayar', 'Muatan Ditolak Sebagian'], { required: true }),
    ],
  }),

  m({
    key: 'passenger_safety',
    name: 'Passenger Safety',
    nameId: 'Keselamatan Penumpang',
    icon: '🧑‍🤝‍🧑',
    codePrefix: 'PSG',
    scope: 'vessel',
    workflow: WF.INSPECTION,
    capa: true,
    standards: ['SOLAS Ch. III'],
    regulations: [
      'UU No. 17 Tahun 2008 - Perlindungan Penumpang',
      'PM Perhubungan tentang Standar Pelayanan Minimum Angkutan Penyeberangan',
      'UU No. 8 Tahun 2016 tentang Penyandang Disabilitas',
    ],
    fields: [
      dt('voyage_date', 'Tanggal Pelayaran', { required: true }),
      f('trip_number', 'Nomor Trip'),
      num('manifest_count', 'Jumlah Penumpang dalam Manifest', { required: true }),
      num('actual_count', 'Jumlah Penumpang Aktual (Hasil Hitung)'),
      num('pax_capacity', 'Kapasitas Penumpang Kapal'),
      num('capacity_utilization', 'Utilisasi Kapasitas (%)', { computed: 'paxUtilization', readonly: true }),
      f('overcapacity', 'Melebihi Kapasitas', 'bool', { computed: 'overCapacity' }),
      num('children_count', 'Jumlah Anak-anak'),
      num('elderly_count', 'Jumlah Lansia'),
      num('disability_count', 'Jumlah Penumpang Disabilitas'),
      num('pregnant_count', 'Jumlah Ibu Hamil'),
      CHK('manifest_accuracy', 'Kesesuaian Manifest dengan Jumlah Aktual'),
      CHK('safety_briefing', 'Briefing Keselamatan Disampaikan'),
      CHK('lifejacket_availability', 'Ketersediaan Life Jacket (Dewasa & Anak)'),
      CHK('lifejacket_demo', 'Demonstrasi Penggunaan Life Jacket'),
      CHK('muster_station_marking', 'Penandaan Muster Station'),
      CHK('evacuation_route', 'Jalur Evakuasi Bebas Hambatan'),
      CHK('emergency_lighting', 'Penerangan Darurat'),
      CHK('pa_system', 'Sistem Pengumuman (PA System)'),
      CHK('disability_access', 'Aksesibilitas Penyandang Disabilitas'),
      CHK('seating_capacity', 'Kecukupan Tempat Duduk'),
      CHK('toilet_sanitation', 'Kebersihan Toilet & Sanitasi'),
      CHK('no_smoking', 'Penegakan Larangan Merokok'),
      CHK('passenger_deck_access', 'Penumpang Tidak di Dek Kendaraan'),
      CHK('first_aid_ready', 'Kotak P3K Tersedia & Lengkap'),
      num('briefing_duration', 'Durasi Briefing (menit)'),
      txt('findings', 'Temuan'),
      sel('result', 'Kesimpulan', ['Memenuhi Standar', 'Memenuhi dengan Catatan', 'Tidak Memenuhi'], { required: true }),
    ],
  }),

  m({
    key: 'cargo_securing',
    name: 'Cargo Securing Inspection',
    nameId: 'Inspeksi Pengikatan Muatan',
    icon: '📦',
    codePrefix: 'CSI',
    scope: 'vessel',
    workflow: WF.INSPECTION,
    capa: true,
    standards: ['IMO CSS Code', 'Cargo Securing Manual'],
    fields: [
      dt('inspection_date', 'Tanggal Inspeksi', { required: true }),
      f('trip_number', 'Nomor Trip'),
      sel('cargo_type', 'Jenis Muatan', ['Kendaraan', 'Muatan Umum', 'Kontainer', 'Curah', 'Alat Berat', 'Barang Berbahaya'], { required: true }),
      num('lashing_points_used', 'Jumlah Titik Lashing Digunakan'),
      CHK('lashing_equipment_condition', 'Kondisi Peralatan Lashing (Chain/Webbing)'),
      CHK('lashing_pattern', 'Pola Pengikatan Sesuai Manual'),
      CHK('chock_wedge', 'Ganjal Roda (Chock)'),
      CHK('deck_lashing_point', 'Kondisi Titik Lashing di Dek'),
      CHK('heavy_cargo_position', 'Posisi Muatan Berat (Rendah & Tengah)'),
      CHK('securing_manual_available', 'Cargo Securing Manual Tersedia'),
      CHK('crew_competency', 'Kompetensi Petugas Lashing'),
      f('weather_forecast_considered', 'Prakiraan Cuaca Dipertimbangkan', 'bool'),
      sel('sea_state_expected', 'Perkiraan Kondisi Laut', ['Tenang (0-1)', 'Sedang (2-3)', 'Berombak (4-5)', 'Kasar (6+)']),
      txt('findings', 'Temuan'),
      sel('result', 'Kesimpulan', ['Aman', 'Perlu Penambahan Lashing', 'Tidak Aman'], { required: true }),
    ],
  }),

  m({
    key: 'dangerous_goods',
    name: 'Dangerous Goods Management',
    nameId: 'Pengelolaan Barang Berbahaya (DG)',
    icon: '☢',
    codePrefix: 'DGM',
    scope: 'any',
    workflow: WF.PERMIT,
    capa: true,
    standards: ['IMDG Code'],
    regulations: [
      'PM Perhubungan No. 32 Tahun 2016 tentang Pengangkutan Barang Berbahaya di Perairan',
      'UU No. 17 Tahun 2008',
      'PP No. 22 Tahun 2021 (B3)',
    ],
    fields: [
      req('title', 'Uraian Muatan Berbahaya'),
      dt('shipment_date', 'Tanggal Pengangkutan', { required: true }),
      f('trip_number', 'Nomor Trip'),
      sel('imdg_class', 'Kelas IMDG', [
        'Kelas 1 - Bahan Peledak', 'Kelas 2.1 - Gas Mudah Menyala', 'Kelas 2.2 - Gas Tidak Mudah Menyala',
        'Kelas 2.3 - Gas Beracun', 'Kelas 3 - Cairan Mudah Menyala', 'Kelas 4.1 - Padatan Mudah Menyala',
        'Kelas 4.2 - Zat Mudah Terbakar Spontan', 'Kelas 4.3 - Zat Berbahaya Bila Basah',
        'Kelas 5.1 - Zat Pengoksidasi', 'Kelas 5.2 - Peroksida Organik', 'Kelas 6.1 - Zat Beracun',
        'Kelas 6.2 - Zat Infeksius', 'Kelas 7 - Radioaktif', 'Kelas 8 - Korosif', 'Kelas 9 - Lain-lain',
      ], { required: true }),
      f('un_number', 'Nomor UN'),
      f('proper_shipping_name', 'Proper Shipping Name'),
      sel('packing_group', 'Packing Group', ['I - Bahaya Tinggi', 'II - Bahaya Sedang', 'III - Bahaya Rendah']),
      num('quantity', 'Jumlah', { step: 0.01 }),
      f('quantity_unit', 'Satuan'),
      f('shipper', 'Pengirim'),
      f('vehicle_plate', 'Nomor Kendaraan Pengangkut'),
      f('dg_declaration', 'Dangerous Goods Declaration Diterima', 'bool', { required: true }),
      f('msds_available', 'MSDS/SDS Tersedia', 'bool'),
      f('placard_affixed', 'Plakat & Label Terpasang', 'bool'),
      f('packaging_certified', 'Kemasan Bersertifikat UN', 'bool'),
      f('segregation_applied', 'Segregasi Sesuai IMDG Diterapkan', 'bool'),
      f('stowage_position', 'Posisi Penempatan di Kapal'),
      f('fire_equipment_ready', 'Peralatan Pemadam Khusus Siap', 'bool'),
      f('crew_briefed', 'ABK Diberi Pengarahan', 'bool'),
      f('emergency_procedure', 'Prosedur Darurat (EmS) Tersedia', 'bool'),
      f('ksop_notified', 'Diberitahukan ke Syahbandar/KSOP', 'bool'),
      sel('approval_status', 'Status Persetujuan', ['Disetujui Diangkut', 'Disetujui dengan Syarat', 'Ditolak'], { required: true }),
      txt('rejection_reason', 'Alasan Penolakan / Syarat'),
      ...riskFields(),
    ],
  }),

  m({
    key: 'lsa_inspection',
    name: 'LSA Inspection',
    nameId: 'Inspeksi Alat Keselamatan Jiwa (LSA)',
    icon: '🛟',
    codePrefix: 'LSA',
    scope: 'vessel',
    workflow: WF.INSPECTION,
    capa: true,
    standards: ['SOLAS Ch. III', 'LSA Code'],
    regulations: ['Peraturan BKI', 'PM Perhubungan tentang Perlengkapan Keselamatan Kapal'],
    fields: [
      dt('inspection_date', 'Tanggal Inspeksi', { required: true }),
      sel('inspection_type', 'Jenis', ['Mingguan', 'Bulanan', 'Triwulanan', 'Tahunan', 'Servis Bersertifikat'], { required: true }),
      f('inspector', 'Inspektor', 'user'),
      num('lifejacket_required', 'Life Jacket - Jumlah Dipersyaratkan'),
      num('lifejacket_available', 'Life Jacket - Jumlah Tersedia'),
      num('lifejacket_defect', 'Life Jacket - Rusak/Tidak Layak'),
      num('lifejacket_child', 'Life Jacket Anak - Tersedia'),
      CHK('lifejacket_condition', 'Kondisi Life Jacket (Tali, Peluit, Lampu, Reflektor)'),
      num('liferaft_count', 'Jumlah Life Raft'),
      num('liferaft_capacity', 'Total Kapasitas Life Raft (orang)'),
      dt('liferaft_service_due', 'Jatuh Tempo Servis Life Raft', { alert: 'expiry' }),
      CHK('liferaft_condition', 'Kondisi Life Raft & HRU'),
      dt('hru_expiry', 'Masa Berlaku HRU', { alert: 'expiry' }),
      num('lifebuoy_count', 'Jumlah Lifebuoy'),
      CHK('lifebuoy_condition', 'Kondisi Lifebuoy (Tali, Lampu, Smoke Signal)'),
      num('lifeboat_count', 'Jumlah Sekoci'),
      CHK('lifeboat_condition', 'Kondisi Sekoci & Davit'),
      dt('lifeboat_load_test', 'Uji Beban Sekoci Terakhir'),
      CHK('immersion_suit', 'Immersion Suit / Thermal Protective Aid'),
      CHK('pyrotechnics', 'Alat Isyarat Bahaya (Pyrotechnics)'),
      dt('pyrotechnics_expiry', 'Masa Berlaku Pyrotechnics', { alert: 'expiry' }),
      CHK('epirb', 'EPIRB'),
      dt('epirb_battery_expiry', 'Masa Berlaku Baterai EPIRB', { alert: 'expiry' }),
      CHK('sart', 'SART'),
      CHK('embarkation_ladder', 'Tangga Embarkasi'),
      CHK('muster_list', 'Muster List / Sijil Kebakaran Terpasang'),
      CHK('signage', 'Rambu & Petunjuk LSA'),
      num('deficiencies', 'Jumlah Ketidaksesuaian'),
      txt('findings', 'Temuan'),
      sel('result', 'Kesimpulan', ['Lengkap & Layak', 'Layak dengan Catatan', 'Tidak Memenuhi Persyaratan'], { required: true }),
      dt('next_inspection', 'Inspeksi Berikutnya', { alert: 'expiry' }),
    ],
  }),

  m({
    key: 'ffa_inspection',
    name: 'FFA Inspection',
    nameId: 'Inspeksi Alat Pemadam Kebakaran (FFA)',
    icon: '🧯',
    codePrefix: 'FFA',
    scope: 'any',
    workflow: WF.INSPECTION,
    capa: true,
    standards: ['SOLAS Ch. II-2', 'FSS Code'],
    regulations: [
      'Permenaker No. 04/MEN/1980 tentang APAR',
      'Kepmenaker No. 186 Tahun 1999 tentang Penanggulangan Kebakaran',
    ],
    fields: [
      dt('inspection_date', 'Tanggal Inspeksi', { required: true }),
      sel('location_type', 'Lokasi', ['Kapal', 'Terminal Penumpang', 'Dermaga', 'Kantor', 'Bengkel', 'Gudang', 'TPS Limbah B3'], { required: true }),
      f('inspector', 'Inspektor', 'user'),
      num('apar_total', 'Jumlah APAR'),
      num('apar_ok', 'APAR Kondisi Baik'),
      num('apar_expired', 'APAR Kedaluwarsa'),
      num('apar_pressure_low', 'APAR Tekanan Kurang'),
      CHK('apar_condition', 'Kondisi APAR (Segel, Tekanan, Selang, Label)'),
      CHK('apar_accessibility', 'Aksesibilitas & Penandaan APAR'),
      num('hydrant_count', 'Jumlah Hydrant / Fire Station'),
      CHK('hydrant_condition', 'Kondisi Hydrant, Selang & Nozzle'),
      CHK('fire_pump', 'Pompa Kebakaran Utama'),
      CHK('emergency_fire_pump', 'Pompa Kebakaran Darurat'),
      num('fire_pump_pressure', 'Tekanan Pompa (bar)', { step: 0.1 }),
      CHK('fixed_system', 'Sistem Pemadam Tetap (CO2/Foam/Sprinkler)'),
      CHK('fire_detection', 'Sistem Deteksi & Alarm Kebakaran'),
      CHK('fire_damper', 'Fire Damper & Ventilasi'),
      CHK('fireman_outfit', 'Fireman Outfit & SCBA'),
      dt('scba_test_due', 'Jatuh Tempo Uji SCBA', { alert: 'expiry' }),
      CHK('emergency_escape_bcba', 'EEBD'),
      CHK('fire_plan', 'Fire Control Plan Terpasang'),
      CHK('escape_route', 'Jalur Evakuasi & Rambu'),
      CHK('assembly_point', 'Titik Kumpul'),
      num('deficiencies', 'Jumlah Ketidaksesuaian'),
      txt('findings', 'Temuan'),
      sel('result', 'Kesimpulan', ['Siap Digunakan', 'Siap dengan Catatan', 'Tidak Siap'], { required: true }),
      dt('next_inspection', 'Inspeksi Berikutnya', { alert: 'expiry' }),
    ],
  }),

  m({
    key: 'stability_monitoring',
    name: 'Stability Monitoring',
    nameId: 'Pemantauan Stabilitas Kapal',
    icon: '⚖',
    codePrefix: 'STB',
    scope: 'vessel',
    workflow: WF.MONITORING,
    capa: true,
    standards: ['IMO Intact Stability Code (IS Code 2008)', 'SOLAS Ch. II-1'],
    regulations: ['Peraturan BKI - Stabilitas Kapal'],
    fields: [
      dt('voyage_date', 'Tanggal', { required: true }),
      f('trip_number', 'Nomor Trip'),
      sel('condition', 'Kondisi Muat', ['Muatan Penuh', 'Muatan Sebagian', 'Ballast', 'Kosong'], { required: true }),
      num('displacement', 'Displasemen (ton)', { step: 0.01 }),
      num('draft_fore', 'Sarat Depan (m)', { step: 0.01 }),
      num('draft_aft', 'Sarat Belakang (m)', { step: 0.01 }),
      num('draft_mean', 'Sarat Rata-rata (m)', { computed: 'meanDraft', readonly: true }),
      num('trim', 'Trim (m)', { computed: 'trimValue', readonly: true }),
      num('heel_angle', 'Sudut Kemiringan (derajat)', { step: 0.1 }),
      num('gm_value', 'GM Aktual (m)', { step: 0.001, required: true }),
      num('gm_minimum', 'GM Minimum Dipersyaratkan (m)', { step: 0.001, default: 0.15 }),
      f('gm_compliant', 'GM Memenuhi Persyaratan', 'bool', { computed: 'gmCompliant' }),
      num('free_surface_effect', 'Koreksi Free Surface (m)', { step: 0.001 }),
      num('cargo_weight', 'Berat Muatan (ton)', { step: 0.01 }),
      num('ballast_weight', 'Berat Ballast (ton)', { step: 0.01 }),
      num('fuel_weight', 'Berat Bahan Bakar (ton)', { step: 0.01 }),
      num('freeboard', 'Lambung Timbul (m)', { step: 0.01 }),
      f('loadline_compliant', 'Memenuhi Garis Muat', 'bool'),
      f('stability_booklet_used', 'Menggunakan Stability Booklet', 'bool'),
      f('calculated_by', 'Dihitung Oleh', 'user'),
      f('approved_by_master', 'Disetujui Nakhoda', 'bool'),
      sel('result', 'Kesimpulan', ['Stabilitas Memenuhi', 'Perlu Penyesuaian Muatan', 'Tidak Memenuhi - Ditunda'], { required: true }),
      txt('notes', 'Catatan'),
    ],
  }),

  m({
    key: 'weather_monitoring',
    name: 'Weather Monitoring',
    nameId: 'Pemantauan Cuaca & Gelombang',
    icon: '🌦',
    codePrefix: 'WTH',
    scope: 'any',
    workflow: WF.MONITORING,
    capa: true,
    standards: ['ISO 22301:2019'],
    regulations: [
      'Peringatan Dini BMKG',
      'PM Perhubungan tentang Pembatasan Operasi Kapal pada Cuaca Buruk',
    ],
    fields: [
      dt('observation_date', 'Tanggal', { required: true }),
      f('observation_time', 'Waktu', 'time'),
      f('area', 'Perairan / Lintasan', 'text', { required: true }),
      f('source', 'Sumber Informasi', 'select', { options: ['BMKG', 'Stasiun Meteorologi Maritim', 'Observasi Kapal', 'Observasi Pelabuhan', 'Aplikasi Cuaca'] }),
      num('wind_speed', 'Kecepatan Angin (knot)', { step: 0.1 }),
      f('wind_direction', 'Arah Angin'),
      num('wave_height', 'Tinggi Gelombang (m)', { required: true, step: 0.1 }),
      num('visibility_km', 'Jarak Pandang (km)', { step: 0.1 }),
      num('current_speed', 'Kecepatan Arus (knot)', { step: 0.1 }),
      num('rainfall', 'Curah Hujan (mm)', { step: 0.1 }),
      sel('weather_condition', 'Kondisi Cuaca', ['Cerah', 'Berawan', 'Hujan Ringan', 'Hujan Lebat', 'Badai', 'Kabut']),
      sel('sea_state', 'Kondisi Laut', ['Tenang (0-0.5m)', 'Sedang (0.5-1.25m)', 'Berombak (1.25-2.5m)', 'Kasar (2.5-4m)', 'Sangat Kasar (>4m)'], { required: true }),
      f('bmkg_warning', 'Terdapat Peringatan Dini BMKG', 'bool'),
      txt('warning_detail', 'Isi Peringatan'),
      sel('operational_decision', 'Keputusan Operasional', ['Operasi Normal', 'Operasi dengan Kewaspadaan', 'Penundaan Keberangkatan', 'Penutupan Sementara Lintasan', 'Penutupan Pelabuhan'], { required: true }),
      f('decision_by', 'Diputuskan Oleh', 'user'),
      num('trips_cancelled', 'Jumlah Trip Dibatalkan'),
      num('delay_hours', 'Total Penundaan (jam)', { step: 0.1 }),
      txt('notes', 'Catatan'),
    ],
  }),

  m({
    key: 'marine_incident',
    name: 'Marine Incident',
    nameId: 'Kecelakaan & Insiden Pelayaran',
    icon: '🌊',
    codePrefix: 'MIN',
    scope: 'any',
    workflow: WF.REPORT,
    capa: true,
    standards: ['ISM Code §9', 'IMO Casualty Investigation Code'],
    regulations: [
      'UU No. 17 Tahun 2008 Pasal 245-256 (Kecelakaan Kapal)',
      'PM Perhubungan tentang Pelaporan Kecelakaan Kapal',
      'Investigasi KNKT',
    ],
    fields: [
      req('title', 'Judul Kejadian'),
      dt('incident_date', 'Tanggal Kejadian', { required: true }),
      f('incident_time', 'Waktu Kejadian', 'time'),
      sel('incident_type', 'Klasifikasi Kejadian', [
        'Kapal Kandas (Grounding)', 'Tubrukan Kapal (Collision)', 'Tubrukan dengan Dermaga (Allision)',
        'Kebakaran Kapal', 'Ledakan', 'Kapal Tenggelam / Terbalik', 'Orang Jatuh ke Laut (Man Overboard)',
        'Tumpahan Minyak dari Kapal', 'Kerusakan Mesin (Blackout/Breakdown)', 'Kegagalan Kemudi',
        'Kegagalan Sandar', 'Kegagalan Ramp Door', 'Cuaca Ekstrem', 'Penutupan Pelabuhan',
        'Kapal Hanyut (Drifting)', 'Kandas Muatan Bergeser', 'Insiden Keamanan (ISPS)', 'Lainnya',
      ], { required: true }),
      sel('severity', 'Tingkat Keparahan', ['Very Serious Casualty', 'Serious Casualty', 'Less Serious Casualty', 'Marine Incident'], { required: true }),
      f('position_lat', 'Posisi - Lintang'),
      f('position_lon', 'Posisi - Bujur'),
      f('location_desc', 'Deskripsi Lokasi'),
      sel('voyage_phase', 'Fase Pelayaran', ['Sandar', 'Lepas Sandar', 'Manuver di Kolam Pelabuhan', 'Alur Pelayaran', 'Laut Terbuka', 'Berlabuh Jangkar', 'Bongkar Muat']),
      txt('description', 'Kronologi Kejadian', { required: true }),
      num('fatality_count', 'Korban Meninggal'),
      num('injured_count', 'Korban Luka'),
      num('missing_count', 'Korban Hilang'),
      num('passengers_onboard', 'Penumpang di Atas Kapal'),
      num('crew_onboard', 'ABK di Atas Kapal'),
      num('vehicles_onboard', 'Kendaraan di Atas Kapal'),
      f('pollution_occurred', 'Terjadi Pencemaran', 'bool'),
      num('pollution_volume', 'Volume Pencemaran (liter)', { step: 0.1 }),
      num('property_damage', 'Kerugian Material (IDR)', { type: 'currency' }),
      num('service_disruption_hours', 'Gangguan Layanan (jam)', { step: 0.1 }),
      sel('weather_at_time', 'Kondisi Cuaca Saat Kejadian', ['Baik', 'Sedang', 'Buruk', 'Sangat Buruk']),
      num('wave_height', 'Tinggi Gelombang (m)', { step: 0.1 }),
      f('sar_involved', 'Melibatkan Operasi SAR', 'bool'),
      f('external_agencies', 'Instansi yang Terlibat', 'multiselect', {
        options: ['KSOP / Syahbandar', 'Basarnas', 'KNKT', 'Polairud', 'TNI AL', 'BPBD', 'KLHK', 'Asuransi', 'BKI'],
      }),
      f('reported_ksop', 'Dilaporkan ke KSOP/Syahbandar', 'bool'),
      f('reported_knkt', 'Dilaporkan ke KNKT', 'bool'),
      dt('report_date', 'Tanggal Pelaporan'),
      txt('immediate_action', 'Tindakan Segera'),
      txt('root_cause', 'Analisis Penyebab'),
      sel('human_factor', 'Faktor Manusia Terlibat', ['Ya - Kesalahan Navigasi', 'Ya - Kelelahan', 'Ya - Kurang Kompetensi', 'Ya - Pelanggaran Prosedur', 'Ya - Komunikasi', 'Tidak']),
      sel('technical_factor', 'Faktor Teknis', ['Kegagalan Mesin', 'Kegagalan Kemudi', 'Kegagalan Struktur', 'Kegagalan Peralatan Navigasi', 'Pemeliharaan Tidak Memadai', 'Tidak Ada']),
      txt('lesson_learned', 'Pembelajaran'),
      ...riskFields('potential_'),
    ],
  }),

  m({
    key: 'port_inspection',
    name: 'Port Facility Inspection',
    nameId: 'Inspeksi Fasilitas Pelabuhan',
    icon: '🏗',
    codePrefix: 'PFI',
    scope: 'port',
    workflow: WF.INSPECTION,
    capa: true,
    standards: ['ISO 55001:2014', 'ISPS Code Part A'],
    regulations: [
      'PP No. 61 Tahun 2009 tentang Kepelabuhanan',
      'PM Perhubungan tentang Standar Fasilitas Pelabuhan Penyeberangan',
    ],
    fields: [
      req('title', 'Judul Inspeksi'),
      dt('inspection_date', 'Tanggal Inspeksi', { required: true }),
      sel('inspection_scope', 'Lingkup Inspeksi', ['Fasilitas Sisi Laut', 'Fasilitas Sisi Darat', 'Terminal Penumpang', 'Keamanan (ISPS)', 'Menyeluruh'], { required: true }),
      f('inspector', 'Inspektor', 'user'),
      CHK('dermaga_structure', 'Struktur Dermaga (Beton/Tiang Pancang)'),
      CHK('fender_condition', 'Kondisi Fender'),
      CHK('bollard_condition', 'Kondisi Bollard'),
      CHK('movable_bridge', 'Movable Bridge / Ponton'),
      CHK('mb_hydraulic', 'Sistem Hidrolik Movable Bridge'),
      CHK('gangway', 'Gangway Penumpang'),
      CHK('trestle', 'Trestle / Causeway'),
      CHK('apron_pavement', 'Perkerasan Apron & Area Manuver'),
      CHK('parking_area', 'Area Parkir & Antrian Kendaraan'),
      CHK('terminal_building', 'Gedung Terminal Penumpang'),
      CHK('waiting_room', 'Ruang Tunggu & Fasilitas Penumpang'),
      CHK('toilet_facility', 'Toilet & Fasilitas Sanitasi'),
      CHK('disability_facility', 'Fasilitas Penyandang Disabilitas'),
      CHK('lighting_dermaga', 'Pencahayaan Dermaga'),
      CHK('lighting_terminal', 'Pencahayaan Terminal & Area Parkir'),
      CHK('signage_marking', 'Rambu & Marka'),
      CHK('sterile_area', 'Pengendalian Area Steril'),
      CHK('access_control', 'Kontrol Akses & Pagar Perimeter'),
      CHK('cctv', 'CCTV & Sistem Pemantauan'),
      CHK('evacuation_route', 'Jalur & Rambu Evakuasi'),
      CHK('assembly_point', 'Titik Kumpul'),
      CHK('apar_hydrant', 'APAR & Hydrant Pelabuhan'),
      CHK('life_saving_shore', 'Peralatan Penyelamatan di Dermaga (Lifebuoy/Tali)'),
      CHK('drainage', 'Sistem Drainase'),
      CHK('waste_facility', 'Fasilitas Pengelolaan Sampah & TPS B3'),
      CHK('ipal', 'IPAL / Pengolahan Air Limbah'),
      CHK('navigation_aid', 'Sarana Bantu Navigasi Pelayaran (SBNP)'),
      CHK('electrical_installation', 'Instalasi Listrik & Panel'),
      CHK('water_supply', 'Suplai Air Bersih'),
      num('items_checked', 'Total Item Diperiksa'),
      num('findings_count', 'Jumlah Temuan'),
      num('critical_findings', 'Temuan Kritis'),
      num('conformity_rate', 'Tingkat Kesesuaian (%)', { computed: 'conformityRate', readonly: true }),
      txt('findings', 'Uraian Temuan'),
      txt('recommendation', 'Rekomendasi'),
      dt('next_inspection', 'Inspeksi Berikutnya', { alert: 'expiry' }),
    ],
  }),
];
