/**
 * GROUP M - Port Safety Management (ASDP specific)
 *
 * Day-to-day safety of the ferry terminal itself: sterile area control, crowd
 * and queue management during peak season (mudik), and ISPS security.
 */
import { m, f, req, sel, num, dt, txt, WF, CHECK_RESULT, riskFields } from './defs.js';

export const group = { code: 'M', key: 'portsafety', name: 'Port Safety (ASDP)', icon: '🏖' };

const CHK = (name, label) => sel(name, label, CHECK_RESULT, { group: 'Checklist' });

export default [
  m({
    key: 'port_safety_patrol',
    name: 'Port Safety Patrol',
    nameId: 'Patroli Keselamatan Pelabuhan',
    icon: '🚶',
    codePrefix: 'PSP',
    scope: 'port',
    workflow: WF.INSPECTION,
    capa: true,
    standards: ['ISO 45001:2018 §9.1'],
    regulations: ['PP No. 61 Tahun 2009', 'PP No. 50 Tahun 2012 (SMK3)'],
    fields: [
      req('title', 'Judul Patroli'),
      dt('patrol_date', 'Tanggal Patroli', { required: true }),
      sel('shift', 'Shift', ['Pagi', 'Siang', 'Malam'], { required: true }),
      f('patrol_officer', 'Petugas Patroli', 'user'),
      CHK('sterile_area_control', 'Pengendalian Area Steril'),
      CHK('unauthorized_person', 'Tidak Ada Orang Tanpa Izin di Area Terbatas'),
      CHK('evacuation_route_clear', 'Jalur Evakuasi Bebas Hambatan'),
      CHK('apar_available', 'APAR Tersedia & Layak'),
      CHK('lighting_adequate', 'Pencahayaan Dermaga Memadai'),
      CHK('fender_bollard', 'Kondisi Fender & Bollard'),
      CHK('mb_gangway', 'Kondisi Movable Bridge & Gangway'),
      CHK('housekeeping', 'Kebersihan & Kerapian (5R)'),
      CHK('signage', 'Rambu Keselamatan Terpasang & Terbaca'),
      CHK('barrier_railing', 'Pagar Pengaman & Railing Dermaga'),
      CHK('spill_free', 'Bebas Ceceran Oli / Tumpahan'),
      CHK('waste_handling', 'Penanganan Sampah'),
      CHK('vehicle_discipline', 'Kedisiplinan Lalu Lintas Kendaraan'),
      CHK('ppe_compliance', 'Kepatuhan Penggunaan APD Petugas'),
      CHK('lifebuoy_shore', 'Lifebuoy di Sisi Dermaga'),
      num('findings_count', 'Jumlah Temuan'),
      num('items_checked', 'Total Item Diperiksa'),
      num('items_conform', 'Item Sesuai'),
      num('conformity_rate', 'Tingkat Kesesuaian (%)', { computed: 'conformityRate', readonly: true }),
      txt('findings', 'Uraian Temuan'),
      txt('immediate_action', 'Tindakan Segera'),
    ],
  }),

  m({
    key: 'crowd_management',
    name: 'Crowd & Peak Season Management',
    nameId: 'Manajemen Kepadatan & Angkutan Puncak',
    icon: '👥',
    codePrefix: 'CRD',
    scope: 'port',
    workflow: WF.MONITORING,
    capa: true,
    standards: ['ISO 45001:2018', 'ISO 22301:2019'],
    regulations: ['SOP Angkutan Lebaran / Nataru Kementerian Perhubungan'],
    fields: [
      dt('record_date', 'Tanggal', { required: true }),
      sel('period_type', 'Periode', ['Hari Biasa', 'Akhir Pekan', 'Angkutan Lebaran', 'Angkutan Natal & Tahun Baru', 'Libur Panjang', 'Kondisi Khusus'], { required: true }),
      f('peak_hour', 'Jam Puncak', 'time'),
      num('passenger_count', 'Jumlah Penumpang', { required: true }),
      num('vehicle_count', 'Jumlah Kendaraan'),
      num('terminal_capacity', 'Kapasitas Ruang Tunggu (orang)'),
      num('occupancy_rate', 'Tingkat Okupansi Terminal (%)', { computed: 'occupancyRate', readonly: true }),
      num('queue_length_km', 'Panjang Antrian Kendaraan (km)', { step: 0.1 }),
      num('waiting_time_minutes', 'Rata-rata Waktu Tunggu (menit)'),
      num('buffer_zone_used', 'Kantong Parkir Digunakan (unit)'),
      sel('congestion_level', 'Tingkat Kepadatan', ['Normal', 'Padat', 'Sangat Padat', 'Kritis'], { required: true }),
      f('delay_system_active', 'Sistem Delay System Diaktifkan', 'bool'),
      f('additional_trip', 'Penambahan Trip', 'bool'),
      num('additional_vessel', 'Penambahan Kapal (unit)'),
      f('joint_command_post', 'Posko Terpadu Aktif', 'bool'),
      f('agencies_involved', 'Instansi Terlibat', 'multiselect', {
        options: ['Kepolisian', 'Dinas Perhubungan', 'TNI', 'Basarnas', 'Dinas Kesehatan', 'BPBD', 'Jasa Marga', 'Satpol PP'],
      }),
      num('medical_cases', 'Jumlah Kasus Kesehatan Penumpang'),
      num('incidents', 'Jumlah Insiden'),
      txt('mitigation', 'Tindakan Pengendalian Kepadatan'),
      txt('notes', 'Catatan'),
    ],
  }),

  m({
    key: 'port_security',
    name: 'Port Security (ISPS)',
    nameId: 'Keamanan Fasilitas Pelabuhan (ISPS)',
    icon: '🛡',
    codePrefix: 'ISPS',
    scope: 'port',
    workflow: WF.REPORT,
    capa: true,
    standards: ['ISPS Code Part A & B', 'ISO 28000', 'ISO 27001:2022'],
    regulations: [
      'PM Perhubungan No. 134 Tahun 2016 tentang Manajemen Keamanan Kapal dan Fasilitas Pelabuhan',
      'SOLAS Ch. XI-2',
    ],
    fields: [
      req('title', 'Judul Kegiatan / Kejadian'),
      sel('record_type', 'Jenis Rekaman', ['Kejadian Keamanan', 'Latihan Keamanan (Drill)', 'Audit Keamanan Internal', 'Perubahan Security Level', 'Pemeriksaan Rutin'], { required: true }),
      dt('event_date', 'Tanggal', { required: true }),
      sel('security_level', 'Security Level', ['Level 1 - Normal', 'Level 2 - Ditingkatkan', 'Level 3 - Khusus'], { required: true }),
      f('pfso_name', 'Port Facility Security Officer (PFSO)', 'user'),
      sel('incident_category', 'Kategori Kejadian', [
        'Akses Tidak Sah', 'Penumpang Gelap (Stowaway)', 'Barang Mencurigakan', 'Ancaman Bom',
        'Pencurian', 'Vandalisme', 'Perkelahian', 'Penyelundupan', 'Gangguan Sistem Keamanan',
        'Pelanggaran Prosedur', 'Tidak Ada Kejadian',
      ]),
      txt('description', 'Uraian'),
      f('screening_conducted', 'Pemeriksaan Dilakukan', 'bool'),
      num('persons_screened', 'Jumlah Orang Diperiksa'),
      num('vehicles_screened', 'Jumlah Kendaraan Diperiksa'),
      num('items_confiscated', 'Barang Disita'),
      f('cctv_functional', 'CCTV Berfungsi Penuh', 'bool'),
      f('access_control_functional', 'Kontrol Akses Berfungsi', 'bool'),
      f('perimeter_intact', 'Pagar Perimeter Utuh', 'bool'),
      f('police_involved', 'Melibatkan Aparat Keamanan', 'bool'),
      f('reported_ksop', 'Dilaporkan ke KSOP', 'bool'),
      txt('action_taken', 'Tindakan yang Diambil'),
      txt('recommendation', 'Rekomendasi'),
      ...riskFields('potential_'),
    ],
  }),

  m({
    key: 'port_environment_monitoring',
    name: 'Port Environmental Housekeeping',
    nameId: 'Kebersihan & Lingkungan Pelabuhan',
    icon: '🧹',
    codePrefix: 'PEH',
    scope: 'port',
    workflow: WF.MONITORING,
    capa: true,
    standards: ['ISO 14001:2015'],
    regulations: ['UU No. 18 Tahun 2008 tentang Pengelolaan Sampah', 'PP No. 22 Tahun 2021'],
    fields: [
      dt('record_date', 'Tanggal', { required: true }),
      sel('shift', 'Shift', ['Pagi', 'Siang', 'Malam']),
      CHK('terminal_cleanliness', 'Kebersihan Terminal Penumpang'),
      CHK('toilet_cleanliness', 'Kebersihan Toilet'),
      CHK('dermaga_cleanliness', 'Kebersihan Dermaga'),
      CHK('parking_cleanliness', 'Kebersihan Area Parkir'),
      CHK('waste_bin_condition', 'Kondisi & Kecukupan Tempat Sampah'),
      CHK('waste_segregation', 'Pemilahan Sampah'),
      CHK('tps_condition', 'Kondisi TPS Sampah'),
      CHK('tps_b3_condition', 'Kondisi TPS Limbah B3'),
      CHK('drainage_condition', 'Kondisi Saluran Drainase'),
      CHK('sea_surface', 'Kebersihan Permukaan Perairan Kolam'),
      CHK('oil_sheen', 'Bebas Lapisan Minyak di Perairan'),
      CHK('ipal_operation', 'Operasi IPAL'),
      CHK('green_area', 'Perawatan Area Hijau'),
      CHK('noise_level', 'Tingkat Kebisingan Wajar'),
      CHK('air_quality', 'Kualitas Udara / Bebas Asap Pekat'),
      num('waste_collected_kg', 'Sampah Terkumpul (kg)', { step: 0.1 }),
      num('findings_count', 'Jumlah Temuan'),
      txt('findings', 'Temuan'),
      txt('action_taken', 'Tindakan'),
    ],
  }),
];
