/**
 * GROUP E - Occupational Safety (ISO 45001:2018 + PP 50/2012 SMK3)
 */
import { m, f, req, sel, num, dt, txt, WF, riskFields, residualFields, PRIORITY, CHECK_RESULT } from './defs.js';

export const group = { code: 'E', key: 'safety', name: 'Occupational Safety', nameId: 'Keselamatan & Kesehatan Kerja', icon: '🦺' };

const PPE = ['Helm', 'Sepatu Safety', 'Rompi Reflektif', 'Sarung Tangan', 'Kacamata Safety', 'Face Shield', 'Pelindung Telinga', 'Masker/Respirator', 'Life Jacket', 'Full Body Harness', 'Wearpack', 'Sepatu Boot Karet'];

const HAZARD_TYPES = [
  'Mekanik (terjepit, terpotong, tertimpa)', 'Ketinggian / Jatuh', 'Listrik', 'Kebakaran & Ledakan',
  'Bahan Kimia / B3', 'Kebisingan', 'Getaran', 'Suhu Ekstrem', 'Pencahayaan', 'Ergonomi',
  'Biologi', 'Ruang Terbatas (Confined Space)', 'Tenggelam / Jatuh ke Laut', 'Lalu Lintas Kendaraan',
  'Pengangkatan Beban (Lifting)', 'Radiasi', 'Psikososial', 'Gerakan Kapal / Cuaca',
];

export default [
  m({
    key: 'incident',
    name: 'Incident',
    nameId: 'Kecelakaan Kerja / Insiden',
    icon: '🚨',
    codePrefix: 'INC',
    scope: 'any',
    workflow: WF.REPORT,
    capa: true,
    contractorAccess: true,
    standards: ['ISO 45001:2018 §10.2'],
    regulations: [
      'UU No. 1 Tahun 1970 tentang Keselamatan Kerja',
      'PP No. 50 Tahun 2012 (SMK3) Elemen 8',
      'Permennaker No. 03/MEN/1998 tentang Tata Cara Pelaporan Kecelakaan',
    ],
    fields: [
      req('title', 'Judul Kejadian'),
      dt('incident_date', 'Tanggal Kejadian', { required: true }),
      f('incident_time', 'Waktu Kejadian', 'time'),
      dt('reported_date', 'Tanggal Dilaporkan'),
      sel('incident_type', 'Jenis Insiden', [
        'Kecelakaan Kerja - Cedera', 'Kecelakaan Kerja - Tanpa Cedera', 'Kebakaran', 'Peledakan',
        'Tumpahan Bahan Kimia/B3', 'Kerusakan Properti', 'Kecelakaan Kendaraan', 'Kecelakaan Alat Angkat',
        'Tersengat Listrik', 'Jatuh dari Ketinggian', 'Jatuh ke Laut (Man Overboard)', 'Keracunan',
        'Kecelakaan Penumpang', 'Kejadian Keamanan', 'Lainnya',
      ], { required: true }),
      sel('classification', 'Klasifikasi Keparahan', [
        'First Aid Case (FAC)', 'Medical Treatment Case (MTC)', 'Restricted Work Case (RWC)',
        'Lost Time Injury (LTI)', 'Fatality', 'Near Miss', 'Property Damage', 'Environmental Damage',
      ], { required: true }),
      sel('location_type', 'Lokasi Kejadian', ['Dermaga', 'Area Parkir/Antrian', 'Terminal Penumpang', 'Kapal - Dek Kendaraan', 'Kapal - Ruang Mesin', 'Kapal - Anjungan', 'Kapal - Akomodasi', 'Movable Bridge', 'Gangway', 'Kantor', 'Bengkel', 'Gudang', 'Perairan', 'Lainnya']),
      f('exact_location', 'Detail Lokasi'),
      txt('description', 'Kronologi Kejadian', { required: true }),
      num('injured_count', 'Jumlah Korban Cedera'),
      num('fatality_count', 'Jumlah Korban Meninggal'),
      f('victim_names', 'Nama Korban'),
      sel('victim_category', 'Kategori Korban', ['Pegawai Organik', 'ABK', 'Kontraktor', 'Penumpang', 'Pengguna Jasa', 'Pihak Ketiga', 'Tidak Ada Korban']),
      num('lost_days', 'Hari Kerja Hilang'),
      num('property_loss', 'Kerugian Properti (IDR)', { type: 'currency' }),
      f('body_part', 'Bagian Tubuh Terluka', 'multiselect', { options: ['Kepala', 'Mata', 'Wajah', 'Leher', 'Bahu', 'Lengan', 'Tangan/Jari', 'Punggung', 'Dada', 'Perut', 'Pinggul', 'Kaki', 'Telapak Kaki', 'Organ Dalam', 'Seluruh Tubuh'] }),
      f('immediate_cause_unsafe_act', 'Penyebab Langsung - Tindakan Tidak Aman', 'textarea'),
      f('immediate_cause_unsafe_condition', 'Penyebab Langsung - Kondisi Tidak Aman', 'textarea'),
      txt('root_cause', 'Akar Masalah (Basic Cause)'),
      txt('immediate_action', 'Tindakan Segera di Lokasi'),
      f('investigation_team', 'Tim Investigasi'),
      dt('investigation_date', 'Tanggal Investigasi'),
      f('ppe_used', 'APD yang Digunakan', 'multiselect', { options: PPE }),
      f('reported_disnaker', 'Dilaporkan ke Disnaker (2x24 jam)', 'bool', { help: 'Permennaker No. 03/MEN/1998' }),
      f('reported_bpjs', 'Dilaporkan ke BPJS Ketenagakerjaan', 'bool'),
      f('reported_kemenhub', 'Dilaporkan ke Kemenhub/Syahbandar', 'bool'),
      ...riskFields('potential_'),
      txt('lesson_learned', 'Pembelajaran (Lesson Learned)'),
    ],
  }),

  m({
    key: 'near_miss',
    name: 'Near Miss',
    nameId: 'Nyaris Celaka',
    icon: '⚡',
    codePrefix: 'NMS',
    scope: 'any',
    workflow: WF.REPORT,
    capa: true,
    contractorAccess: true,
    standards: ['ISO 45001:2018 §10.2'],
    fields: [
      req('title', 'Judul Kejadian'),
      dt('event_date', 'Tanggal Kejadian', { required: true }),
      f('event_time', 'Waktu', 'time'),
      sel('location_type', 'Lokasi', ['Dermaga', 'Terminal Penumpang', 'Kapal', 'Movable Bridge', 'Gangway', 'Area Parkir', 'Bengkel', 'Kantor', 'Perairan', 'Lainnya']),
      f('exact_location', 'Detail Lokasi'),
      txt('description', 'Uraian Kejadian', { required: true }),
      sel('hazard_type', 'Jenis Bahaya', HAZARD_TYPES),
      txt('potential_consequence', 'Potensi Konsekuensi'),
      ...riskFields('potential_'),
      txt('immediate_action', 'Tindakan Segera'),
      f('reporter_anonymous', 'Pelaporan Anonim', 'bool'),
    ],
  }),

  m({
    key: 'unsafe_action',
    name: 'Unsafe Action',
    nameId: 'Tindakan Tidak Aman',
    icon: '🙅',
    codePrefix: 'USA',
    scope: 'any',
    workflow: WF.REPORT,
    capa: true,
    contractorAccess: true,
    standards: ['ISO 45001:2018 §8.1'],
    fields: [
      req('title', 'Judul Temuan'),
      dt('observed_date', 'Tanggal Pengamatan', { required: true }),
      sel('category', 'Kategori Tindakan', [
        'Tidak Menggunakan APD', 'Bekerja Tanpa Izin Kerja', 'Mengabaikan Prosedur',
        'Posisi Kerja Berbahaya', 'Mengoperasikan Alat Tanpa Kewenangan', 'Kecepatan Berlebih',
        'Merokok di Area Terlarang', 'Menonaktifkan Alat Pengaman', 'Bergurau Saat Bekerja',
        'Mengangkat Beban Tidak Benar', 'Menggunakan Alat Rusak', 'Lainnya',
      ], { required: true }),
      f('person_observed', 'Pihak yang Diamati'),
      sel('person_category', 'Kategori', ['Pegawai', 'ABK', 'Kontraktor', 'Pengguna Jasa', 'Pihak Ketiga']),
      f('exact_location', 'Lokasi'),
      txt('description', 'Uraian Temuan', { required: true }),
      sel('severity', 'Tingkat Potensi Bahaya', PRIORITY, { required: true }),
      txt('corrective_action', 'Tindakan Koreksi di Tempat'),
      sel('intervention', 'Bentuk Intervensi', ['Teguran Lisan', 'Coaching di Tempat', 'Penghentian Pekerjaan (Stop Work)', 'Teguran Tertulis', 'Pelatihan Ulang']),
      f('stop_work_applied', 'Stop Work Authority Digunakan', 'bool'),
    ],
  }),

  m({
    key: 'unsafe_condition',
    name: 'Unsafe Condition',
    nameId: 'Kondisi Tidak Aman',
    icon: '🚧',
    codePrefix: 'USC',
    scope: 'any',
    workflow: WF.REPORT,
    capa: true,
    contractorAccess: true,
    standards: ['ISO 45001:2018 §8.1'],
    fields: [
      req('title', 'Judul Temuan'),
      dt('observed_date', 'Tanggal Pengamatan', { required: true }),
      sel('category', 'Kategori Kondisi', [
        'Pelindung Mesin Rusak/Hilang', 'Housekeeping Buruk', 'Pencahayaan Kurang',
        'Kebisingan Berlebih', 'Instalasi Listrik Tidak Aman', 'APAR Kedaluwarsa/Tidak Ada',
        'Jalur Evakuasi Terhalang', 'Permukaan Licin', 'Railing/Pagar Pengaman Rusak',
        'Rambu Keselamatan Tidak Ada', 'Tumpahan Cairan/Oli', 'Fender/Bollard Rusak',
        'Ventilasi Buruk', 'Alat Rusak', 'Lainnya',
      ], { required: true }),
      f('exact_location', 'Lokasi'),
      txt('description', 'Uraian Kondisi', { required: true }),
      sel('severity', 'Tingkat Potensi Bahaya', PRIORITY, { required: true }),
      f('asset_ref', 'Aset Terkait', 'asset'),
      txt('immediate_action', 'Tindakan Segera'),
      f('area_isolated', 'Area Diisolasi / Ditutup', 'bool'),
      f('pic', 'Penanggung Jawab Perbaikan', 'user'),
      dt('due_date', 'Target Perbaikan', { alert: 'due' }),
    ],
  }),

  m({
    key: 'hira',
    name: 'HIRA / HIRADC',
    nameId: 'Identifikasi Bahaya & Penilaian Risiko',
    icon: '🧭',
    codePrefix: 'HIRA',
    scope: 'any',
    workflow: WF.RISK,
    capa: true,
    contractorAccess: true,
    standards: ['ISO 45001:2018 §6.1.2', 'ISO 31000:2018'],
    regulations: ['PP No. 50 Tahun 2012 (SMK3) Elemen 2 & 3'],
    fields: [
      req('title', 'Judul / Aktivitas'),
      f('process_activity', 'Proses / Aktivitas Kerja', 'text', { required: true }),
      sel('routine', 'Sifat Aktivitas', ['Rutin', 'Non-Rutin', 'Darurat'], { required: true }),
      f('exact_location', 'Lokasi Kerja'),
      sel('hazard_type', 'Jenis Bahaya', HAZARD_TYPES, { required: true }),
      txt('hazard_description', 'Uraian Bahaya', { required: true }),
      txt('potential_impact', 'Potensi Dampak / Konsekuensi'),
      f('affected_party', 'Pihak Terpapar', 'multiselect', { options: ['Pegawai', 'ABK', 'Kontraktor', 'Penumpang', 'Pengguna Jasa', 'Masyarakat Sekitar', 'Lingkungan', 'Aset'] }),
      ...riskFields(),
      txt('existing_control', 'Pengendalian yang Ada'),
      sel('control_hierarchy', 'Hirarki Pengendalian Tambahan', ['Eliminasi', 'Substitusi', 'Rekayasa Teknik', 'Administratif', 'APD']),
      txt('additional_control', 'Pengendalian Tambahan'),
      ...residualFields(),
      f('required_ppe', 'APD Wajib', 'multiselect', { options: PPE }),
      f('legal_requirement', 'Persyaratan Legal Terkait'),
      f('pic', 'Penanggung Jawab', 'user'),
      dt('review_date', 'Tanggal Tinjauan Ulang', { alert: 'expiry' }),
      sel('acceptability', 'Keberterimaan Risiko', ['Dapat Diterima', 'Dapat Diterima dengan Pengendalian', 'Tidak Dapat Diterima']),
    ],
  }),

  m({
    key: 'jsa',
    name: 'Job Safety Analysis',
    nameId: 'Analisis Keselamatan Pekerjaan (JSA)',
    icon: '📝',
    codePrefix: 'JSA',
    scope: 'any',
    workflow: WF.SIMPLE,
    capa: true,
    contractorAccess: true,
    standards: ['ISO 45001:2018 §8.1.2'],
    fields: [
      req('title', 'Judul Pekerjaan'),
      dt('analysis_date', 'Tanggal Analisis', { required: true }),
      f('work_location', 'Lokasi Pekerjaan'),
      f('executor', 'Pelaksana Pekerjaan'),
      sel('executor_type', 'Jenis Pelaksana', ['Internal', 'Kontraktor', 'Gabungan']),
      f('contractor_ref', 'Kontraktor', 'contractor'),
      txt('job_steps', 'Tahapan Pekerjaan', { required: true, help: 'Satu tahap per baris.' }),
      txt('hazards_per_step', 'Bahaya per Tahapan', { required: true }),
      txt('controls_per_step', 'Pengendalian per Tahapan', { required: true }),
      ...riskFields(),
      f('required_ppe', 'APD Wajib', 'multiselect', { options: PPE }),
      f('permit_required', 'Memerlukan Izin Kerja', 'bool'),
      f('permit_types', 'Jenis Izin Kerja', 'multiselect', { options: ['Panas (Hot Work)', 'Ruang Terbatas', 'Ketinggian', 'Listrik / LOTO', 'Penggalian', 'Pengangkatan', 'Penyelaman', 'Radiografi'] }),
      f('team_members', 'Anggota Tim'),
      f('reviewed_by', 'Ditinjau Oleh', 'user'),
      f('approved_by', 'Disetujui Oleh', 'user'),
    ],
  }),

  m({
    key: 'work_permit',
    name: 'Work Permit',
    nameId: 'Izin Kerja (PTW)',
    icon: '🎫',
    codePrefix: 'PTW',
    scope: 'any',
    workflow: WF.PERMIT,
    capa: true,
    contractorAccess: true,
    standards: ['ISO 45001:2018 §8.1.2'],
    regulations: ['UU No. 1 Tahun 1970 Pasal 3', 'Permenaker No. 09 Tahun 2016 (Kerja di Ketinggian)'],
    fields: [
      req('title', 'Uraian Pekerjaan'),
      f('permit_types', 'Jenis Izin Kerja', 'multiselect', {
        required: true,
        options: ['Pekerjaan Panas (Hot Work)', 'Pekerjaan Dingin (Cold Work)', 'Ruang Terbatas', 'Ketinggian >1.8m', 'Listrik / LOTO', 'Penggalian', 'Pengangkatan Berat', 'Penyelaman', 'Radiografi', 'Pekerjaan di Atas Air', 'Bunkering BBM'],
      }),
      f('work_location', 'Lokasi Pekerjaan', 'text', { required: true }),
      f('asset_ref', 'Aset / Peralatan', 'asset'),
      dt('valid_from', 'Berlaku Mulai', { required: true }),
      dt('valid_to', 'Berlaku Sampai', { required: true, alert: 'expiry' }),
      f('shift_time', 'Jam Kerja'),
      sel('executor_type', 'Pelaksana', ['Internal', 'Kontraktor'], { required: true }),
      f('contractor_ref', 'Kontraktor', 'contractor'),
      num('worker_count', 'Jumlah Pekerja'),
      f('supervisor', 'Pengawas Pekerjaan', 'user', { required: true }),
      f('jsa_ref', 'Nomor JSA / HIRA'),
      f('required_ppe', 'APD Wajib', 'multiselect', { options: PPE }),
      f('precautions', 'Tindakan Pencegahan', 'multiselect', {
        options: ['Gas Test Dilakukan', 'Isolasi Energi (LOTO)', 'Fire Watch Disiagakan', 'APAR Tersedia', 'Ventilasi Mekanik', 'Area Dibarikade', 'Rambu Dipasang', 'Standby Person', 'Komunikasi Radio', 'Peralatan Rescue Siap', 'Koordinasi dengan Nakhoda', 'Koordinasi dengan Syahbandar'],
      }),
      num('gas_test_o2', 'Hasil Gas Test - O2 (%)', { step: 0.1 }),
      num('gas_test_lel', 'Hasil Gas Test - LEL (%)', { step: 0.1 }),
      num('gas_test_h2s', 'Hasil Gas Test - H2S (ppm)', { step: 0.1 }),
      num('gas_test_co', 'Hasil Gas Test - CO (ppm)', { step: 0.1 }),
      f('gas_test_by', 'Gas Test Dilakukan Oleh'),
      f('approved_by', 'Disetujui Oleh', 'user'),
      dt('closed_date', 'Tanggal Penutupan Izin'),
      txt('close_out_notes', 'Catatan Penutupan'),
      f('area_restored', 'Area Dikembalikan Aman', 'bool'),
    ],
  }),

  m({
    key: 'toolbox_meeting',
    name: 'Toolbox Meeting',
    nameId: 'Toolbox Meeting / Safety Talk',
    icon: '🗣',
    codePrefix: 'TBM',
    scope: 'any',
    workflow: WF.SIMPLE,
    contractorAccess: true,
    standards: ['ISO 45001:2018 §7.4'],
    regulations: ['PP No. 50 Tahun 2012 (SMK3) Elemen 4'],
    fields: [
      req('title', 'Topik'),
      dt('meeting_date', 'Tanggal', { required: true }),
      f('meeting_time', 'Waktu', 'time'),
      f('location', 'Lokasi'),
      f('leader', 'Pemimpin Meeting', 'user', { required: true }),
      num('participant_count', 'Jumlah Peserta', { required: true }),
      f('participants', 'Daftar Peserta', 'textarea'),
      sel('topic_category', 'Kategori Topik', ['Bahaya Pekerjaan Hari Ini', 'Penggunaan APD', 'Prosedur Darurat', 'Pembelajaran Insiden', 'Housekeeping', 'Keselamatan Pelayaran', 'Lingkungan', 'Kesehatan', 'Keamanan']),
      txt('discussion', 'Materi Pembahasan', { required: true }),
      txt('hazards_today', 'Bahaya Pekerjaan Hari Ini'),
      txt('commitment', 'Komitmen / Kesepakatan'),
      num('duration_minutes', 'Durasi (menit)'),
    ],
  }),

  m({
    key: 'safety_observation',
    name: 'Safety Observation',
    nameId: 'Observasi Keselamatan (BBS)',
    icon: '👁',
    codePrefix: 'OBS',
    scope: 'any',
    workflow: WF.REPORT,
    capa: true,
    contractorAccess: true,
    standards: ['ISO 45001:2018 §9.1'],
    fields: [
      req('title', 'Judul Observasi'),
      dt('observation_date', 'Tanggal Observasi', { required: true }),
      f('area_observed', 'Area yang Diobservasi'),
      sel('observation_type', 'Jenis Observasi', ['Perilaku Aman', 'Perilaku Tidak Aman', 'Kondisi Aman', 'Kondisi Tidak Aman', 'Safety Patrol Manajemen']),
      f('observer', 'Observer', 'user'),
      num('safe_count', 'Jumlah Pengamatan Aman'),
      num('unsafe_count', 'Jumlah Pengamatan Tidak Aman'),
      num('safe_percentage', 'Persentase Aman (%)', { computed: 'safePercentage', readonly: true }),
      f('categories_observed', 'Aspek yang Diamati', 'multiselect', {
        options: ['Penggunaan APD', 'Posisi Tubuh', 'Penggunaan Alat', 'Prosedur Kerja', 'Housekeeping', 'Reaksi Pekerja', 'Rambu & Barikade', 'Komunikasi'],
      }),
      txt('findings', 'Temuan'),
      txt('feedback_given', 'Umpan Balik yang Diberikan'),
      txt('follow_up', 'Tindak Lanjut'),
    ],
  }),

  m({
    key: 'emergency_response',
    name: 'Emergency Response',
    nameId: 'Tanggap Darurat & Latihan',
    icon: '🆘',
    codePrefix: 'ERP',
    scope: 'any',
    workflow: WF.REPORT,
    capa: true,
    standards: ['ISO 45001:2018 §8.2', 'ISO 22301:2019'],
    regulations: ['Kepmenaker No. 186 Tahun 1999 (Penanggulangan Kebakaran)', 'SOLAS Ch. III - Drills'],
    fields: [
      req('title', 'Judul Kegiatan / Kejadian'),
      sel('record_type', 'Jenis Rekaman', ['Latihan (Drill)', 'Kejadian Darurat Nyata', 'Uji Peralatan Darurat', 'Simulasi Meja (Tabletop)'], { required: true }),
      sel('scenario', 'Skenario', [
        'Kebakaran di Kapal', 'Kebakaran di Pelabuhan', 'Man Overboard', 'Abandon Ship',
        'Tumpahan Minyak', 'Kapal Kandas', 'Tubrukan Kapal', 'Gempa Bumi', 'Tsunami',
        'Evakuasi Penumpang Massal', 'Kebocoran B3', 'Ancaman Bom / Keamanan', 'Kegagalan Listrik Total',
        'Cuaca Ekstrem', 'Kecelakaan Kerja Serius', 'Pandemi / Wabah',
      ], { required: true }),
      dt('event_date', 'Tanggal', { required: true }),
      f('event_time', 'Waktu', 'time'),
      f('location', 'Lokasi'),
      num('participant_count', 'Jumlah Peserta'),
      num('response_time_minutes', 'Waktu Respons (menit)'),
      num('evacuation_time_minutes', 'Waktu Evakuasi (menit)'),
      f('muster_complete', 'Seluruh Personil Terkumpul di Muster Station', 'bool'),
      f('external_agency', 'Instansi Eksternal yang Terlibat', 'multiselect', {
        options: ['Syahbandar / KSOP', 'Basarnas', 'Damkar', 'Polisi / Polairud', 'TNI AL', 'BPBD', 'Rumah Sakit', 'KLHK', 'Tidak Ada'],
      }),
      txt('scenario_description', 'Uraian Skenario / Kronologi'),
      txt('evaluation', 'Evaluasi Pelaksanaan'),
      txt('weaknesses', 'Kelemahan yang Teridentifikasi'),
      txt('improvement', 'Rekomendasi Perbaikan'),
      sel('effectiveness', 'Efektivitas', ['Sangat Efektif', 'Efektif', 'Cukup', 'Kurang Efektif']),
      dt('next_drill', 'Jadwal Latihan Berikutnya', { alert: 'expiry' }),
    ],
  }),
];
