/**
 * GROUP P - Competency & Training Management
 *
 * Kompetensi adalah satu-satunya pengendalian risiko yang dibawa pekerja ke
 * mana pun ia ditugaskan, dan satu-satunya yang kedaluwarsa diam-diam. Kelompok
 * ini menutup seluruh siklusnya: katalog pelatihan, matriks wajib per jabatan,
 * pendaftaran berjenjang, kehadiran, pembelajaran daring, ujian, asesmen
 * praktek, OJT, kesenjangan kompetensi, anggaran, vendor, sampai evaluasi
 * efektivitas Kirkpatrick level 1-4.
 *
 * Acuan: ISO 45001:2018 §7.2 & §7.3, ISO 9001:2015 §7.2, PP No. 50 Tahun 2012
 * (SMK3) Elemen 4 & 12, Permenaker No. 02/MEN/1992, STCW 2010 Manila Amendments.
 */
import { m, f, req, sel, num, dt, txt, WF, PRIORITY } from './defs.js';

export const group = { code: 'P', key: 'training', name: 'Competency & Training Management', nameId: 'Kompetensi & Pelatihan', icon: '🎓' };

/* --------------------------------------------------------------- pilihan */

/** Status berlaku sertifikat - dihitung, bukan dipilih. Lihat RISK_LEVELS. */
export const CERT_STATES = ['Berlaku', 'Akan Kedaluwarsa', 'Kedaluwarsa'];

/** Kategori pelatihan wajib - dipakai katalog, matriks dan dashboard. */
export const TRAINING_CATEGORIES = [
  'QHSE',
  'Safety / K3',
  'Emergency Response',
  'Lingkungan',
  'Maritim & Pelayaran',
  'Operasional Pelabuhan',
  'Kesehatan Kerja',
  'Manajemen & Kepemimpinan',
  'Digital & Sistem Informasi',
];

const MANDATORY_TYPE = ['Wajib Regulasi', 'Wajib Internal', 'Wajib Bersyarat', 'Pengembangan (Tidak Wajib)'];

const METHODS = [
  'Classroom (Tatap Muka)', 'Online / E-Learning', 'Blended Learning',
  'Praktek Lapangan', 'Simulator', 'On the Job Training (OJT)', 'Webinar',
];

/**
 * Tingkat kompetensi berawalan angka: fungsi turunan membaca angka di depan,
 * sehingga kesenjangan dapat dihitung tanpa tabel pemetaan terpisah.
 */
const COMPETENCY_LEVELS = [
  { value: '1 - Beginner', label: '★☆☆☆☆ 1 - Beginner (Awareness)' },
  { value: '2 - Basic', label: '★★☆☆☆ 2 - Basic (Dibimbing)' },
  { value: '3 - Intermediate', label: '★★★☆☆ 3 - Intermediate (Mandiri)' },
  { value: '4 - Advanced', label: '★★★★☆ 4 - Advanced (Mampu Menilai)' },
  { value: '5 - Expert', label: '★★★★★ 5 - Expert (Mampu Mengajar)' },
];

const TARGET_SCOPES = ['Kantor Pusat', 'Regional', 'Cabang', 'Pelabuhan', 'Kapal', 'Seluruh Unit'];

const VESSEL_TYPES = ['Semua Jenis Kapal', 'KMP Ro-Ro', 'KMP Ro-Pax', 'Kapal Cepat', 'Landing Craft Tank', 'Tug Boat'];

/* -------------------------------------------------------------- workflow */

/** Pendaftaran pelatihan: tiga lapis persetujuan, plus jalur daftar tunggu. */
const WF_REGISTRATION = [
  { key: 'draft', label: 'Draft', requires: 'create', initial: true },
  { key: 'submitted', label: 'Diajukan', requires: 'create' },
  { key: 'supervisor_approved', label: 'Disetujui Atasan', requires: 'edit' },
  { key: 'hr_approved', label: 'Disetujui SDM', requires: 'edit' },
  { key: 'qhse_approved', label: 'Disetujui QHSE', requires: 'approve' },
  { key: 'waiting_list', label: 'Daftar Tunggu', requires: 'edit' },
  { key: 'confirmed', label: 'Peserta Terkonfirmasi', requires: 'approve', terminal: true },
  { key: 'cancelled', label: 'Dibatalkan', requires: 'edit', terminal: true, negative: true },
  { key: 'rejected', label: 'Ditolak', requires: 'approve', terminal: true, negative: true },
];

/** Penyelenggaraan: rencana - buka pendaftaran - berjalan - selesai. */
const WF_SCHEDULE = [
  { key: 'planned', label: 'Direncanakan', requires: 'create', initial: true },
  { key: 'registration', label: 'Pendaftaran Dibuka', requires: 'edit' },
  { key: 'running', label: 'Berlangsung', requires: 'edit' },
  { key: 'completed', label: 'Selesai', requires: 'edit', terminal: true },
  { key: 'postponed', label: 'Ditunda', requires: 'edit' },
  { key: 'cancelled', label: 'Dibatalkan', requires: 'approve', terminal: true, negative: true },
];

/** Sertifikat pegawai: aktif sampai kedaluwarsa, dengan jalur perpanjangan. */
const WF_CERTIFICATE = [
  { key: 'draft', label: 'Draft', requires: 'create', initial: true },
  { key: 'verified', label: 'Terverifikasi', requires: 'approve' },
  { key: 'renewal', label: 'Proses Perpanjangan', requires: 'edit' },
  { key: 'expired', label: 'Kedaluwarsa', requires: 'edit', terminal: true, negative: true },
  { key: 'revoked', label: 'Dicabut', requires: 'approve', terminal: true, negative: true },
];

export default [
  /* ------------------------------------------------- 1. katalog pelatihan */
  m({
    key: 'training_master',
    name: 'Training Catalogue',
    nameId: 'Katalog Pelatihan (Master)',
    master: true,
    scope: 'corporate',
    orgFields: [],
    codePrefix: 'TRM',
    icon: '📚',
    workflow: WF.RECORD,
    standards: ['ISO 45001:2018 §7.2', 'ISO 9001:2015 §7.2'],
    regulations: ['PP No. 50 Tahun 2012 (SMK3) Elemen 12'],
    listFields: ['name', 'training_code', 'category', 'mandatory', 'lesson_hours', 'validity_months'],
    fields: [
      req('name', 'Nama Training'),
      req('training_code', 'Kode Training', 'text', { placeholder: 'QHSE-01' }),
      sel('category', 'Kategori Training', TRAINING_CATEGORIES, { required: true }),
      sel('mandatory', 'Sifat Pelatihan', MANDATORY_TYPE, { required: true }),
      f('regulation_basis', 'Dasar Regulasi / Standar', 'text', { help: 'Contoh: Permenaker No. 02/MEN/1992 untuk Ahli K3 Umum.' }),
      num('duration_days', 'Durasi (hari)', { step: 0.5 }),
      num('lesson_hours', 'Jam Pelajaran (JP)'),
      sel('method', 'Metode Pelaksanaan', METHODS, { type: 'multiselect' }),
      sel('competency_level', 'Tingkat Kompetensi Dituju', COMPETENCY_LEVELS),
      f('certificate_issued', 'Menerbitkan Sertifikat', 'bool'),
      f('certificate_body', 'Lembaga Penerbit Sertifikat'),
      num('validity_months', 'Masa Berlaku Sertifikat (bulan)', { help: 'Kosongkan bila sertifikat berlaku seumur hidup.' }),
      f('refresh_required', 'Perlu Refresh Training', 'bool'),
      num('refresh_interval_months', 'Interval Refresh (bulan)'),
      num('passing_grade', 'Nilai Kelulusan', { min: 0, max: 100 }),
      num('standard_cost', 'Biaya Standar per Peserta (IDR)', { type: 'currency' }),
      f('prerequisite', 'Prasyarat Peserta'),
      txt('target_audience', 'Sasaran Peserta'),
      txt('objective', 'Tujuan Pembelajaran'),
      txt('syllabus', 'Silabus / Pokok Bahasan'),
    ],
  }),

  /* -------------------------------------------------- 2. matriks pelatihan */
  m({
    key: 'training_matrix',
    name: 'Mandatory Training Matrix',
    nameId: 'Matriks Pelatihan Wajib',
    scope: 'any',
    codePrefix: 'TMX',
    icon: '🧮',
    workflow: WF.RECORD,
    standards: ['ISO 45001:2018 §7.2'],
    regulations: ['PP No. 50 Tahun 2012 (SMK3) Elemen 12', 'STCW 2010'],
    listFields: ['position', 'training_name', 'requirement_type', 'target_scope', 'division'],
    labelField: 'position',
    fields: [
      req('position', 'Jabatan'),
      f('division', 'Divisi / Unit Kerja'),
      f('job_grade', 'Grade / Golongan'),
      sel('target_scope', 'Lokasi Penugasan', TARGET_SCOPES, { required: true }),
      sel('vessel_type', 'Jenis Kapal (bila di kapal)', VESSEL_TYPES),
      f('training_ref', 'Training Wajib', 'training', { required: true }),
      req('training_name', 'Nama Training', 'text', { help: 'Disalin dari katalog agar matriks tetap terbaca bila katalog berubah.' }),
      sel('category', 'Kategori', TRAINING_CATEGORIES),
      sel('requirement_type', 'Sifat Kewajiban', [
        'Wajib Sebelum Bertugas', 'Wajib Berkala', 'Wajib Bersyarat (Tugas Tertentu)', 'Dianjurkan',
      ], { required: true }),
      num('refresh_interval_months', 'Interval Penyegaran (bulan)'),
      sel('required_level', 'Tingkat Kompetensi Minimum', COMPETENCY_LEVELS),
      f('regulation_basis', 'Dasar Kewajiban'),
      sel('priority', 'Prioritas Pemenuhan', PRIORITY),
      dt('effective_date', 'Berlaku Sejak'),
      dt('review_date', 'Tinjauan Matriks', { alert: 'expiry' }),
      txt('notes', 'Catatan'),
    ],
  }),

  /* ------------------------------------------------- 3. matriks kompetensi */
  m({
    key: 'competency_matrix',
    name: 'Employee Competency Matrix',
    nameId: 'Matriks Kompetensi Pegawai',
    scope: 'any',
    codePrefix: 'KMX',
    icon: '⭐',
    workflow: WF.RECORD,
    standards: ['ISO 45001:2018 §7.2', 'ISO 9001:2015 §7.2'],
    listFields: ['competency_name', 'employee_name', 'position', 'required_level', 'current_level', 'gap_level'],
    labelField: 'competency_name',
    fields: [
      req('competency_name', 'Nama Kompetensi'),
      f('employee_ref', 'Pegawai', 'employee', { required: true }),
      req('employee_name', 'Nama Pegawai'),
      f('position', 'Jabatan'),
      f('division', 'Divisi / Unit Kerja'),
      sel('competency_type', 'Jenis Kompetensi', ['Teknis', 'Fungsional', 'Perilaku', 'Kepemimpinan', 'QHSE', 'Kepelautan'], { required: true }),
      sel('required_level', 'Tingkat Dipersyaratkan', COMPETENCY_LEVELS, { required: true }),
      sel('current_level', 'Tingkat Saat Ini', COMPETENCY_LEVELS, { required: true }),
      num('gap_level', 'Kesenjangan (tingkat)', { computed: 'competencyGap', readonly: true }),
      sel('gap_status', 'Status Kompetensi', ['Memenuhi', 'Perlu Pengembangan', 'Kesenjangan Besar'], { computed: 'competencyGapStatus', readonly: true }),
      dt('assessment_date', 'Tanggal Penilaian'),
      f('assessor', 'Penilai', 'user'),
      f('evidence', 'Bukti Kompetensi', 'text', { help: 'Nomor sertifikat, hasil asesmen, atau rekaman OJT.' }),
      txt('development_plan', 'Rencana Pengembangan'),
      dt('target_date', 'Target Pemenuhan', { alert: 'due' }),
    ],
  }),

  /* ------------------------------------------------ 4. sertifikasi pegawai */
  m({
    key: 'employee_certification',
    name: 'Employee Certification',
    nameId: 'Sertifikasi Pegawai',
    scope: 'any',
    codePrefix: 'SRT',
    icon: '🏅',
    workflow: WF_CERTIFICATE,
    capa: true,
    standards: ['ISO 45001:2018 §7.2', 'ISO 9001:2015 §7.2'],
    regulations: [
      'Permenaker No. 02/MEN/1992 (Ahli K3)',
      'Permenaker No. 08 Tahun 2020 (Operator Pesawat Angkat & Angkut)',
      'STCW 2010 - Sertifikat Keahlian & Keterampilan Pelaut',
      'PM Perhubungan tentang Sertifikasi Awak Kapal',
    ],
    listFields: ['certificate_name', 'employee_name', 'certificate_number', 'issue_date', 'valid_until', 'cert_status'],
    labelField: 'certificate_name',
    fields: [
      req('certificate_name', 'Nama Sertifikat'),
      f('employee_ref', 'Pegawai', 'employee', { required: true }),
      req('employee_name', 'Nama Pegawai'),
      f('position', 'Jabatan'),
      req('certificate_number', 'Nomor Sertifikat'),
      sel('certificate_type', 'Jenis Sertifikat', [
        'Sertifikat Kompetensi BNSP', 'Sertifikat Kemnaker (Lisensi K3)', 'Sertifikat Kepelautan (STCW)',
        'Sertifikat Kemenhub', 'Sertifikat Badan Klasifikasi (BKI)', 'Sertifikat Lembaga Pelatihan',
        'Sertifikat Internal ASDP', 'Sertifikat Kesehatan',
      ], { required: true }),
      f('training_ref', 'Training Terkait', 'training'),
      req('issuer', 'Lembaga Penerbit'),
      dt('issue_date', 'Tanggal Terbit', { required: true }),
      dt('valid_until', 'Berlaku Sampai', { alert: 'expiry', help: 'Kosongkan bila berlaku seumur hidup.' }),
      num('renewal_lead_days', 'Ambang Peringatan (hari sebelum kedaluwarsa)', { default: 30, help: 'Peringatan bertingkat 30 / 14 / 7 hari dan pada hari-H dihitung dari tanggal berlaku.' }),
      f('cert_status', 'Status Sertifikat', 'text', { computed: 'certStatus', readonly: true, values: CERT_STATES }),
      num('days_to_expiry', 'Sisa Hari Berlaku', { computed: 'daysToExpiry', readonly: true }),
      f('competency_area', 'Bidang Kompetensi'),
      sel('verification_status', 'Verifikasi Dokumen', ['Terverifikasi', 'Menunggu Verifikasi', 'Tidak Dapat Diverifikasi']),
      f('document_no', 'Nomor Arsip Dokumen', 'text', { help: 'Berkas PDF sertifikat dilampirkan pada tab Lampiran rekaman ini.' }),
      f('renewal_planned', 'Perpanjangan Sudah Direncanakan', 'bool'),
      dt('renewal_date', 'Rencana Perpanjangan', { alert: 'due' }),
      txt('notes', 'Catatan'),
    ],
  }),

  /* --------------------------------------------------- 5. jadwal pelatihan */
  m({
    key: 'training_schedule',
    name: 'Training Schedule',
    nameId: 'Jadwal Pelatihan',
    scope: 'any',
    codePrefix: 'TSC',
    icon: '🗓',
    workflow: WF_SCHEDULE,
    standards: ['ISO 45001:2018 §7.2'],
    listFields: ['title', 'period', 'start_date', 'method', 'quota', 'registered'],
    fields: [
      req('title', 'Judul Penyelenggaraan'),
      f('training_ref', 'Training dari Katalog', 'training', { required: true }),
      sel('plan_type', 'Jenis Rencana', ['Rencana Tahunan', 'Rencana Bulanan', 'Insidental / Kebutuhan Mendesak'], { required: true }),
      req('period', 'Periode', 'text', { placeholder: '2026-03', help: 'Isi YYYY untuk rencana tahunan atau YYYY-MM untuk rencana bulanan.' }),
      dt('start_date', 'Tanggal Mulai', { required: true }),
      dt('end_date', 'Tanggal Selesai'),
      f('session_time', 'Waktu Pelaksanaan', 'text', { placeholder: '08.00 - 16.00 WIB' }),
      sel('method', 'Metode', METHODS, { required: true }),
      f('venue', 'Tempat Pelaksanaan'),
      sel('target_scope', 'Sasaran Unit', TARGET_SCOPES),
      f('target_division', 'Divisi Sasaran'),
      f('vendor_ref', 'Vendor Penyelenggara', 'vendor'),
      f('instructor', 'Instruktur / Fasilitator'),
      f('batch', 'Angkatan / Batch'),
      num('quota', 'Kuota Peserta', { required: true }),
      num('registered', 'Peserta Terdaftar'),
      num('waiting_list', 'Daftar Tunggu'),
      num('seat_remaining', 'Sisa Kursi', { computed: 'seatRemaining', readonly: true }),
      num('cost_per_participant', 'Biaya per Peserta (IDR)', { type: 'currency' }),
      num('total_budget', 'Anggaran Penyelenggaraan (IDR)', { type: 'currency' }),
      f('pic', 'Penanggung Jawab', 'user'),
      dt('registration_close', 'Penutupan Pendaftaran', { alert: 'due' }),
      txt('notes', 'Catatan'),
    ],
  }),

  /* ------------------------------------------------ 6. pendaftaran peserta */
  m({
    key: 'training_registration',
    name: 'Training Registration',
    nameId: 'Pendaftaran Pelatihan',
    scope: 'any',
    codePrefix: 'TRG',
    icon: '📝',
    workflow: WF_REGISTRATION,
    standards: ['ISO 45001:2018 §7.2'],
    listFields: ['employee_name', 'training_name', 'position', 'registration_date', 'seat_status'],
    labelField: 'employee_name',
    fields: [
      req('employee_name', 'Nama Peserta'),
      f('employee_ref', 'Pegawai', 'employee', { required: true }),
      f('position', 'Jabatan'),
      f('division', 'Divisi / Unit Kerja'),
      f('training_ref', 'Training', 'training', { required: true }),
      req('training_name', 'Nama Training'),
      f('schedule_code', 'Kode Jadwal', 'text', { placeholder: 'TSC/2026/0001' }),
      dt('registration_date', 'Tanggal Pendaftaran', { required: true }),
      f('mandatory_flag', 'Termasuk Pelatihan Wajib', 'bool'),
      txt('justification', 'Alasan Kebutuhan'),
      f('supervisor', 'Atasan Langsung', 'user', { group: 'Persetujuan Berjenjang' }),
      dt('supervisor_date', 'Tanggal Persetujuan Atasan', { group: 'Persetujuan Berjenjang' }),
      f('hr_approver', 'Pejabat SDM', 'user', { group: 'Persetujuan Berjenjang' }),
      dt('hr_date', 'Tanggal Persetujuan SDM', { group: 'Persetujuan Berjenjang' }),
      f('qhse_approver', 'Pejabat QHSE', 'user', { group: 'Persetujuan Berjenjang' }),
      dt('qhse_date', 'Tanggal Persetujuan QHSE', { group: 'Persetujuan Berjenjang' }),
      sel('seat_status', 'Status Kursi', ['Terkonfirmasi', 'Daftar Tunggu', 'Dibatalkan']),
      num('waiting_number', 'Nomor Antrean'),
      sel('cancel_reason', 'Alasan Pembatalan', [
        'Tugas Operasional Mendesak', 'Sakit / Berhalangan', 'Kuota Penuh',
        'Pelatihan Ditunda', 'Anggaran Tidak Tersedia', 'Peserta Mengundurkan Diri',
      ]),
      txt('approval_note', 'Catatan Persetujuan'),
    ],
  }),

  /* --------------------------------------------------- 7. kehadiran peserta */
  m({
    key: 'training_attendance',
    name: 'Training Attendance',
    nameId: 'Kehadiran Pelatihan',
    scope: 'any',
    codePrefix: 'TAT',
    icon: '✅',
    workflow: WF.MONITORING,
    standards: ['ISO 45001:2018 §7.2'],
    listFields: ['employee_name', 'training_name', 'session_date', 'attendance_status', 'attendance_method'],
    labelField: 'employee_name',
    fields: [
      req('employee_name', 'Nama Peserta'),
      f('employee_ref', 'Pegawai', 'employee', { required: true }),
      f('training_ref', 'Training', 'training'),
      req('training_name', 'Nama Training'),
      f('schedule_code', 'Kode Jadwal'),
      dt('session_date', 'Tanggal Sesi', { required: true }),
      f('session_title', 'Nama Sesi / Materi'),
      f('check_in_time', 'Jam Masuk', 'time'),
      f('check_out_time', 'Jam Keluar', 'time'),
      sel('attendance_method', 'Metode Pencatatan', [
        'QR Code', 'Face Recognition', 'NFC / Kartu Pegawai', 'GPS Lokasi', 'Manual (Tanda Tangan)',
      ], { required: true }),
      f('gps_coordinate', 'Koordinat GPS', 'text', { placeholder: '-5.8901, 105.9012' }),
      f('device_id', 'Perangkat Pencatat'),
      sel('attendance_status', 'Status Kehadiran', ['Hadir', 'Terlambat', 'Izin', 'Sakit', 'Tidak Hadir'], { required: true }),
      num('session_hours', 'Jam Sesi (JP)', { step: 0.5 }),
      num('attended_hours', 'Jam Diikuti (JP)', { step: 0.5 }),
      num('attendance_percent', 'Persentase Kehadiran (%)', { computed: 'attendancePercent', readonly: true }),
      f('eligible_certificate', 'Memenuhi Syarat Sertifikat', 'bool', { help: 'Umumnya minimal 80% kehadiran.' }),
      f('verified_by', 'Diverifikasi Oleh', 'user'),
      txt('notes', 'Catatan'),
    ],
  }),

  /* ------------------------------------------- 8. materi pembelajaran (LMS) */
  m({
    key: 'learning_content',
    name: 'Online Learning Content',
    nameId: 'Materi Pembelajaran Daring (LMS)',
    scope: 'any',
    codePrefix: 'LMS',
    icon: '💻',
    workflow: WF.DOC,
    standards: ['ISO 9001:2015 §7.5', 'ISO 45001:2018 §7.2'],
    listFields: ['title', 'content_type', 'learning_path', 'duration_minutes', 'completion_rate'],
    fields: [
      req('title', 'Judul Materi'),
      f('training_ref', 'Training Terkait', 'training'),
      sel('content_type', 'Bentuk Materi', [
        'Video', 'Dokumen PDF', 'Modul Interaktif', 'Kuis', 'Simulasi', 'Animasi',
        'Paket SCORM', 'Audio / Podcast', 'Infografis',
      ], { required: true }),
      f('learning_path', 'Jalur Pembelajaran (Learning Path)', 'text', { placeholder: 'Jalur Petugas Dermaga - Tingkat Dasar' }),
      num('sequence', 'Urutan dalam Jalur'),
      num('duration_minutes', 'Durasi (menit)'),
      f('language', 'Bahasa'),
      f('content_url', 'Lokasi / Tautan Materi'),
      f('scorm_version', 'Versi SCORM', 'text', { placeholder: 'SCORM 1.2 / 2004' }),
      f('mandatory', 'Wajib Diselesaikan', 'bool'),
      num('min_completion_percent', 'Ambang Penyelesaian (%)', { min: 0, max: 100 }),
      num('enrolled_count', 'Peserta Terdaftar'),
      num('completed_count', 'Peserta Menyelesaikan'),
      num('completion_rate', 'Tingkat Penyelesaian (%)', { computed: 'completionRate', readonly: true }),
      num('avg_score', 'Rata-rata Nilai Kuis', { step: 0.1 }),
      num('avg_rating', 'Rata-rata Penilaian Peserta (1-5)', { step: 0.1, min: 0, max: 5 }),
      f('author', 'Penyusun Materi'),
      dt('published_date', 'Tanggal Terbit'),
      dt('review_due', 'Jatuh Tempo Tinjauan Materi', { alert: 'expiry' }),
      txt('description', 'Deskripsi Materi'),
    ],
  }),

  /* ----------------------------------------------------------- 9. ujian */
  m({
    key: 'training_exam',
    name: 'Training Exam',
    nameId: 'Ujian Pelatihan',
    scope: 'any',
    codePrefix: 'EXM',
    icon: '📄',
    workflow: WF.MONITORING,
    standards: ['ISO 45001:2018 §7.2'],
    listFields: ['employee_name', 'training_name', 'exam_date', 'score', 'exam_result'],
    labelField: 'employee_name',
    fields: [
      req('employee_name', 'Nama Peserta'),
      f('employee_ref', 'Pegawai', 'employee', { required: true }),
      f('training_ref', 'Training', 'training'),
      req('training_name', 'Nama Training'),
      dt('exam_date', 'Tanggal Ujian', { required: true }),
      sel('exam_type', 'Bentuk Ujian', [
        'Pilihan Ganda', 'Essay', 'Ujian Video', 'Ujian Praktek', 'Studi Kasus', 'Ujian Lisan',
      ], { type: 'multiselect', required: true }),
      num('question_count', 'Jumlah Soal'),
      f('randomised', 'Soal Diacak', 'bool'),
      num('time_limit_minutes', 'Batas Waktu (menit)'),
      num('attempt', 'Percobaan Ke-', { default: 1 }),
      num('passing_grade', 'Nilai Kelulusan', { min: 0, max: 100, required: true }),
      num('pretest_score', 'Nilai Pre-Test', { min: 0, max: 100, step: 0.1 }),
      num('score', 'Nilai Akhir (Post-Test)', { min: 0, max: 100, step: 0.1, required: true }),
      num('score_gain', 'Kenaikan Nilai', { computed: 'scoreGain', readonly: true }),
      f('exam_result', 'Hasil', 'text', { computed: 'examResult', readonly: true }),
      f('remedial_required', 'Perlu Remedial', 'bool'),
      dt('remedial_date', 'Rencana Remedial', { alert: 'due' }),
      f('examiner', 'Penguji', 'user'),
      txt('notes', 'Catatan Penguji'),
    ],
  }),

  /* ---------------------------------------------------- 10. asesmen praktek */
  m({
    key: 'practical_assessment',
    name: 'Practical Assessment',
    nameId: 'Asesmen Praktek',
    scope: 'any',
    codePrefix: 'PRA',
    icon: '🧯',
    workflow: WF.INSPECTION,
    capa: true,
    standards: ['ISO 45001:2018 §7.2', 'ISO 45001:2018 §8.2'],
    regulations: ['PP No. 50 Tahun 2012 (SMK3) Elemen 12', 'Permenaker No. 08 Tahun 2020'],
    listFields: ['title', 'employee_name', 'assessment_type', 'assessment_date', 'result'],
    fields: [
      req('title', 'Judul Asesmen'),
      f('employee_ref', 'Pegawai', 'employee', { required: true }),
      req('employee_name', 'Nama Pegawai'),
      f('position', 'Jabatan'),
      sel('assessment_type', 'Jenis Praktek', [
        'Penggunaan APAR', 'Evakuasi Darurat', 'Pertolongan Pertama (P3K)', 'Ruang Terbatas (Confined Space)',
        'Lock Out Tag Out (LOTO)', 'Bekerja di Ketinggian', 'Mengemudi Defensif', 'Operator Crane',
        'Operator Forklift', 'Mooring & Unmooring', 'Pengoperasian Ramp Door & Movable Bridge',
        'Penanggulangan Tumpahan', 'Peluncuran Sekoci & Life Raft', 'Pemadaman Kebakaran Kapal',
      ], { required: true }),
      dt('assessment_date', 'Tanggal Asesmen', { required: true }),
      f('location', 'Lokasi Asesmen'),
      f('assessor', 'Asesor', 'user', { required: true }),
      f('assessor_certificate', 'Sertifikat Asesor'),
      num('items_checked', 'Jumlah Kriteria Dinilai'),
      num('items_conform', 'Kriteria Terpenuhi'),
      num('conformity_rate', 'Tingkat Pemenuhan (%)', { computed: 'conformityRate', readonly: true }),
      num('passing_grade', 'Nilai Kelulusan', { min: 0, max: 100 }),
      num('score', 'Nilai Praktek', { min: 0, max: 100, step: 0.1 }),
      sel('result', 'Hasil Asesmen', ['Kompeten', 'Belum Kompeten'], { required: true }),
      txt('observation', 'Catatan Pengamatan'),
      txt('corrective_action', 'Tindakan Perbaikan Kompetensi'),
      dt('reassessment_date', 'Rencana Asesmen Ulang', { alert: 'due' }),
    ],
  }),

  /* ------------------------------------------------------------- 11. OJT */
  m({
    key: 'ojt_program',
    name: 'On the Job Training',
    nameId: 'On the Job Training (OJT)',
    scope: 'any',
    codePrefix: 'OJT',
    icon: '🧑‍🏭',
    workflow: WF.SIMPLE,
    standards: ['ISO 45001:2018 §7.2'],
    regulations: ['STCW 2010 - Onboard Training Record Book'],
    listFields: ['title', 'employee_name', 'mentor', 'start_date', 'progress_percent', 'result'],
    fields: [
      req('title', 'Program OJT'),
      f('employee_ref', 'Pegawai', 'employee', { required: true }),
      req('employee_name', 'Nama Pegawai'),
      f('position_target', 'Jabatan yang Disiapkan'),
      f('mentor', 'Mentor', 'user', { required: true }),
      f('supervisor', 'Supervisor Penilai', 'user'),
      dt('start_date', 'Tanggal Mulai', { required: true }),
      dt('end_date', 'Target Selesai', { alert: 'due' }),
      num('planned_hours', 'Jam OJT Direncanakan'),
      num('actual_hours', 'Jam OJT Terealisasi'),
      num('progress_percent', 'Progres (%)', { computed: 'ojtProgress', readonly: true }),
      num('logbook_entries', 'Jumlah Entri Logbook'),
      txt('logbook_summary', 'Ringkasan Logbook'),
      txt('competency_target', 'Kompetensi yang Dituju'),
      num('mentor_score', 'Nilai Mentor', { min: 0, max: 100, step: 0.1 }),
      num('supervisor_score', 'Nilai Supervisor', { min: 0, max: 100, step: 0.1 }),
      num('final_score', 'Nilai Akhir OJT', { computed: 'ojtFinalScore', readonly: true }),
      sel('result', 'Hasil OJT', ['Lulus', 'Perlu Perpanjangan', 'Tidak Lulus']),
      txt('mentor_note', 'Catatan Mentor'),
    ],
  }),

  /* --------------------------------------------------- 12. asesmen kompetensi */
  m({
    key: 'competency_assessment',
    name: 'Competency Assessment',
    nameId: 'Asesmen Kompetensi',
    scope: 'any',
    codePrefix: 'KOM',
    icon: '🎯',
    workflow: WF.SIMPLE,
    standards: ['ISO 45001:2018 §7.2', 'ISO 9001:2015 §7.2'],
    regulations: ['Peraturan BNSP tentang Sertifikasi Kompetensi Kerja'],
    listFields: ['employee_name', 'competency_area', 'assessment_date', 'level_result', 'gap_level'],
    labelField: 'employee_name',
    fields: [
      req('employee_name', 'Nama Pegawai'),
      f('employee_ref', 'Pegawai', 'employee', { required: true }),
      f('position', 'Jabatan'),
      f('division', 'Divisi / Unit Kerja'),
      req('competency_area', 'Bidang Kompetensi'),
      dt('assessment_date', 'Tanggal Asesmen', { required: true }),
      sel('assessment_method', 'Metode Asesmen', [
        'Uji Tulis', 'Wawancara', 'Observasi Kerja', 'Portofolio', 'Simulasi', 'Asesmen BNSP', 'Uji Praktek',
      ], { required: true }),
      sel('required_level', 'Tingkat Dipersyaratkan', COMPETENCY_LEVELS, { required: true }),
      sel('level_result', 'Tingkat Hasil Asesmen', COMPETENCY_LEVELS, { required: true }),
      num('gap_level', 'Kesenjangan (tingkat)', { computed: 'levelGap', readonly: true }),
      num('score', 'Nilai Asesmen', { min: 0, max: 100, step: 0.1 }),
      sel('result', 'Rekomendasi Asesor', ['Kompeten', 'Belum Kompeten', 'Kompeten dengan Catatan']),
      f('assessor', 'Asesor', 'user'),
      f('assessor_licence', 'Nomor Lisensi Asesor'),
      dt('valid_until', 'Hasil Berlaku Sampai', { alert: 'expiry' }),
      num('renewal_lead_days', 'Ambang Peringatan (hari)', { default: 60 }),
      f('cert_status', 'Status Berlaku', 'text', { computed: 'certStatus', readonly: true, values: CERT_STATES }),
      f('follow_up_training', 'Pelatihan Tindak Lanjut'),
      txt('gap_note', 'Uraian Kesenjangan'),
      txt('recommendation', 'Rekomendasi Pengembangan'),
    ],
  }),

  /* ------------------------------------------------- 13. skill gap analysis */
  m({
    key: 'skill_gap',
    name: 'Skill Gap Analysis',
    nameId: 'Analisis Kesenjangan Kompetensi',
    scope: 'any',
    codePrefix: 'GAP',
    icon: '📐',
    workflow: WF.CAPA,
    capa: true,
    standards: ['ISO 45001:2018 §7.2', 'ISO 9001:2015 §7.2'],
    regulations: ['PP No. 50 Tahun 2012 (SMK3) Elemen 12'],
    listFields: ['employee_name', 'position', 'required_training_count', 'owned_training_count', 'gap_count', 'gap_status'],
    labelField: 'employee_name',
    fields: [
      req('employee_name', 'Nama Pegawai'),
      f('employee_ref', 'Pegawai', 'employee', { required: true }),
      req('position', 'Jabatan'),
      f('division', 'Divisi / Unit Kerja'),
      dt('analysis_date', 'Tanggal Analisis', { required: true }),
      num('required_training_count', 'Pelatihan Wajib Dipersyaratkan', {
        required: true,
        help: 'Dihitung dari Matriks Pelatihan Wajib untuk jabatan ini.',
      }),
      num('owned_training_count', 'Pelatihan Sudah Dimiliki & Masih Berlaku', { required: true }),
      num('gap_count', 'Jumlah Kesenjangan', { computed: 'skillGapCount', readonly: true }),
      num('compliance_percent', 'Pemenuhan (%)', { computed: 'skillGapCompliance', readonly: true }),
      f('gap_status', 'Status Pemenuhan', 'text', { computed: 'skillGapStatus', readonly: true }),
      num('expired_certificate_count', 'Sertifikat Kedaluwarsa'),
      num('expiring_certificate_count', 'Sertifikat Akan Kedaluwarsa (90 hari)'),
      txt('missing_training', 'Daftar Pelatihan yang Belum Dipenuhi'),
      sel('priority', 'Prioritas Penutupan', PRIORITY),
      txt('closure_plan', 'Rencana Penutupan Kesenjangan'),
      num('estimated_cost', 'Perkiraan Biaya Penutupan (IDR)', { type: 'currency' }),
      dt('target_date', 'Target Penutupan', { alert: 'due' }),
      num('progress', 'Progres Penutupan (%)', { min: 0, max: 100 }),
      f('pic', 'Penanggung Jawab', 'user'),
    ],
  }),

  /* ---------------------------------------------------- 14. usulan pelatihan */
  m({
    key: 'training_request',
    name: 'Training Request',
    nameId: 'Usulan Kebutuhan Pelatihan',
    scope: 'any',
    codePrefix: 'TRQ',
    icon: '📨',
    workflow: WF.SIMPLE,
    standards: ['ISO 45001:2018 §7.2'],
    listFields: ['title', 'division', 'need_source', 'participant_count', 'request_date', 'priority'],
    fields: [
      req('title', 'Judul Usulan Pelatihan'),
      f('requester', 'Pengusul', 'user'),
      f('employee_ref', 'Pegawai Sasaran', 'employee'),
      f('division', 'Divisi / Unit Kerja'),
      f('position', 'Jabatan Sasaran'),
      f('training_ref', 'Training dari Katalog', 'training'),
      f('training_name', 'Nama Training Diusulkan'),
      sel('category', 'Kategori', TRAINING_CATEGORIES),
      dt('request_date', 'Tanggal Usulan', { required: true }),
      dt('needed_by', 'Dibutuhkan Sebelum', { alert: 'due' }),
      num('participant_count', 'Perkiraan Jumlah Peserta', { required: true }),
      sel('need_source', 'Sumber Kebutuhan', [
        'Hasil Analisis Kesenjangan Kompetensi', 'Temuan Audit', 'Hasil Investigasi Insiden',
        'Regulasi Baru / Perubahan Regulasi', 'Rotasi & Promosi Jabatan', 'Peralatan / Teknologi Baru',
        'Hasil Tinjauan Manajemen', 'Permintaan Individu', 'Sertifikat Akan Kedaluwarsa',
      ], { required: true }),
      f('source_reference', 'Referensi Sumber', 'text', { help: 'Nomor temuan audit, kode insiden, atau kode analisis kesenjangan.' }),
      txt('justification', 'Justifikasi Kebutuhan', { required: true }),
      num('estimated_cost', 'Perkiraan Biaya (IDR)', { type: 'currency' }),
      f('budget_available', 'Anggaran Tersedia', 'bool'),
      sel('priority', 'Prioritas', PRIORITY, { required: true }),
      f('approver', 'Pejabat Penyetuju', 'user'),
      txt('approval_note', 'Catatan Persetujuan'),
    ],
  }),

  /* ------------------------------------------------- 15. anggaran pelatihan */
  m({
    key: 'training_budget',
    name: 'Training Budget',
    nameId: 'Anggaran & Realisasi Pelatihan',
    scope: 'any',
    codePrefix: 'TBG',
    icon: '💰',
    workflow: WF.SIMPLE,
    standards: ['ISO 9001:2015 §7.1'],
    listFields: ['title', 'period', 'participant_count', 'total_budget', 'actual_cost', 'absorption_percent'],
    fields: [
      req('title', 'Nama Anggaran Pelatihan'),
      req('period', 'Periode', 'text', { placeholder: '2026 atau 2026-03' }),
      f('training_ref', 'Training', 'training'),
      f('training_name', 'Nama Training'),
      f('vendor_ref', 'Vendor', 'vendor'),
      num('participant_count', 'Jumlah Peserta', { required: true }),
      num('cost_training', 'Biaya Pelatihan / Vendor (IDR)', { type: 'currency', group: 'Rincian Biaya' }),
      num('cost_instructor', 'Honor Instruktur (IDR)', { type: 'currency', group: 'Rincian Biaya' }),
      num('cost_venue', 'Sewa Tempat & Hotel (IDR)', { type: 'currency', group: 'Rincian Biaya' }),
      num('cost_transport', 'Transportasi (IDR)', { type: 'currency', group: 'Rincian Biaya' }),
      num('cost_consumption', 'Konsumsi (IDR)', { type: 'currency', group: 'Rincian Biaya' }),
      num('cost_material', 'Modul & Perlengkapan (IDR)', { type: 'currency', group: 'Rincian Biaya' }),
      num('cost_certification', 'Sertifikasi & Uji Kompetensi (IDR)', { type: 'currency', group: 'Rincian Biaya' }),
      num('total_budget', 'Total Anggaran (IDR)', { type: 'currency', computed: 'trainingBudgetTotal', readonly: true }),
      num('actual_cost', 'Realisasi Biaya (IDR)', { type: 'currency' }),
      num('variance', 'Selisih Anggaran (IDR)', { type: 'currency', computed: 'budgetVariance', readonly: true }),
      num('absorption_percent', 'Serapan Anggaran (%)', { computed: 'budgetAbsorption', readonly: true }),
      num('cost_per_participant', 'Biaya per Peserta (IDR)', { type: 'currency', computed: 'costPerParticipant', readonly: true }),
      sel('funding_source', 'Sumber Dana', ['Anggaran Cabang', 'Anggaran Korporat', 'Program CSR', 'Beasiswa / Bantuan Vendor', 'Anggaran Regional']),
      f('cost_center', 'Pusat Biaya'),
      txt('notes', 'Catatan'),
    ],
  }),

  /* -------------------------------------------------- 16. vendor pelatihan */
  m({
    key: 'training_vendor',
    name: 'Training Vendor',
    nameId: 'Lembaga Pelatihan (Vendor)',
    master: true,
    scope: 'any',
    codePrefix: 'VTR',
    icon: '🏫',
    workflow: WF.RECORD,
    standards: ['ISO 9001:2015 §8.4'],
    regulations: ['Permenaker No. 04 Tahun 1995 (PJK3)', 'Peraturan BNSP tentang LSP'],
    listFields: ['name', 'vendor_type', 'accreditation_no', 'vendor_score', 'vendor_grade', 'vendor_status'],
    fields: [
      req('name', 'Nama Lembaga Pelatihan'),
      sel('vendor_type', 'Jenis Lembaga', [
        'PJK3 Kemnaker', 'Lembaga Sertifikasi Profesi (BNSP)', 'Balai Diklat Kemenhub',
        'Badan Klasifikasi (BKI)', 'Perguruan Tinggi / Politeknik', 'Konsultan & Training Provider',
        'Lembaga Internasional', 'Internal ASDP Corporate University',
      ], { required: true }),
      f('accreditation_no', 'Nomor Akreditasi / Penunjukan'),
      f('accreditation_body', 'Instansi Pemberi Akreditasi'),
      dt('accreditation_expiry', 'Masa Berlaku Akreditasi', { alert: 'expiry' }),
      f('npwp', 'NPWP'),
      f('address', 'Alamat', 'textarea'),
      f('pic_name', 'Nama PIC'),
      f('pic_phone', 'Telepon PIC'),
      f('pic_email', 'Surel PIC'),
      sel('specialisation', 'Bidang Pelatihan', TRAINING_CATEGORIES, { type: 'multiselect' }),
      f('contract_no', 'Nomor Kontrak / PKS'),
      dt('contract_start', 'Mulai Kontrak'),
      dt('contract_end', 'Akhir Kontrak', { alert: 'expiry' }),
      num('training_count', 'Jumlah Pelatihan Diselenggarakan'),
      num('participant_count', 'Jumlah Peserta Dilatih'),
      num('score_material', 'Nilai Materi', { min: 0, max: 100, group: 'Penilaian Vendor' }),
      num('score_instructor', 'Nilai Instruktur', { min: 0, max: 100, group: 'Penilaian Vendor' }),
      num('score_facility', 'Nilai Fasilitas & Peralatan', { min: 0, max: 100, group: 'Penilaian Vendor' }),
      num('score_service', 'Nilai Administrasi & Layanan', { min: 0, max: 100, group: 'Penilaian Vendor' }),
      num('score_certificate', 'Nilai Ketepatan Sertifikat', { min: 0, max: 100, group: 'Penilaian Vendor' }),
      num('vendor_score', 'Skor Vendor', { computed: 'vendorScore', readonly: true, group: 'Penilaian Vendor' }),
      f('vendor_grade', 'Grade Vendor', 'text', { computed: 'vendorGrade', readonly: true, group: 'Penilaian Vendor' }),
      sel('vendor_status', 'Status Kerja Sama', ['Aktif', 'Peringatan', 'Suspensi', 'Tidak Digunakan Lagi']),
      txt('document_note', 'Kelengkapan Dokumen'),
    ],
  }),

  /* ------------------------------------- 17. evaluasi pelatihan (level 1-2) */
  m({
    key: 'training_evaluation',
    name: 'Training Evaluation',
    nameId: 'Evaluasi Pelatihan (Kirkpatrick 1-2)',
    scope: 'any',
    codePrefix: 'TEV',
    icon: '📋',
    workflow: WF.MONITORING,
    standards: ['ISO 45001:2018 §7.2', 'ISO 9001:2015 §9.1'],
    listFields: ['title', 'evaluation_date', 'respondent_count', 'satisfaction_score', 'satisfaction_level'],
    fields: [
      req('title', 'Judul Evaluasi'),
      f('training_ref', 'Training', 'training'),
      f('training_name', 'Nama Training'),
      f('vendor_ref', 'Vendor Penyelenggara', 'vendor'),
      dt('evaluation_date', 'Tanggal Evaluasi', { required: true }),
      num('participant_count', 'Jumlah Peserta'),
      num('respondent_count', 'Jumlah Responden'),
      num('score_material', 'Nilai Materi', { min: 0, max: 100, group: 'Reaksi Peserta (Level 1)' }),
      num('score_trainer', 'Nilai Instruktur', { min: 0, max: 100, group: 'Reaksi Peserta (Level 1)' }),
      num('score_venue', 'Nilai Tempat & Fasilitas', { min: 0, max: 100, group: 'Reaksi Peserta (Level 1)' }),
      num('score_organizer', 'Nilai Penyelenggaraan', { min: 0, max: 100, group: 'Reaksi Peserta (Level 1)' }),
      num('score_relevance', 'Nilai Relevansi dengan Pekerjaan', { min: 0, max: 100, group: 'Reaksi Peserta (Level 1)' }),
      num('satisfaction_score', 'Indeks Kepuasan Pelatihan', { computed: 'trainingSatisfaction', readonly: true, group: 'Reaksi Peserta (Level 1)' }),
      f('satisfaction_level', 'Tingkat Kepuasan', 'text', { computed: 'trainingSatisfactionLevel', readonly: true, group: 'Reaksi Peserta (Level 1)' }),
      num('nps_score', 'Skor NPS Peserta', { min: -100, max: 100, group: 'Reaksi Peserta (Level 1)' }),
      num('pretest_avg', 'Rata-rata Pre-Test', { min: 0, max: 100, step: 0.1, group: 'Pembelajaran (Level 2)' }),
      num('posttest_avg', 'Rata-rata Post-Test', { min: 0, max: 100, step: 0.1, group: 'Pembelajaran (Level 2)' }),
      num('knowledge_gain', 'Kenaikan Pengetahuan (%)', { computed: 'knowledgeGain', readonly: true, group: 'Pembelajaran (Level 2)' }),
      num('pass_count', 'Peserta Lulus', { group: 'Pembelajaran (Level 2)' }),
      num('pass_rate', 'Tingkat Kelulusan (%)', { computed: 'passRate', readonly: true, group: 'Pembelajaran (Level 2)' }),
      txt('strength', 'Hal yang Sudah Baik'),
      txt('improvement', 'Usulan Perbaikan'),
    ],
  }),

  /* ---------------------------------- 18. efektivitas pelatihan (level 3-4) */
  m({
    key: 'training_effectiveness',
    name: 'Training Effectiveness',
    nameId: 'Efektivitas Pelatihan (Kirkpatrick 3-4)',
    scope: 'any',
    codePrefix: 'TEF',
    icon: '📈',
    workflow: WF.SIMPLE,
    capa: true,
    standards: ['ISO 45001:2018 §7.2', 'ISO 45001:2018 §9.1', 'ISO 9001:2015 §9.1'],
    listFields: ['title', 'evaluation_date', 'months_after', 'incident_reduction', 'effectiveness_level'],
    fields: [
      req('title', 'Judul Kajian Efektivitas'),
      f('training_ref', 'Training', 'training'),
      f('training_name', 'Nama Training'),
      f('evaluation_period', 'Periode Pengamatan', 'text', { placeholder: '6 bulan setelah pelatihan' }),
      dt('evaluation_date', 'Tanggal Kajian', { required: true }),
      num('months_after', 'Jarak dari Pelatihan (bulan)', { required: true }),
      num('participant_count', 'Jumlah Peserta Dikaji'),
      sel('behaviour_observed', 'Perubahan Perilaku Teramati', [
        'Diterapkan Konsisten', 'Diterapkan Sebagian', 'Belum Diterapkan',
      ], { required: true, group: 'Perilaku (Level 3)' }),
      num('implementation_score', 'Skor Penerapan di Tempat Kerja', { min: 0, max: 100, group: 'Perilaku (Level 3)' }),
      f('supervisor_confirmation', 'Dikonfirmasi Atasan Langsung', 'bool', { group: 'Perilaku (Level 3)' }),
      txt('behaviour_evidence', 'Bukti Penerapan', { group: 'Perilaku (Level 3)' }),
      num('incident_before', 'Insiden Sebelum', { group: 'Hasil (Level 4)' }),
      num('incident_after', 'Insiden Sesudah', { group: 'Hasil (Level 4)' }),
      num('near_miss_before', 'Near Miss Sebelum', { group: 'Hasil (Level 4)' }),
      num('near_miss_after', 'Near Miss Sesudah', { group: 'Hasil (Level 4)' }),
      num('unsafe_before', 'Tindakan/Kondisi Tidak Aman Sebelum', { group: 'Hasil (Level 4)' }),
      num('unsafe_after', 'Tindakan/Kondisi Tidak Aman Sesudah', { group: 'Hasil (Level 4)' }),
      num('audit_finding_before', 'Temuan Audit Sebelum', { group: 'Hasil (Level 4)' }),
      num('audit_finding_after', 'Temuan Audit Sesudah', { group: 'Hasil (Level 4)' }),
      num('kpi_before', 'Nilai KPI Sebelum', { step: 0.01, group: 'Hasil (Level 4)' }),
      num('kpi_after', 'Nilai KPI Sesudah', { step: 0.01, group: 'Hasil (Level 4)' }),
      num('incident_reduction', 'Penurunan Insiden (%)', { computed: 'incidentReduction', readonly: true, group: 'Hasil (Level 4)' }),
      num('kpi_improvement', 'Kenaikan KPI (%)', { computed: 'kpiImprovement', readonly: true, group: 'Hasil (Level 4)' }),
      f('effectiveness_level', 'Tingkat Efektivitas', 'text', {
        computed: 'trainingEffectivenessLevel',
        readonly: true,
        values: ['Sangat Efektif', 'Efektif', 'Cukup Efektif', 'Tidak Efektif'],
      }),
      txt('conclusion', 'Kesimpulan'),
      txt('follow_up', 'Tindak Lanjut'),
    ],
  }),

  /* ---------------------------------------- 19. pelaksanaan (dipindah dari N) */
  m({
    key: 'training_competency',
    name: 'Training Delivery Record',
    nameId: 'Pelaksanaan Pelatihan',
    icon: '🧑‍🏫',
    codePrefix: 'TRN',
    scope: 'any',
    workflow: WF.SIMPLE,
    capa: true,
    standards: ['ISO 45001:2018 §7.2', 'ISO 9001:2015 §7.2', 'STCW'],
    regulations: [
      'PP No. 50 Tahun 2012 (SMK3) Elemen 4 & 12',
      'Permenaker No. 02/MEN/1992 (Ahli K3)',
      'STCW - Sertifikasi Pelaut',
    ],
    fields: [
      req('title', 'Judul Pelatihan'),
      sel('training_category', 'Kategori', [
        'Induksi K3', 'Pelatihan Wajib Regulasi', 'Sertifikasi Kompetensi', 'Refreshment',
        'Pelatihan Darurat', 'Pelatihan Sistem Manajemen', 'Pelatihan Teknis', 'Pelatihan Pelayanan',
      ], { required: true }),
      sel('topic', 'Topik', [
        'Ahli K3 Umum', 'P3K di Tempat Kerja', 'Pemadam Kebakaran', 'Bekerja di Ketinggian',
        'Ruang Terbatas', 'LOTO', 'Operator Forklift', 'Operator Crane', 'Basic Safety Training (BST)',
        'Survival Craft (SCRB)', 'Advanced Fire Fighting (AFF)', 'Medical First Aid (MFA)',
        'Penanganan B3 & IMDG', 'Auditor Internal ISO', 'HIRADC', 'Investigasi Insiden',
        'Penanggulangan Tumpahan Minyak', 'Keamanan Informasi', 'Pelayanan Prima', 'ISPS Code',
      ]),
      dt('start_date', 'Tanggal Mulai', { required: true }),
      dt('end_date', 'Tanggal Selesai'),
      num('duration_hours', 'Durasi (jam)'),
      f('provider', 'Penyelenggara'),
      f('trainer', 'Instruktur'),
      sel('mandatory', 'Sifat', ['Wajib Regulasi', 'Wajib Internal', 'Pengembangan']),
      num('planned_participants', 'Target Peserta'),
      num('actual_participants', 'Realisasi Peserta'),
      f('participants', 'Daftar Peserta', 'textarea'),
      num('pretest_avg', 'Rata-rata Pre-Test', { step: 0.1 }),
      num('posttest_avg', 'Rata-rata Post-Test', { step: 0.1 }),
      num('pass_count', 'Jumlah Lulus'),
      f('certificate_issued', 'Sertifikat Diterbitkan', 'bool'),
      dt('certificate_valid_until', 'Sertifikat Berlaku Sampai', { alert: 'expiry' }),
      num('cost', 'Biaya (IDR)', { type: 'currency' }),
      sel('effectiveness', 'Evaluasi Efektivitas', ['Sangat Efektif', 'Efektif', 'Cukup', 'Kurang Efektif', 'Belum Dievaluasi']),
      txt('evaluation_note', 'Catatan Evaluasi'),
    ],
  }),
];
